import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Basic

set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false
set_option linter.unusedVariables false

namespace CausalSmith.Stat.ReverseKLTwoCoverage

open scoped BigOperators

variable {d : ℕ} {𝒳 𝒜 : Type*}
  [Fintype 𝒳] [Fintype 𝒜] [DecidableEq 𝒳] [DecidableEq 𝒜]
  [MeasurableSpace 𝒳] [MeasurableSpace 𝒜]
  [MeasurableSingletonClass 𝒳] [MeasurableSingletonClass 𝒜]
  (E : CommonExperiment d 𝒳 𝒜)

/-- Gibbs policy generated by an arbitrary bounded potential. -/
noncomputable def gibbsFromPotential (r : 𝒳 → 𝒜 → ℝ) : Policy 𝒳 𝒜 :=
  fun x a => E.reference x a * Real.exp (E.eta * r x a) /
    ∑ b, E.reference x b * Real.exp (E.eta * r x b)

/-- Regularized welfare when the context mass and reward potential are explicit. -/
noncomputable def welfareFromPotential (rho : 𝒳 → ℝ) (r : 𝒳 → 𝒜 → ℝ)
    (π : Policy 𝒳 𝒜) : ℝ :=
  (∑ x, rho x * ∑ a, π x a * r x a) -
    E.eta⁻¹ * ∑ x, rho x * policyKL π E.reference x

/-- Policy support inclusion used by finite KL identities. -/
def SupportedOnReference (π : Policy 𝒳 𝒜) : Prop :=
  ∀ x a, π x a ≠ 0 → E.reference x a ≠ 0

-- @node: gibbsPotentialNormalizer_pos
lemma gibbsPotentialNormalizer_pos (r : 𝒳 → 𝒜 → ℝ) (x : 𝒳) :
    0 < ∑ a, E.reference x a * Real.exp (E.eta * r x a) := by
  have hsum_ne : ∑ a, E.reference x a ≠ 0 := by
    rw [E.reference_isPolicy.2 x]
    norm_num
  obtain ⟨a, _, ha_ne⟩ :=
    Finset.exists_ne_zero_of_sum_ne_zero (s := Finset.univ) hsum_ne
  have ha_pos : 0 < E.reference x a :=
    lt_of_le_of_ne (E.reference_isPolicy.1 x a) (Ne.symm ha_ne)
  exact Finset.sum_pos'
    (fun b _ => mul_nonneg (E.reference_isPolicy.1 x b) (Real.exp_pos _).le)
    ⟨a, Finset.mem_univ _, mul_pos ha_pos (Real.exp_pos _)⟩

-- @node: gibbsFromPotential_isPolicy
lemma gibbsFromPotential_isPolicy (r : 𝒳 → 𝒜 → ℝ) :
    IsPolicy (gibbsFromPotential E r) := by
  constructor
  · intro x a
    exact div_nonneg
      (mul_nonneg (E.reference_isPolicy.1 x a) (Real.exp_pos _).le)
      (gibbsPotentialNormalizer_pos E r x).le
  · intro x
    simp only [gibbsFromPotential]
    rw [← Finset.sum_div]
    exact div_self (ne_of_gt (gibbsPotentialNormalizer_pos E r x))

-- @node: gibbsFromPotential_supported
lemma gibbsFromPotential_supported (r : 𝒳 → 𝒜 → ℝ) :
    SupportedOnReference E (gibbsFromPotential E r) := by
  intro x a hne
  by_contra href
  apply hne
  simp [gibbsFromPotential, href]

-- @node: gibbsFromPotential_ne_zero_iff_reference
lemma gibbsFromPotential_ne_zero_iff_reference
    (r : 𝒳 → 𝒜 → ℝ) (x : 𝒳) (a : 𝒜) :
    gibbsFromPotential E r x a ≠ 0 ↔ E.reference x a ≠ 0 := by
  constructor
  · exact gibbsFromPotential_supported E r x a
  · intro href
    simp only [gibbsFromPotential]
    exact div_ne_zero
      (mul_ne_zero href (ne_of_gt (Real.exp_pos _)))
      (ne_of_gt (gibbsPotentialNormalizer_pos E r x))

-- @node: policyKL_gibbsPotentials_nonneg
lemma policyKL_gibbsPotentials_nonneg
    (r g : 𝒳 → 𝒜 → ℝ) (x : 𝒳) :
    0 ≤ policyKL (gibbsFromPotential E g) (gibbsFromPotential E r) x := by
  let p := gibbsFromPotential E g x
  let q := gibbsFromPotential E r x
  have hmassp : ∑ a, p a = 1 := (gibbsFromPotential_isPolicy E g).2 x
  have hmassq : ∑ a, q a = 1 := (gibbsFromPotential_isPolicy E r).2 x
  have hterm : ∀ a, p a - q a ≤
      if p a = 0 then 0 else p a * Real.log (p a / q a) := by
    intro a
    split_ifs with hp
    · have hq : q a = 0 := by
        by_contra hq
        have href := (gibbsFromPotential_ne_zero_iff_reference E r x a).mp hq
        exact ((gibbsFromPotential_ne_zero_iff_reference E g x a).mpr href) hp
      simp [hp, hq]
    · have hq : q a ≠ 0 := by
        have href := (gibbsFromPotential_ne_zero_iff_reference E g x a).mp hp
        exact (gibbsFromPotential_ne_zero_iff_reference E r x a).mpr href
      have hp_pos : 0 < p a :=
        lt_of_le_of_ne ((gibbsFromPotential_isPolicy E g).1 x a) (Ne.symm hp)
      have hq_pos : 0 < q a :=
        lt_of_le_of_ne ((gibbsFromPotential_isPolicy E r).1 x a) (Ne.symm hq)
      have hlog := Real.one_sub_inv_le_log_of_pos (div_pos hp_pos hq_pos)
      have hmul := mul_le_mul_of_nonneg_left hlog hp_pos.le
      field_simp [hp, hq] at hmul
      exact hmul
  change 0 ≤ ∑ a, if p a = 0 then 0 else p a * Real.log (p a / q a)
  have hsum := Finset.sum_le_sum (s := Finset.univ) fun a _ ↦ hterm a
  rw [Finset.sum_sub_distrib, hmassp, hmassq] at hsum
  norm_num at hsum
  exact hsum

-- @node: gibbsPotential_log_ratio
lemma gibbsPotential_log_ratio (r g : 𝒳 → 𝒜 → ℝ) (x : 𝒳) (a : 𝒜)
    (href : E.reference x a ≠ 0) :
    Real.log (gibbsFromPotential E g x a / gibbsFromPotential E r x a) =
      E.eta * (g x a - r x a) +
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b)) := by
  have her : Real.exp (E.eta * r x a) ≠ 0 := ne_of_gt (Real.exp_pos _)
  have heg : Real.exp (E.eta * g x a) ≠ 0 := ne_of_gt (Real.exp_pos _)
  have hzr :
      (∑ b, E.reference x b * Real.exp (E.eta * r x b)) ≠ 0 :=
    ne_of_gt (gibbsPotentialNormalizer_pos E r x)
  have hzg :
      (∑ b, E.reference x b * Real.exp (E.eta * g x b)) ≠ 0 :=
    ne_of_gt (gibbsPotentialNormalizer_pos E g x)
  simp only [gibbsFromPotential]
  have hratio :
      (E.reference x a * Real.exp (E.eta * g x a) /
          ∑ b, E.reference x b * Real.exp (E.eta * g x b)) /
        (E.reference x a * Real.exp (E.eta * r x a) /
          ∑ b, E.reference x b * Real.exp (E.eta * r x b)) =
      (E.reference x a * Real.exp (E.eta * g x a) *
          ∑ b, E.reference x b * Real.exp (E.eta * r x b)) /
        (E.reference x a * Real.exp (E.eta * r x a) *
          ∑ b, E.reference x b * Real.exp (E.eta * g x b)) := by
    field_simp
  rw [hratio, Real.log_div
    (mul_ne_zero (mul_ne_zero href heg) hzr)
    (mul_ne_zero (mul_ne_zero href her) hzg)]
  rw [Real.log_mul (mul_ne_zero href heg) hzr,
    Real.log_mul (mul_ne_zero href her) hzg,
    Real.log_mul href heg, Real.log_mul href her,
    Real.log_exp, Real.log_exp]
  ring

-- @node: policyKL_gibbsPotentials_expansion
lemma policyKL_gibbsPotentials_expansion (r g : 𝒳 → 𝒜 → ℝ) (x : 𝒳) :
    policyKL (gibbsFromPotential E g) (gibbsFromPotential E r) x =
      E.eta * ∑ a, gibbsFromPotential E g x a * (g x a - r x a) +
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b)) := by
  rw [policyKL]
  calc
    (∑ a, if gibbsFromPotential E g x a = 0 then 0
      else gibbsFromPotential E g x a *
        Real.log (gibbsFromPotential E g x a / gibbsFromPotential E r x a)) =
        ∑ a, gibbsFromPotential E g x a *
          (E.eta * (g x a - r x a) +
            Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
            Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b))) := by
      apply Finset.sum_congr rfl
      intro a _
      split_ifs with ha
      · simp [ha]
      · have href : E.reference x a ≠ 0 :=
          gibbsFromPotential_supported E g x a ha
        rw [gibbsPotential_log_ratio E r g x a href]
    _ = _ := by
      have hterm : ∀ a,
          gibbsFromPotential E g x a *
              (E.eta * (g x a - r x a) +
                Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
                Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b))) =
            E.eta * (gibbsFromPotential E g x a * (g x a - r x a)) +
              gibbsFromPotential E g x a *
                Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
              gibbsFromPotential E g x a *
                Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b)) := by
        intro a
        ring
      simp_rw [hterm, Finset.sum_sub_distrib, Finset.sum_add_distrib]
      rw [← Finset.mul_sum, ← Finset.sum_mul, ← Finset.sum_mul,
        (gibbsFromPotential_isPolicy E g).2 x]
      ring

-- @node: policyKL_gibbsPotential_reference
lemma policyKL_gibbsPotential_reference (r : 𝒳 → 𝒜 → ℝ) (x : 𝒳) :
    policyKL (gibbsFromPotential E r) E.reference x =
      E.eta * ∑ a, gibbsFromPotential E r x a * r x a -
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) := by
  rw [policyKL]
  calc
    (∑ a, if gibbsFromPotential E r x a = 0 then 0
      else gibbsFromPotential E r x a *
        Real.log (gibbsFromPotential E r x a / E.reference x a)) =
        ∑ a, gibbsFromPotential E r x a *
          (E.eta * r x a -
            Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b))) := by
      apply Finset.sum_congr rfl
      intro a _
      split_ifs with ha
      · simp [ha]
      · have href : E.reference x a ≠ 0 :=
          gibbsFromPotential_supported E r x a ha
        have hexp : Real.exp (E.eta * r x a) ≠ 0 :=
          ne_of_gt (Real.exp_pos _)
        have hz :
            (∑ b, E.reference x b * Real.exp (E.eta * r x b)) ≠ 0 :=
          ne_of_gt (gibbsPotentialNormalizer_pos E r x)
        simp only [gibbsFromPotential]
        have hratio :
            (E.reference x a * Real.exp (E.eta * r x a) /
                ∑ b, E.reference x b * Real.exp (E.eta * r x b)) /
              E.reference x a =
            Real.exp (E.eta * r x a) /
              ∑ b, E.reference x b * Real.exp (E.eta * r x b) := by
          field_simp
        rw [hratio, Real.log_div hexp hz, Real.log_exp]
    _ = _ := by
      simp only [mul_sub]
      rw [Finset.sum_sub_distrib]
      have hfirst :
          (∑ a, gibbsFromPotential E r x a * (E.eta * r x a)) =
            E.eta * ∑ a, gibbsFromPotential E r x a * r x a := by
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro a _
        ring
      rw [hfirst, ← Finset.sum_mul, (gibbsFromPotential_isPolicy E r).2 x]
      ring

-- @node: welfareFromPotential_gibbs
lemma welfareFromPotential_gibbs (rho : 𝒳 → ℝ) (r : 𝒳 → 𝒜 → ℝ) :
    welfareFromPotential E rho r (gibbsFromPotential E r) =
      E.eta⁻¹ * ∑ x, rho x *
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) := by
  rw [welfareFromPotential]
  simp_rw [policyKL_gibbsPotential_reference E]
  have heta : E.eta ≠ 0 := ne_of_gt E.eta_pos
  field_simp
  rw [Finset.sum_mul]
  have hdist : ∀ x,
      rho x * (E.eta * ∑ a, gibbsFromPotential E r x a * r x a -
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b))) =
      (rho x * ∑ a, gibbsFromPotential E r x a * r x a) * E.eta -
        rho x * Real.log
          (∑ b, E.reference x b * Real.exp (E.eta * r x b)) := by
    intro x
    ring
  simp_rw [hdist, Finset.sum_sub_distrib]
  ring

-- @node: welfareFromPotential_regret_eq_kl
lemma welfareFromPotential_regret_eq_kl
    (rho : 𝒳 → ℝ) (r g : 𝒳 → 𝒜 → ℝ) :
    welfareFromPotential E rho r (gibbsFromPotential E r) -
        welfareFromPotential E rho r (gibbsFromPotential E g) =
      E.eta⁻¹ * ∑ x, rho x *
        policyKL (gibbsFromPotential E g) (gibbsFromPotential E r) x := by
  rw [welfareFromPotential_gibbs E]
  rw [welfareFromPotential]
  simp_rw [policyKL_gibbsPotential_reference E,
    policyKL_gibbsPotentials_expansion E]
  have heta : E.eta ≠ 0 := ne_of_gt E.eta_pos
  field_simp
  have hleft : ∀ x,
      rho x * (E.eta * ∑ a, gibbsFromPotential E g x a * g x a -
        Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b))) =
      E.eta * rho x * ∑ a, gibbsFromPotential E g x a * g x a -
        rho x * Real.log
          (∑ b, E.reference x b * Real.exp (E.eta * g x b)) := by
    intro x
    ring
  have hright : ∀ x,
      rho x *
          (E.eta * ∑ a, gibbsFromPotential E g x a * (g x a - r x a) +
            Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
            Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b))) =
        E.eta * rho x * ∑ a, gibbsFromPotential E g x a * g x a -
          E.eta * rho x * ∑ a, gibbsFromPotential E g x a * r x a +
          rho x * Real.log
            (∑ b, E.reference x b * Real.exp (E.eta * r x b)) -
          rho x * Real.log
            (∑ b, E.reference x b * Real.exp (E.eta * g x b)) := by
    intro x
    have hin :
        (∑ a, gibbsFromPotential E g x a * (g x a - r x a)) =
          (∑ a, gibbsFromPotential E g x a * g x a) -
            ∑ a, gibbsFromPotential E g x a * r x a := by
      calc
        _ = ∑ a, (gibbsFromPotential E g x a * g x a -
            gibbsFromPotential E g x a * r x a) := by
          apply Finset.sum_congr rfl
          intro a _
          ring
        _ = _ := by rw [Finset.sum_sub_distrib]
    rw [hin]
    ring
  simp_rw [hleft, hright, Finset.sum_sub_distrib, Finset.sum_add_distrib,
    Finset.mul_sum]
  rw [Finset.sum_sub_distrib]
  have hr_assoc :
      (∑ x, ∑ a, E.eta * (rho x * (gibbsFromPotential E g x a * r x a))) =
        ∑ x, ∑ a, E.eta * rho x * gibbsFromPotential E g x a * r x a := by
    apply Finset.sum_congr rfl
    intro x _
    apply Finset.sum_congr rfl
    intro a _
    ring
  rw [hr_assoc]
  simp only [mul_assoc]
  abel

-- @node: symmetrized_log_ratio_le
lemma symmetrized_log_ratio_le {u v : ℝ} (hu : 0 < u) (hv : 0 < v) :
    (u - v) * Real.log (u / v) ≤
      (u + v) / 2 * (Real.log (u / v)) ^ 2 := by
  have hcase : ∀ {a b : ℝ}, 0 < a → 0 < b → b ≤ a →
      (a - b) * Real.log (a / b) ≤
        (a + b) / 2 * (Real.log (a / b)) ^ 2 := by
    intro a b ha hb hba
    have hx : 0 ≤ (a - b) / b := div_nonneg (sub_nonneg.mpr hba) hb.le
    have hlog := Real.le_log_one_add_of_nonneg hx
    have hone : 1 + (a - b) / b = a / b := by
      field_simp
      ring
    have hfrac :
        2 * ((a - b) / b) / ((a - b) / b + 2) =
          2 * (a - b) / (a + b) := by
      have hden : (a - b) / b + 2 = (a + b) / b := by
        field_simp
        ring
      rw [hden]
      apply (div_eq_div_iff
        (div_ne_zero (ne_of_gt (add_pos ha hb)) (ne_of_gt hb))
        (ne_of_gt (add_pos ha hb))).2
      ring
    rw [hone, hfrac] at hlog
    have hab_pos : 0 < a + b := add_pos ha hb
    have hscaled : 2 * (a - b) ≤ (a + b) * Real.log (a / b) := by
      have := mul_le_mul_of_nonneg_left hlog hab_pos.le
      field_simp [ne_of_gt hab_pos] at this
      linarith
    have hlog_nonneg : 0 ≤ Real.log (a / b) :=
      Real.log_nonneg ((one_le_div hb).2 hba)
    have hmul := mul_nonneg hlog_nonneg
      (sub_nonneg.mpr hscaled)
    nlinarith
  by_cases hvu : v ≤ u
  · exact hcase hu hv hvu
  · have huv : u ≤ v := le_of_not_ge hvu
    have h := hcase hv hu huv
    have hlog :
        Real.log (v / u) = -Real.log (u / v) := by
      rw [Real.log_div (ne_of_gt hv) (ne_of_gt hu),
        Real.log_div (ne_of_gt hu) (ne_of_gt hv)]
      ring
    rw [hlog] at h
    nlinarith

-- @node: weighted_policy_mean_abs_le_sqrt
lemma weighted_policy_mean_abs_le_sqrt
    (rho : 𝒳 → ℝ) (p : Policy 𝒳 𝒜) (h : 𝒳 → 𝒜 → ℝ)
    (hrho_nonneg : ∀ x, 0 ≤ rho x) (hrho_mass : ∑ x, rho x = 1)
    (hp : IsPolicy p) :
    |∑ x, rho x * ∑ a, p x a * h x a| ≤
      Real.sqrt (∑ x, rho x * ∑ a, p x a * (h x a) ^ 2) := by
  let w : 𝒳 × 𝒜 → ℝ := fun z => rho z.1 * p z.1 z.2
  let H : 𝒳 × 𝒜 → ℝ := fun z => h z.1 z.2
  have hw : ∀ z, 0 ≤ w z :=
    fun z ↦ mul_nonneg (hrho_nonneg z.1) (hp.1 z.1 z.2)
  have hwmass : ∑ z : 𝒳 × 𝒜, w z = 1 := by
    rw [Fintype.sum_prod_type]
    simp_rw [w, ← Finset.mul_sum, hp.2]
    simpa using hrho_mass
  have hsqrt_sq : ∀ z, (Real.sqrt (w z)) ^ 2 = w z :=
    fun z ↦ Real.sq_sqrt (hw z)
  have hupper := Real.sum_mul_le_sqrt_mul_sqrt Finset.univ
    (fun z : 𝒳 × 𝒜 => Real.sqrt (w z))
    (fun z : 𝒳 × 𝒜 => Real.sqrt (w z) * H z)
  have hlower := Real.sum_mul_le_sqrt_mul_sqrt Finset.univ
    (fun z : 𝒳 × 𝒜 => Real.sqrt (w z))
    (fun z : 𝒳 × 𝒜 => -(Real.sqrt (w z) * H z))
  have hprod : ∀ z,
      Real.sqrt (w z) * (Real.sqrt (w z) * H z) = w z * H z := by
    intro z
    rw [← mul_assoc, ← pow_two, hsqrt_sq]
  have hsqprod : ∀ z,
      (Real.sqrt (w z) * H z) ^ 2 = w z * H z ^ 2 := by
    intro z
    rw [mul_pow, hsqrt_sq]
  have hprodneg : ∀ z,
      Real.sqrt (w z) * -(Real.sqrt (w z) * H z) = -(w z * H z) := by
    intro z
    rw [mul_neg, hprod]
  simp_rw [hprod, hsqprod, hsqrt_sq, hwmass, Real.sqrt_one, one_mul] at hupper
  simp_rw [hprodneg, neg_sq, hsqprod, hsqrt_sq, hwmass,
    Real.sqrt_one, one_mul] at hlower
  simp_rw [Fintype.sum_prod_type] at hupper hlower
  rw [abs_le]
  constructor
  · have hlower' :
        -(∑ x, rho x * ∑ a, p x a * h x a) ≤
          Real.sqrt (∑ x, rho x * ∑ a, p x a * h x a ^ 2) := by
      simpa [w, H, Finset.mul_sum, mul_assoc] using hlower
    linarith
  · simpa [w, H, Finset.mul_sum, mul_assoc] using hupper

-- @node: two_endpoint_gibbs_slow
lemma two_endpoint_gibbs_slow
    (rho : 𝒳 → ℝ) (r g : 𝒳 → 𝒜 → ℝ)
    (hrho_nonneg : ∀ x, 0 ≤ rho x) (hrho_mass : ∑ x, rho x = 1) :
    let A :=
      ∑ x, rho x * ∑ a, gibbsFromPotential E r x a * (g x a - r x a) ^ 2
    let B :=
      ∑ x, rho x * ∑ a, gibbsFromPotential E g x a * (g x a - r x a) ^ 2
    welfareFromPotential E rho r (gibbsFromPotential E r) -
        welfareFromPotential E rho r (gibbsFromPotential E g) ≤
      Real.sqrt A + Real.sqrt B := by
  dsimp only
  let delta : 𝒳 → 𝒜 → ℝ := fun x a => g x a - r x a
  let p := gibbsFromPotential E r
  let q := gibbsFromPotential E g
  let mp := ∑ x, rho x * ∑ a, p x a * delta x a
  let mq := ∑ x, rho x * ∑ a, q x a * delta x a
  let kp := ∑ x, rho x * policyKL p q x
  let kq := ∑ x, rho x * policyKL q p x
  have hkp : 0 ≤ kp := by
    apply Finset.sum_nonneg
    intro x _
    exact mul_nonneg (hrho_nonneg x)
      (policyKL_gibbsPotentials_nonneg E g r x)
  have hjeff : kp + kq = E.eta * (mq - mp) := by
    simp only [kp, kq, p, q, mp, mq, delta]
    simp_rw [policyKL_gibbsPotentials_expansion E]
    have hdelta : ∀ (x : 𝒳) (s : 𝒳 → 𝒜 → ℝ),
        (∑ a, gibbsFromPotential E s x a * (g x a - r x a)) =
          (∑ a, gibbsFromPotential E s x a * g x a) -
            ∑ a, gibbsFromPotential E s x a * r x a := by
      intro x s
      calc
        _ = ∑ a, (gibbsFromPotential E s x a * g x a -
            gibbsFromPotential E s x a * r x a) := by
          apply Finset.sum_congr rfl
          intro a _
          ring
        _ = _ := by rw [Finset.sum_sub_distrib]
    have hdeltaRev : ∀ (x : 𝒳) (s : 𝒳 → 𝒜 → ℝ),
        (∑ a, gibbsFromPotential E s x a * (r x a - g x a)) =
          -((∑ a, gibbsFromPotential E s x a * g x a) -
            ∑ a, gibbsFromPotential E s x a * r x a) := by
      intro x s
      calc
        _ = ∑ a, (gibbsFromPotential E s x a * r x a -
            gibbsFromPotential E s x a * g x a) := by
          apply Finset.sum_congr rfl
          intro a _
          ring
        _ = _ := by rw [Finset.sum_sub_distrib]; ring
    simp_rw [hdelta, hdeltaRev]
    rw [← Finset.sum_add_distrib, ← Finset.sum_sub_distrib,
      Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro x _
    ring
  have hkq : kq ≤ E.eta * (mq - mp) := by linarith
  have hreg :
      welfareFromPotential E rho r (gibbsFromPotential E r) -
          welfareFromPotential E rho r (gibbsFromPotential E g) =
        E.eta⁻¹ * kq := by
    simpa only [kq, p, q] using welfareFromPotential_regret_eq_kl E rho r g
  have hmean :
      welfareFromPotential E rho r (gibbsFromPotential E r) -
          welfareFromPotential E rho r (gibbsFromPotential E g) ≤ mq - mp := by
    rw [hreg]
    have hinv : 0 ≤ E.eta⁻¹ := (inv_pos.mpr E.eta_pos).le
    calc
      E.eta⁻¹ * kq ≤ E.eta⁻¹ * (E.eta * (mq - mp)) :=
        mul_le_mul_of_nonneg_left hkq hinv
      _ = mq - mp := by
        rw [← mul_assoc, inv_mul_cancel₀ (ne_of_gt E.eta_pos), one_mul]
  have hmp := weighted_policy_mean_abs_le_sqrt
    rho p delta hrho_nonneg hrho_mass
      (gibbsFromPotential_isPolicy E r)
  have hmq := weighted_policy_mean_abs_le_sqrt
    rho q delta hrho_nonneg hrho_mass
      (gibbsFromPotential_isPolicy E g)
  have hmeans : mq - mp ≤
      Real.sqrt
          (∑ x, rho x * ∑ a, p x a * (delta x a) ^ 2) +
        Real.sqrt
          (∑ x, rho x * ∑ a, q x a * (delta x a) ^ 2) := by
    have hmp' : -Real.sqrt
          (∑ x, rho x * ∑ a, p x a * (delta x a) ^ 2) ≤ mp :=
      (abs_le.mp hmp).1
    have hmq' : mq ≤ Real.sqrt
          (∑ x, rho x * ∑ a, q x a * (delta x a) ^ 2) :=
      (abs_le.mp hmq).2
    linarith
  exact hmean.trans (by simpa only [mp, mq, p, q, delta] using hmeans)

-- @node: two_endpoint_gibbs_fast
lemma two_endpoint_gibbs_fast
    (rho : 𝒳 → ℝ) (r g : 𝒳 → 𝒜 → ℝ)
    (hrho_nonneg : ∀ x, 0 ≤ rho x) :
    let A :=
      ∑ x, rho x * ∑ a, gibbsFromPotential E r x a * (g x a - r x a) ^ 2
    let B :=
      ∑ x, rho x * ∑ a, gibbsFromPotential E g x a * (g x a - r x a) ^ 2
    welfareFromPotential E rho r (gibbsFromPotential E r) -
        welfareFromPotential E rho r (gibbsFromPotential E g) ≤
      E.eta * (A + B) := by
  dsimp only
  let p := gibbsFromPotential E r
  let q := gibbsFromPotential E g
  let delta : 𝒳 → 𝒜 → ℝ := fun x a => g x a - r x a
  let mp : 𝒳 → ℝ := fun x => ∑ a, p x a * delta x a
  let mq : 𝒳 → ℝ := fun x => ∑ a, q x a * delta x a
  let ap : 𝒳 → ℝ := fun x => ∑ a, p x a * (delta x a) ^ 2
  let aq : 𝒳 → ℝ := fun x => ∑ a, q x a * (delta x a) ^ 2
  let c : 𝒳 → ℝ := fun x =>
    (Real.log (∑ b, E.reference x b * Real.exp (E.eta * g x b)) -
      Real.log (∑ b, E.reference x b * Real.exp (E.eta * r x b))) / E.eta
  have heta0 : 0 < E.eta := E.eta_pos
  have heta_ne : E.eta ≠ 0 := ne_of_gt heta0
  have hp_pol : IsPolicy p := gibbsFromPotential_isPolicy E r
  have hq_pol : IsPolicy q := gibbsFromPotential_isPolicy E g
  have hkl_qp : ∀ x, policyKL q p x = E.eta * (mq x - c x) := by
    intro x
    rw [policyKL_gibbsPotentials_expansion E]
    simp only [p, q, mq, delta, c]
    field_simp
    ring
  have hkl_pq : ∀ x, policyKL p q x = E.eta * (c x - mp x) := by
    intro x
    rw [policyKL_gibbsPotentials_expansion E]
    simp only [p, q, mp, delta, c]
    rw [show (∑ a, gibbsFromPotential E r x a * (r x a - g x a)) =
        -(∑ a, gibbsFromPotential E r x a * (g x a - r x a)) by
      rw [← Finset.sum_neg_distrib]
      apply Finset.sum_congr rfl
      intro a _
      ring]
    field_simp
    ring
  have hcmp : ∀ x, mp x ≤ c x ∧ c x ≤ mq x := by
    intro x
    have hpq := policyKL_gibbsPotentials_nonneg E g r x
    have hqp := policyKL_gibbsPotentials_nonneg E r g x
    change 0 ≤ policyKL p q x at hpq
    change 0 ≤ policyKL q p x at hqp
    rw [hkl_pq x] at hpq
    rw [hkl_qp x] at hqp
    constructor <;> nlinarith
  have hmeanp : ∀ x, (mp x) ^ 2 ≤ ap x := by
    intro x
    have h := weighted_policy_mean_abs_le_sqrt
      (fun _ : Unit => 1) (fun _ => p x) (fun _ => delta x)
      (fun _ => zero_le_one) (by simp) (by
        constructor
        · exact fun _ a => hp_pol.1 x a
        · exact fun _ => hp_pol.2 x)
    simp only [Finset.univ_unique, Finset.sum_singleton, one_mul] at h
    have hap : 0 ≤ ap x := by
      apply Finset.sum_nonneg
      intro a _
      exact mul_nonneg (hp_pol.1 x a) (sq_nonneg _)
    have hsqrt := Real.sq_sqrt hap
    change |mp x| ≤ Real.sqrt (ap x) at h
    have hs := mul_self_le_mul_self (abs_nonneg (mp x)) h
    rw [← pow_two, ← pow_two, sq_abs, hsqrt] at hs
    exact hs
  have hmeanq : ∀ x, (mq x) ^ 2 ≤ aq x := by
    intro x
    have h := weighted_policy_mean_abs_le_sqrt
      (fun _ : Unit => 1) (fun _ => q x) (fun _ => delta x)
      (fun _ => zero_le_one) (by simp) (by
        constructor
        · exact fun _ a => hq_pol.1 x a
        · exact fun _ => hq_pol.2 x)
    simp only [Finset.univ_unique, Finset.sum_singleton, one_mul] at h
    have haq : 0 ≤ aq x := by
      apply Finset.sum_nonneg
      intro a _
      exact mul_nonneg (hq_pol.1 x a) (sq_nonneg _)
    have hsqrt := Real.sq_sqrt haq
    change |mq x| ≤ Real.sqrt (aq x) at h
    have hs := mul_self_le_mul_self (abs_nonneg (mq x)) h
    rw [← pow_two, ← pow_two, sq_abs, hsqrt] at hs
    exact hs
  have hcenter : ∀ x,
      (∑ a, p x a * (delta x a - c x) ^ 2) +
        ∑ a, q x a * (delta x a - c x) ^ 2 ≤
      2 * (ap x + aq x) := by
    intro x
    have hpc := (hcmp x).1
    have hcq := (hcmp x).2
    have hbetween : (c x - mp x) * (c x - mq x) ≤ 0 :=
      mul_nonpos_of_nonneg_of_nonpos (sub_nonneg.mpr hpc) (sub_nonpos.mpr hcq)
    have hp_expand :
        (∑ a, p x a * (delta x a - c x) ^ 2) =
          ap x - 2 * c x * mp x + (c x) ^ 2 := by
      calc
        _ = ∑ a, (p x a * (delta x a) ^ 2 -
            2 * c x * (p x a * delta x a) + p x a * (c x) ^ 2) := by
          apply Finset.sum_congr rfl
          intro a _
          ring
        _ = _ := by
          rw [Finset.sum_add_distrib, Finset.sum_sub_distrib,
            ← Finset.sum_mul, hp_pol.2 x]
          simp only [ap, mp]
          rw [Finset.mul_sum]
          ring
    have hq_expand :
        (∑ a, q x a * (delta x a - c x) ^ 2) =
          aq x - 2 * c x * mq x + (c x) ^ 2 := by
      calc
        _ = ∑ a, (q x a * (delta x a) ^ 2 -
            2 * c x * (q x a * delta x a) + q x a * (c x) ^ 2) := by
          apply Finset.sum_congr rfl
          intro a _
          ring
        _ = _ := by
          rw [Finset.sum_add_distrib, Finset.sum_sub_distrib,
            ← Finset.sum_mul, hq_pol.2 x]
          simp only [aq, mq]
          rw [Finset.mul_sum]
          ring
    rw [hp_expand, hq_expand]
    nlinarith [hmeanp x, hmeanq x, sq_nonneg (mp x + mq x)]
  have hjeff : ∀ x,
      policyKL q p x + policyKL p q x ≤
        E.eta ^ 2 * (ap x + aq x) := by
    intro x
    have hsum : policyKL q p x + policyKL p q x ≤
        E.eta ^ 2 / 2 *
          ((∑ a, p x a * (delta x a - c x) ^ 2) +
            ∑ a, q x a * (delta x a - c x) ^ 2) := by
      rw [policyKL, policyKL]
      have hterm : ∀ a,
          (if q x a = 0 then 0 else q x a * Real.log (q x a / p x a)) +
              (if p x a = 0 then 0 else p x a * Real.log (p x a / q x a)) ≤
            E.eta ^ 2 / 2 *
              (p x a * (delta x a - c x) ^ 2 +
                q x a * (delta x a - c x) ^ 2) := by
        intro a
        by_cases href : E.reference x a = 0
        · have hp0 : p x a = 0 := by simp [p, gibbsFromPotential, href]
          have hq0 : q x a = 0 := by simp [q, gibbsFromPotential, href]
          simp [hp0, hq0]
        · have hp0 : p x a ≠ 0 :=
            gibbsFromPotential_ne_zero_iff_reference E r x a |>.2 href
          have hq0 : q x a ≠ 0 :=
            gibbsFromPotential_ne_zero_iff_reference E g x a |>.2 href
          have hp_pos := lt_of_le_of_ne (hp_pol.1 x a) (Ne.symm hp0)
          have hq_pos := lt_of_le_of_ne (hq_pol.1 x a) (Ne.symm hq0)
          have hsymm := symmetrized_log_ratio_le hp_pos hq_pos
          have hlog :
              Real.log (q x a / p x a) =
                E.eta * (delta x a - c x) := by
            rw [gibbsPotential_log_ratio E r g x a href]
            simp only [delta, c]
            field_simp
            ring
          have hlog_rev :
              Real.log (p x a / q x a) =
                -Real.log (q x a / p x a) := by
            rw [Real.log_div hp0 hq0, Real.log_div hq0 hp0]
            ring
          simp only [if_neg hp0, if_neg hq0]
          rw [hlog_rev, hlog] at hsymm ⊢
          nlinarith [hsymm]
      rw [← Finset.sum_add_distrib]
      calc
        _ ≤ ∑ a, E.eta ^ 2 / 2 *
            (p x a * (delta x a - c x) ^ 2 +
              q x a * (delta x a - c x) ^ 2) :=
          Finset.sum_le_sum fun a _ => hterm a
        _ = _ := by
          rw [← Finset.mul_sum]
          congr 2
          rw [Finset.sum_add_distrib]
    calc
      _ ≤ E.eta ^ 2 / 2 *
          ((∑ a, p x a * (delta x a - c x) ^ 2) +
            ∑ a, q x a * (delta x a - c x) ^ 2) := hsum
      _ ≤ E.eta ^ 2 * (ap x + aq x) := by
        have heta_sq : 0 ≤ E.eta ^ 2 := sq_nonneg _
        nlinarith [hcenter x]
  rw [welfareFromPotential_regret_eq_kl E]
  have hpoint : ∀ x,
      E.eta⁻¹ * (rho x * policyKL q p x) ≤
        rho x * (E.eta * (ap x + aq x)) := by
    intro x
    have hpq := policyKL_gibbsPotentials_nonneg E g r x
    change 0 ≤ policyKL p q x at hpq
    have hj := hjeff x
    have hqbound : policyKL q p x ≤ E.eta ^ 2 * (ap x + aq x) := by
      linarith
    have hrho := hrho_nonneg x
    have hinv : 0 ≤ E.eta⁻¹ := (inv_pos.mpr heta0).le
    calc
      E.eta⁻¹ * (rho x * policyKL q p x) ≤
          E.eta⁻¹ * (rho x * (E.eta ^ 2 * (ap x + aq x))) :=
        mul_le_mul_of_nonneg_left
          (mul_le_mul_of_nonneg_left hqbound hrho) hinv
      _ = rho x * (E.eta * (ap x + aq x)) := by
        field_simp
  calc
    E.eta⁻¹ * ∑ x, rho x * policyKL q p x =
        ∑ x, E.eta⁻¹ * (rho x * policyKL q p x) := by rw [Finset.mul_sum]
    _ ≤ ∑ x, rho x * (E.eta * (ap x + aq x)) :=
      Finset.sum_le_sum fun x _ => hpoint x
    _ = E.eta *
        ((∑ x, rho x * ∑ a, gibbsFromPotential E r x a *
            (g x a - r x a) ^ 2) +
          ∑ x, rho x * ∑ a, gibbsFromPotential E g x a *
            (g x a - r x a) ^ 2) := by
      simp only [p, q, delta, ap, aq]
      calc
        _ = ∑ x, E.eta * (rho x *
            ((∑ a, gibbsFromPotential E r x a * (g x a - r x a) ^ 2) +
              ∑ a, gibbsFromPotential E g x a * (g x a - r x a) ^ 2)) := by
          apply Finset.sum_congr rfl
          intro x _
          ring
        _ = E.eta * ∑ x, rho x *
            ((∑ a, gibbsFromPotential E r x a * (g x a - r x a) ^ 2) +
              ∑ a, gibbsFromPotential E g x a * (g x a - r x a) ^ 2) := by
          rw [Finset.mul_sum]
        _ = _ := by
          apply congrArg (fun z => E.eta * z)
          rw [← Finset.sum_add_distrib]
          apply Finset.sum_congr rfl
          intro x _
          ring

-- @node: gibbsNormalizer_pos
lemma gibbsNormalizer_pos (P : BanditLaw E) (x : 𝒳) :
    0 < gibbsNormalizer E P x := by
  have href_nonneg : ∀ a, 0 ≤ E.reference x a :=
    fun a => E.reference_isPolicy.1 x a
  have hsum_ne : ∑ a, E.reference x a ≠ 0 := by
    rw [E.reference_isPolicy.2 x]
    norm_num
  obtain ⟨a, _, ha_ne⟩ :=
    Finset.exists_ne_zero_of_sum_ne_zero (s := Finset.univ) hsum_ne
  have ha_pos : 0 < E.reference x a :=
    lt_of_le_of_ne (href_nonneg a) (Ne.symm ha_ne)
  exact Finset.sum_pos'
    (fun b _ => mul_nonneg (href_nonneg b) (Real.exp_pos _).le)
    ⟨a, Finset.mem_univ _, mul_pos ha_pos (Real.exp_pos _)⟩

-- @node: gibbsPolicy_isPolicy
lemma gibbsPolicy_isPolicy (P : BanditLaw E) :
    IsPolicy (gibbsPolicy E P) := by
  constructor
  · intro x a
    exact div_nonneg
      (mul_nonneg (E.reference_isPolicy.1 x a) (Real.exp_pos _).le)
      (gibbsNormalizer_pos E P x).le
  · intro x
    simp only [gibbsPolicy, gibbsNormalizer]
    rw [← Finset.sum_div]
    exact div_self (ne_of_gt (gibbsNormalizer_pos E P x))

-- @node: gibbs_log_ratio
lemma gibbs_log_ratio (P : BanditLaw E) (π : Policy 𝒳 𝒜)
    (hsupp : SupportedOnReference E π) (x : 𝒳) (a : 𝒜)
    (hπa : π x a ≠ 0) :
    Real.log (π x a / gibbsPolicy E P x a) =
      Real.log (π x a / E.reference x a) -
        E.eta * linearReward P x a + Real.log (gibbsNormalizer E P x) := by
  have href : E.reference x a ≠ 0 := hsupp x a hπa
  have hexp : Real.exp (E.eta * linearReward P x a) ≠ 0 :=
    ne_of_gt (Real.exp_pos _)
  have hZ : gibbsNormalizer E P x ≠ 0 :=
    ne_of_gt (gibbsNormalizer_pos E P x)
  have hgibbs : gibbsPolicy E P x a ≠ 0 := by
    simp only [gibbsPolicy]
    exact div_ne_zero (mul_ne_zero href hexp) hZ
  rw [Real.log_div hπa hgibbs, Real.log_div hπa href]
  simp only [gibbsPolicy]
  rw [Real.log_div (mul_ne_zero href hexp) hZ, Real.log_mul href hexp,
    Real.log_exp]
  ring

-- @node: policyKL_gibbs_expansion
lemma policyKL_gibbs_expansion (P : BanditLaw E) (π : Policy 𝒳 𝒜)
    (hπ : IsPolicy π) (hsupp : SupportedOnReference E π) (x : 𝒳) :
    policyKL π (gibbsPolicy E P) x =
      policyKL π E.reference x -
        E.eta * ∑ a, π x a * linearReward P x a +
        Real.log (gibbsNormalizer E P x) := by
  rw [policyKL, policyKL]
  calc
    (∑ a, if π x a = 0 then 0
      else π x a * Real.log (π x a / gibbsPolicy E P x a)) =
        ∑ a, ((if π x a = 0 then 0
          else π x a * Real.log (π x a / E.reference x a)) -
          E.eta * (π x a * linearReward P x a) +
          π x a * Real.log (gibbsNormalizer E P x)) := by
      apply Finset.sum_congr rfl
      intro a _
      split_ifs with ha
      · simp [ha]
      · rw [gibbs_log_ratio E P π hsupp x a ha]
        ring
    _ = (∑ a, if π x a = 0 then 0
          else π x a * Real.log (π x a / E.reference x a)) -
        E.eta * ∑ a, π x a * linearReward P x a +
        Real.log (gibbsNormalizer E P x) := by
      rw [Finset.sum_add_distrib, Finset.sum_sub_distrib,
        ← Finset.mul_sum, ← Finset.sum_mul, hπ.2 x]
      ring

-- @node: gibbsPolicy_supported
lemma gibbsPolicy_supported (P : BanditLaw E) :
    SupportedOnReference E (gibbsPolicy E P) := by
  intro x a hg
  by_contra href
  apply hg
  simp [gibbsPolicy, href]

-- @node: policyKL_gibbs_reference
lemma policyKL_gibbs_reference (P : BanditLaw E) (x : 𝒳) :
    policyKL (gibbsPolicy E P) E.reference x =
      E.eta * ∑ a, gibbsPolicy E P x a * linearReward P x a -
        Real.log (gibbsNormalizer E P x) := by
  have h :=
    policyKL_gibbs_expansion E P (gibbsPolicy E P) (gibbsPolicy_isPolicy E P)
      (gibbsPolicy_supported E P) x
  have hself : policyKL (gibbsPolicy E P) (gibbsPolicy E P) x = 0 := by
    simp [policyKL]
  rw [hself] at h
  linarith

-- @node: regularizedWelfare_gibbs
lemma regularizedWelfare_gibbs (P : BanditLaw E) :
    regularizedWelfare E P (gibbsPolicy E P) =
      E.eta⁻¹ * ∑ x, contextMass P x *
        Real.log (gibbsNormalizer E P x) := by
  rw [regularizedWelfare]
  have heta_ne : E.eta ≠ 0 := ne_of_gt E.eta_pos
  calc
    (∑ x, contextMass P x *
        ∑ a, gibbsPolicy E P x a * linearReward P x a) -
        E.eta⁻¹ *
          ∑ x, contextMass P x *
            policyKL (gibbsPolicy E P) E.reference x =
      (∑ x, contextMass P x *
        ∑ a, gibbsPolicy E P x a * linearReward P x a) -
        E.eta⁻¹ *
          ∑ x, contextMass P x *
            (E.eta * ∑ a, gibbsPolicy E P x a * linearReward P x a -
              Real.log (gibbsNormalizer E P x)) := by
        congr 2
        apply Finset.sum_congr rfl
        intro x _
        rw [policyKL_gibbs_reference E P x]
    _ = E.eta⁻¹ * ∑ x, contextMass P x *
        Real.log (gibbsNormalizer E P x) := by
      field_simp
      conv_lhs => rhs; enter [2, x]; rw [mul_sub]
      rw [Finset.sum_sub_distrib]
      have hcancel :
          (∑ x, contextMass P x *
            ∑ a, gibbsPolicy E P x a * linearReward P x a) * E.eta =
          ∑ x, E.eta * contextMass P x *
            ∑ a, gibbsPolicy E P x a * linearReward P x a := by
        rw [Finset.sum_mul]
        apply Finset.sum_congr rfl
        intro x _
        ring
      rw [hcancel]
      ring
      have hone : (Nat.rawCast 1 : ℝ) = 1 := by
        unfold Nat.rawCast
        norm_num
      exact (congrArg
        (fun t : ℝ => (∑ x, contextMass P x *
          Real.log (gibbsNormalizer E P x)) * t) hone).trans (mul_one _)

-- @node: lem:gibbs-regret-identity
lemma gibbs_regret_identity
    (P : BanditLaw E) (C D : ℝ) (hshell : ExactShell E P C D)
    (π : Policy 𝒳 𝒜) (hπ : IsPolicy π) (hsupp : SupportedOnReference E π) :
    regularizedWelfare E P (gibbsPolicy E P) - regularizedWelfare E P π =
      E.eta⁻¹ * ∑ x, contextMass P x * policyKL π (gibbsPolicy E P) x := by
  rw [regularizedWelfare_gibbs E P, regularizedWelfare]
  have heta_ne : E.eta ≠ 0 := ne_of_gt E.eta_pos
  calc
    E.eta⁻¹ * ∑ x, contextMass P x *
          Real.log (gibbsNormalizer E P x) -
        ((∑ x, contextMass P x * ∑ a, π x a * linearReward P x a) -
          E.eta⁻¹ * ∑ x, contextMass P x * policyKL π E.reference x) =
      E.eta⁻¹ * ∑ x, contextMass P x *
        (policyKL π E.reference x -
          E.eta * ∑ a, π x a * linearReward P x a +
          Real.log (gibbsNormalizer E P x)) := by
      field_simp
      conv_rhs => enter [2, x]; rw [mul_add, mul_sub]
      rw [Finset.sum_add_distrib, Finset.sum_sub_distrib]
      rw [Finset.mul_sum]
      rw [show
        (∑ x, E.eta *
          (contextMass P x * ∑ a, π x a * linearReward P x a)) =
        ∑ x, contextMass P x *
          (E.eta * ∑ a, π x a * linearReward P x a) by
          apply Finset.sum_congr rfl
          intro x _
          ring]
      ring
    _ = E.eta⁻¹ * ∑ x, contextMass P x *
        policyKL π (gibbsPolicy E P) x := by
      congr 1
      apply Finset.sum_congr rfl
      intro x _
      rw [policyKL_gibbs_expansion E P π hπ hsupp x]

end CausalSmith.Stat.ReverseKLTwoCoverage
