/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Basic
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Coverage.FeatureDomination
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.Certificate
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.CertificateAlgebra
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.CertificateDefinitions
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.CertificateLaw
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.CertificateRayleigh
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.IndexRegion
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.IndexRegionConstruction
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.IndexRegionNecessity
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.IndexRegionNecessityAlgebra
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Feasibility.IndexRegionOffDiagonal
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.FrontierNonuniqueness
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Gibbs.RegretIdentity
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Gibbs.RegretIdentityCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Helpers.FastBranchInversion
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Learner.PredictionPolytope
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.Adapters
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.Arithmetic
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.Assembly
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.Entropy
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.LinearExactShell
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.LinearExactShellConditional
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.Projection
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.BoundedLinearLocalization.Zhao
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.Concentration
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.ConcentrationCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Localization.UniformGibbsSupport
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness.Construction
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness.Envelope
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness.Event
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness.Limits
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness.Risk
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitness.Shell
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.DimensionWitnessDefs
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.HardFamily
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.HardFamilyCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.Assouad
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.BernoulliLaw
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.Calibration
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.ConstructionCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.ConstructionShell
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.DecoderRisk
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.ExactShell
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.FeasibilityRealization
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.Minimax
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.PolicyBridge
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.RiskLower
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.Informative.SourceChi
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.InformativeShell
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Analysis
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Assouad
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Basis
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Blueprint
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Certificate
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.ConstructionCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.ConstructionLaw
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Coordinates
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.ExactShell
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.FamilyCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Geometry
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Inversion
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Kernel
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Minimax
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Risk
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.RiskBridge
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Source
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Terminal
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Tilt
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.SameShellLower.Weights
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.ZeroRisk
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.ZeroRisk.CommonPolicy
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.ZeroRisk.ConstructionAnchor
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.ZeroRisk.ConstructionCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Lower.ZeroRisk.Minimax
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.NoSlowBranch
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.CleanTemperature
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPlugin
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPluginAssembly
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPluginCore
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPluginDefs
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPluginExpectedRisk
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPluginInversion
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.ERMPluginLocalizedGap
import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Upper.Localized

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
