/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Basic
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Basic
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.CitedInterfaces
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.DecisionClass
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.EntropyChaining
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.PopulationCoefficient
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.RadialCover
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.ScoreL2
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.Separability
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.SeparableCover
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EmpiricalProcess.VCExpectedMaximal
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Estimator
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.EuclideanBallsVC
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.FiniteMaxAssembly
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.FiniteMaxDecision
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.FiniteMaxLowerBound
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.BernoulliKernel
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.CommonStatisticBernoulli
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Density
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Design
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Divergence
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Family
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareAnalytic
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareClassGeometry
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareGeometry
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareGram
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareGramCertificate
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedCancellation
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedCertificate
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedKL
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedNormalized
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedObservation
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedOutside
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSignedSuccess
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.HardSquareSlice
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.PotentialOutcomeLaw
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Profiles
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.Regression
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.ScoreLaw
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.Hypercube.SmoothEnvelope
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.LawClass
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.T3_A1A2PointIndexedConverse
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.T4_WinsorizedUpper
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.T5_MatchedFrontier
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Causal.WinsorizedScoreMaximal
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AnalyticMeasurability
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularCellMass
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularCoordinates
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularDesign
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularFullDisc
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularGrid
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularHolder
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularLaw
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularLocality
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularMeasure
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularPacking
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularPackingOnePointKL
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularPackingTheorem
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadial
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialAlgebra
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialAssembly
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialFibre
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialKL
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialOnePointKL
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialOutcome
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularRadialQuantitative
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.AngularScaledDelta
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.BumpHolder
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.BumpHolderScaling
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.ClassInclusion
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.CoordinateEnvelope
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.DirectProduct
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxCore
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxDepoisson
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxExperiment
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxLowerBound
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.FiniteMaxRisk
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.MaximalCoupling
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.OuterExpectation
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.Poissonization
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.Polar
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.Helpers.SquareBoundary
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.T1_SameClassLogConverse
import CausalSmith.Stat.STAT_BddUniformLogPenalty_Research.T2_PointIndexedLogConverse

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
