import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.Transforms
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.ComplexAnalysisLocal
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.Cumulant
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.CertifiedComplex
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.CertifiedTranscendental
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.ContourBank
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.EmpiricalTransform
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.EmpiricalTransformSeries
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.UniformDiskSeries
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.SpectralEstimator
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.SelectorSoundness
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.HardSubmodel
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.ClassRelations
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.JmsComparator
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.SineScore
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.LuxemburgMGF
import CausalSmith.Stat.STAT_SaPlmCumulantConverse_Research.Helpers.JensenBlaschke

/-!
# Shared helper barrel for the spectral-annihilation paper
-/
