/-
# Prediction-space learners

The construction is deliberately coordinate-free: selection happens among
prediction functions, never among coefficient representatives.
-/

import CausalSmith.Stat.STAT_ReverseklTwoCoverage_Research.Basic
import Causalean.Stat.Concentration.Covering.CoveringNumber
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse

set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false
set_option linter.unusedVariables false

namespace CausalSmith.Stat.ReverseKLTwoCoverage

open scoped BigOperators

variable {d n : ℕ} {𝒳 𝒜 : Type*}
  [Fintype 𝒳] [Fintype 𝒜] [DecidableEq 𝒳] [DecidableEq 𝒜]
  [LinearOrder 𝒳] [LinearOrder 𝒜]
  [MeasurableSpace 𝒳] [MeasurableSpace 𝒜]
  [MeasurableSingletonClass 𝒳] [MeasurableSingletonClass 𝒜]
  (E : CommonExperiment d 𝒳 𝒜)

abbrev Prediction := 𝒳 → 𝒜 → ℝ

/-- Bounded linear prediction polytope. -/
def predictionPolytope : Set (Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)) :=
  {f | (∀ x a, f x a ∈ Set.Icc (0 : ℝ) 1) ∧
    ∃ θ : Fin d → ℝ, ∀ x a, f x a = ∑ i, E.feature x a i * θ i}
  -- @realizes \mathcal F({bounded linear predictions in [0,1]^S})

/-- Empirical squared loss. -/
noncomputable def empiricalLoss (sample : LoggedSample n 𝒳 𝒜)
    (f : Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)) : ℝ :=
  (n : ℝ)⁻¹ * ∑ i, ((sample i).reward - f (sample i).context (sample i).action) ^ 2
  -- @realizes L_n(n⁻¹∑(Y_i-f(X_i,A_i))²)

/-- The fixed sequential total order on context-action coordinates: contexts
are compared first, and actions break ties between equal contexts. -/
def PredictionCoordinateEarlier (x' : 𝒳) (a' : 𝒜) (x : 𝒳) (a : 𝒜) : Prop :=
  x' < x ∨ (x' = x ∧ a' < a)

/-- Lexicographic comparison of prediction vectors in the fixed sequential
context-then-action order. -/
def PredictionLexLT (f g : Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)) : Prop :=
  ∃ x a,
    (∀ x' a', PredictionCoordinateEarlier x' a' x a → f x' a' = g x' a') ∧
    f x a < g x a

/-- Predicate characterizing the sequentially lexicographic ERM. -/
def IsLexicographicERM (sample : LoggedSample n 𝒳 𝒜)
    (f : Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)) : Prop :=
  f ∈ predictionPolytope E ∧
  (∀ g ∈ predictionPolytope E, empiricalLoss sample f ≤ empiricalLoss sample g) ∧
  ∀ g ∈ predictionPolytope E,
    empiricalLoss sample g = empiricalLoss sample f → ¬ PredictionLexLT g f

/-- Total noncomputable selection, using zero only in the logically unreachable
case in which the compact minimizer predicate has no witness. -/
noncomputable def selectedERM (sample : LoggedSample n 𝒳 𝒜) :
    Prediction (𝒳 := 𝒳) (𝒜 := 𝒜) := by
  classical
  exact if h : ∃ f, IsLexicographicERM E sample f then Classical.choose h else fun _ _ => 0
  -- @realizes \widehat f(sequentially lexicographic empirical-risk minimizer)

/-- Empirical logging seminorm squared. -/
noncomputable def empiricalSeminormSq (sample : LoggedSample n 𝒳 𝒜)
    (h : Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)) : ℝ :=
  (n : ℝ)⁻¹ * ∑ i, (h (sample i).context (sample i).action) ^ 2
  -- @realizes \|\cdot\|_n(empirical prediction seminorm)

/-- Prediction confidence polytope. -/
def confidencePolytope (c0 : ℝ) (sample : LoggedSample n 𝒳 𝒜) :
    Set (Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)) :=
  {f | f ∈ predictionPolytope E ∧
    empiricalSeminormSq sample (fun x a => f x a - selectedERM E sample x a) ≤
      c0 * ((d : ℝ) * Real.log (Real.exp 1 * n) + Real.log (2 * (n : ℝ) ^ 2)) / n}
  -- @realizes \mathcal Q_n(empirical ball around fhat)

/-- Coordinatewise lower envelope of the confidence polytope. -/
noncomputable def lowerEnvelope (c0 : ℝ) (sample : LoggedSample n 𝒳 𝒜) :
    Prediction (𝒳 := 𝒳) (𝒜 := 𝒜) :=
  fun x a => sInf {r : ℝ | ∃ f ∈ confidencePolytope E c0 sample, r = f x a}

/-- Gibbs policy generated by the coordinatewise lower envelope. -/
noncomputable def lowerEnvelopePolicy (c0 : ℝ) (sample : LoggedSample n 𝒳 𝒜) :
    Policy 𝒳 𝒜 :=
  fun x a =>
    E.reference x a * Real.exp (E.eta * lowerEnvelope E c0 sample x a) /
      ∑ b, E.reference x b * Real.exp (E.eta * lowerEnvelope E c0 sample x b)
  -- @realizes \widehat\pi(lower-envelope Gibbs learner; receives only D_n and 𝔈)

/-- Diagnostic pessimistic empirical welfare criterion. -/
noncomputable def diagnosticPessimisticWelfare (c0 : ℝ)
    (sample : LoggedSample n 𝒳 𝒜) (π : Policy 𝒳 𝒜)
    (_hπ : IsPolicy π ∧ PolicySupportedOn π E.reference) : ℝ :=
  sInf {j : ℝ | ∃ f ∈ confidencePolytope E c0 sample,
    j = (n : ℝ)⁻¹ * ∑ i, ∑ a, π (sample i).context a * f (sample i).context a -
      (E.eta * n)⁻¹ * ∑ i, policyKL π E.reference (sample i).context}
  -- @realizes \underline J_n(real-valued diagnostic restricted to
  -- reference-supported policies in Δ(𝒜)^𝒳)

/-- All components of the prediction-polytope learner. -/
structure PredictionPolytopeConstruction (n : ℕ) where
  functionClass : Set (Prediction (𝒳 := 𝒳) (𝒜 := 𝒜))
  loss : LoggedSample n 𝒳 𝒜 → Prediction (𝒳 := 𝒳) (𝒜 := 𝒜) → ℝ
  selected : LoggedSample n 𝒳 𝒜 → Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)
  seminormSq : LoggedSample n 𝒳 𝒜 → Prediction (𝒳 := 𝒳) (𝒜 := 𝒜) → ℝ
  confidence : LoggedSample n 𝒳 𝒜 → Set (Prediction (𝒳 := 𝒳) (𝒜 := 𝒜))
  lowerReward : LoggedSample n 𝒳 𝒜 → Prediction (𝒳 := 𝒳) (𝒜 := 𝒜)
  deployed : Learner n (𝒳 := 𝒳) (𝒜 := 𝒜)
  diagnostic : (sample : LoggedSample n 𝒳 𝒜) → (π : Policy 𝒳 𝒜) →
    IsPolicy π ∧ PolicySupportedOn π E.reference → ℝ

-- @node: def:prediction-polytope-learner
/-- Complete prediction-polytope learner at universal radius constant `c₀`. -/
noncomputable def predictionPolytopeLearner (c0 : ℝ) (_hc0 : 0 < c0) :
    PredictionPolytopeConstruction E n where
  functionClass := predictionPolytope E
  loss := empiricalLoss
  selected := selectedERM E
  seminormSq := empiricalSeminormSq
  confidence := confidencePolytope E c0
  lowerReward := lowerEnvelope E c0
  deployed := fun sample _ => lowerEnvelopePolicy E c0 sample
  diagnostic := diagnosticPessimisticWelfare E c0
  -- @realizes c_0(carrier ℝ; universal positive/sufficiently-large range in upper theorems)

/-- Finite-dimensional compact selection makes the concrete learner measurable. -/
lemma predictionPolytopeLearner_measurable
    (c0 : ℝ) (hc0 : 0 < c0) :
    IsMeasurableLearner E
      (predictionPolytopeLearner E c0 hc0 (n := n)).deployed := by
  sorry

/-- The lower-envelope Gibbs numerator vanishes exactly off reference
support, so every deployed row is reference supported. -/
lemma predictionPolytopeLearner_supported (c0 : ℝ) (hc0 : 0 < c0) :
    ∀ sample hs,
      PolicySupportedOn
        ((predictionPolytopeLearner E c0 hc0 (n := n)).deployed sample hs)
        E.reference := by
  intro sample hs x a href
  simp only [predictionPolytopeLearner, lowerEnvelopePolicy]
  rw [href]
  simp

-- @node: def:erm-gibbs-plugin-learner
/-- Gibbs plug-in learner generated by the selected ERM. -/
noncomputable def ermGibbsPluginLearner :
    Learner n (𝒳 := 𝒳) (𝒜 := 𝒜) :=
  fun sample _ x a =>
    E.reference x a * Real.exp (E.eta * selectedERM E sample x a) /
      ∑ b, E.reference x b * Real.exp (E.eta * selectedERM E sample x b)
  -- @realizes \widehat\pi_{\mathrm{ERM}}(Gibbs policy of fhat)

/-- The ERM Gibbs plug-in has exactly the public reference support. -/
lemma ermGibbsPluginLearner_supported :
    ∀ sample hs,
      PolicySupportedOn (ermGibbsPluginLearner (n := n) E sample hs) E.reference := by
  intro sample hs x a href
  simp only [ermGibbsPluginLearner]
  rw [href]
  simp

/-- Finite-dimensional ERM selection and the continuous Gibbs map make the
plug-in learner a member of the effective decision class. -/
lemma ermGibbsPluginLearner_measurable :
    IsMeasurableLearner E (ermGibbsPluginLearner (n := n) E) := by
  sorry

/-- `E'` is the invertible feature-coordinate reparameterization of `E`. -/
def IsFeatureReparameterization
    (E' : CommonExperiment d 𝒳 𝒜) (T : (Matrix (Fin d) (Fin d) ℝ)ˣ) : Prop :=
  (∀ x a, E'.feature x a = (T : Matrix (Fin d) (Fin d) ℝ).mulVec (E.feature x a)) ∧
  E'.reference = E.reference ∧ E'.eta = E.eta
  -- @realizes T(invertible GL_d(ℝ) feature reparameterization)

-- @node: lem:learner-invariance
lemma learner_invariance
    (E' : CommonExperiment d 𝒳 𝒜) (T : (Matrix (Fin d) (Fin d) ℝ)ˣ)
    (hT : IsFeatureReparameterization E E' T) (c0 : ℝ) :
    predictionPolytope E' = predictionPolytope E ∧
    selectedERM (n := n) E' = selectedERM (n := n) E ∧
    confidencePolytope (n := n) E' c0 = confidencePolytope (n := n) E c0 ∧
    (∀ sample π
      (hπ' : IsPolicy π ∧ PolicySupportedOn π E'.reference)
      (hπ : IsPolicy π ∧ PolicySupportedOn π E.reference),
      diagnosticPessimisticWelfare (n := n) E' c0 sample π hπ' =
        diagnosticPessimisticWelfare (n := n) E c0 sample π hπ) ∧
    lowerEnvelopePolicy (n := n) E' c0 = lowerEnvelopePolicy (n := n) E c0 := by
  rcases hT with ⟨hfeature, href, heta⟩
  have hinvfeature : ∀ x a,
      E.feature x a =
        (↑T⁻¹ : Matrix (Fin d) (Fin d) ℝ).mulVec (E'.feature x a) := by
    intro x a
    rw [hfeature]
    rw [Matrix.mulVec_mulVec, Units.inv_mul, Matrix.one_mulVec]
  have hpoly : predictionPolytope E' = predictionPolytope E := by
    ext f
    constructor
    · rintro ⟨hf, theta, htheta⟩
      refine ⟨hf, (↑T : Matrix (Fin d) (Fin d) ℝ).transpose.mulVec theta, ?_⟩
      intro x a
      rw [htheta x a, hfeature x a]
      simp only [Matrix.mulVec, dotProduct, Matrix.transpose_apply]
      simp_rw [Finset.sum_mul, Finset.mul_sum]
      rw [Finset.sum_comm]
      simp only [mul_comm, mul_left_comm]
    · rintro ⟨hf, theta, htheta⟩
      refine
        ⟨hf, (↑T⁻¹ : Matrix (Fin d) (Fin d) ℝ).transpose.mulVec theta, ?_⟩
      intro x a
      rw [htheta x a, hinvfeature x a]
      simp only [Matrix.mulVec, dotProduct, Matrix.transpose_apply]
      simp_rw [Finset.sum_mul, Finset.mul_sum]
      rw [Finset.sum_comm]
      simp only [mul_comm, mul_left_comm]
  have hselected : selectedERM (n := n) E' = selectedERM (n := n) E := by
    unfold selectedERM IsLexicographicERM
    rw [hpoly]
  have hconfidence :
      confidencePolytope (n := n) E' c0 =
        confidencePolytope (n := n) E c0 := by
    unfold confidencePolytope
    rw [hpoly, hselected]
  refine ⟨hpoly, hselected, hconfidence, ?_, ?_⟩
  · intro sample π hπ' hπ
    unfold diagnosticPessimisticWelfare
    rw [hconfidence, href, heta]
  · unfold lowerEnvelopePolicy lowerEnvelope
    rw [hconfidence, href, heta]

end CausalSmith.Stat.ReverseKLTwoCoverage
