/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Derived joint and observational kernels of a generalized SCM

Given a gSCM `M`, the joint kernel `jointKernel M : Kernel (FixedValues M) (RandomValues M)`
is the pushforward of the latent product measure `M.latentProduct` along the evaluation
map `M.evalMap` (see `Causal/Model/Evaluation.lean`), with the fixed-value argument `s`
threaded as the kernel parameter.  The observational kernel `obsKernel M` is then the
pushforward of `jointKernel M` onto the observed coordinates `V ⊆ V ∪ L`.

The construction uses `Kernel.compProd` of the constant kernel at `M.latentProduct`
and the deterministic kernel of `Function.uncurry M.evalMap`, followed by a
`Kernel.map Prod.snd`.  `obsCondKernel` is the jointly measurable
kernel-native conditional object built via Mathlib's `Kernel.condKernel`.

Do-calculus Rule 2 / Rule 3 kernel-level theorems (and their value-space
plumbing) have been factored out to:
  * `Causalean/Causal/Do/Rule2.lean` — Rule 2 + `fillZrW` helpers.
  * `Causalean/Causal/Do/Rule3.lean` — Rule 3 + compat bridge lemmas.

## References

* Basic Concepts.tex, Definition `def:scm-joint` (joint and observational kernels).
-/

import Causalean.SCM.Model.SCM
import Causalean.SCM.Model.Evaluation
import Causalean.SCM.Model.InterventionSet
import Mathlib.Probability.Kernel.Basic
import Mathlib.Probability.Kernel.Composition.MapComap
import Mathlib.Probability.Kernel.Composition.CompProd
import Mathlib.Probability.Kernel.CondDistrib

/-! # Kernels Generated by Structural Causal Models

This file constructs the joint kernel induced by a structural causal model from
its latent distribution and evaluation map, and then obtains the observational
kernel by projecting to observed coordinates. It also provides the conditional
kernels used to state kernel-level do-calculus rules.

Do-calculus Rule 2 and Rule 3 kernel statements and their value-space helpers
live in the dedicated do-calculus files rather than in this core kernel file.

## Main definitions and results

* `SCM.jointKernel` is the law of `SCM.evalMap` under the latent product,
  parameterized by fixed values.
* `SCM.randomToObserved` and `SCM.obsKernel` project the joint law to observed
  coordinates.
* `SCM.jointKernel_apply_eq` and `SCM.jointKernel_map_commute` expose
  pushforward forms used by downstream measure proofs.
* `SCM.obsCondPairKernel` and `SCM.obsCondKernel` construct jointly measurable
  conditional laws of target coordinates given conditioning coordinates.
* `SCM.obsCondKernel_ae_eq_condDistrib` connects the kernel-native conditional
  object to the measure-level conditional distribution.
-/

namespace Causalean

variable {N : Type*} [DecidableEq N] [Fintype N]
variable {Ω : N → Type*} [∀ n, MeasurableSpace (Ω n)]

namespace SCM

open scoped MeasureTheory ProbabilityTheory

/-- The joint kernel maps each fixed-value assignment to the law of the model evaluation under the latent product distribution.

    The joint kernel `jointKernel M : Kernel (FixedValues M) (RandomValues M)`.

    Sends each fixed assignment `s : FixedValues M` to the pushforward of the latent
    product measure `M.latentProduct` along the evaluation map `fun ℓ => M.evalMap s ℓ`.

    Implemented via `compProd` of the constant kernel at `M.latentProduct` and the
    deterministic kernel of `Function.uncurry M.evalMap`, then projected to the
    second factor: the joint `(ℓ, evalMap s ℓ)` distribution has `Prod.snd`
    pushforward equal to the pushforward of `latentProduct` by `evalMap s`. -/
noncomputable def jointKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.Kernel (FixedValues M) (RandomValues M) :=
  ((ProbabilityTheory.Kernel.const (FixedValues M) M.latentProduct) ⊗ₖ
    (ProbabilityTheory.Kernel.deterministic
      (Function.uncurry M.evalMap) M.evalMap_measurable)).map Prod.snd

/-- The observed projection keeps only the observed coordinates of a full random assignment. -/
def randomToObserved (M : Causalean.SCM N Ω) :
    RandomValues M → ObservedValues M :=
  fun ξ v => ξ ⟨v.val, Finset.mem_union_left _ v.property⟩

/-- The observed-coordinate projection is measurable. -/
theorem measurable_randomToObserved (M : Causalean.SCM N Ω) :
    Measurable (M.randomToObserved) := by
  refine measurable_pi_lambda _ ?_
  intro v
  exact measurable_pi_apply
    (a := (⟨v.val, Finset.mem_union_left _ v.property⟩ : {i // i ∈ M.randomVars}))

/-- At each fixed assignment, the joint kernel is the pushforward of the latent product through the evaluation map.

    Pointwise form of the joint kernel: at each fixed assignment `s`, the joint kernel
    is the pushforward of `M.latentProduct` along `fun ℓ => M.evalMap s ℓ`.

    This is the direct `Measure`-level form of `jointKernel`, collapsing the
    `compProd`-of-`const`-and-`deterministic` construction used in the definition. -/
lemma jointKernel_apply_eq (M : Causalean.SCM N Ω) (s : FixedValues M) :
    M.jointKernel s = M.latentProduct.map (fun ℓ => M.evalMap s ℓ) := by
  have hf : Measurable (fun ℓ : LatentValues M => M.evalMap s ℓ) := by
    have : M.evalMap s = fun ℓ => Function.uncurry M.evalMap (s, ℓ) := rfl
    rw [this]
    exact M.evalMap_measurable.comp (Measurable.prodMk measurable_const measurable_id)
  refine MeasureTheory.Measure.ext fun A hA => ?_
  unfold jointKernel
  rw [ProbabilityTheory.Kernel.map_apply _ measurable_snd,
      MeasureTheory.Measure.map_apply measurable_snd hA,
      ProbabilityTheory.Kernel.compProd_apply (measurable_snd hA),
      ProbabilityTheory.Kernel.const_apply,
      MeasureTheory.Measure.map_apply hf hA]
  -- LHS: ∫⁻ ℓ, (deterministic (uncurry evalMap)) (s, ℓ) (Prod.mk ℓ ⁻¹' (Prod.snd ⁻¹' A)) ∂latentProduct
  -- RHS: latentProduct ((fun ℓ => evalMap s ℓ) ⁻¹' A)
  simp only [ProbabilityTheory.Kernel.deterministic_apply, Function.uncurry_apply_pair]
  -- Simplify the preimage `Prod.mk ℓ ⁻¹' (Prod.snd ⁻¹' A) = A` (rfl on Set membership).
  have hset : ∀ ℓ : LatentValues M,
      (Prod.mk ℓ ⁻¹' (Prod.snd ⁻¹' A) : Set (RandomValues M)) = A := fun _ => rfl
  simp only [hset]
  -- Goal: ∫⁻ ℓ, Measure.dirac (M.evalMap s ℓ) A ∂latentProduct
  --     = latentProduct ((fun ℓ => evalMap s ℓ) ⁻¹' A)
  -- Bridge through indicator form.
  trans (∫⁻ ℓ, Set.indicator ((fun ℓ => M.evalMap s ℓ) ⁻¹' A) (fun _ => (1 : ENNReal)) ℓ
              ∂M.latentProduct)
  · apply MeasureTheory.lintegral_congr
    intro ℓ
    rw [MeasureTheory.Measure.dirac_apply' _ hA]
    simp only [Set.indicator, Set.mem_preimage, Pi.one_apply]
    rfl
  · exact MeasureTheory.lintegral_indicator_one (hf hA)

/-- The observational kernel maps each fixed-value assignment to the induced law of the observed nodes.

    The observational kernel `obsKernel M : Kernel (FixedValues M) (ObservedValues M)`.

    Defined by pushing `jointKernel M` through the observed-coordinate projection
    `randomToObserved : RandomValues M → ObservedValues M`. -/
noncomputable def obsKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.Kernel (FixedValues M) (ObservedValues M) :=
  (M.jointKernel).map M.randomToObserved

/-- The joint kernel is a Markov kernel. -/
instance instIsMarkovKernelJointKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.IsMarkovKernel M.jointKernel := by
  unfold jointKernel
  exact ProbabilityTheory.Kernel.IsMarkovKernel.map _ measurable_snd

/-- The observational kernel is a Markov kernel. -/
instance instIsMarkovKernelObsKernel (M : Causalean.SCM N Ω) :
    ProbabilityTheory.IsMarkovKernel M.obsKernel := by
  unfold obsKernel
  exact ProbabilityTheory.Kernel.IsMarkovKernel.map _ M.measurable_randomToObserved

/-- Each observational-kernel slice has total mass one. -/
theorem obsKernel_apply_univ (M : Causalean.SCM N Ω) (s : FixedValues M) :
    M.obsKernel s Set.univ = 1 := by
  exact MeasureTheory.measure_univ

/-- The observational kernel can be written as one pushforward that evaluates the model and then projects to observed coordinates.

    **Pushforward and projection commute.**  The observational kernel can be obtained
    either in two steps (first push the latent product along `evalMap`, then project
    onto observed coordinates), or in one step by folding the projection into the
    deterministic kernel.  This is purely `Kernel.map_comp_right`, exposed here so that
    downstream proofs can reach for the one-step form directly. -/
theorem jointKernel_map_commute (M : Causalean.SCM N Ω) :
    M.obsKernel =
      ((ProbabilityTheory.Kernel.const (FixedValues M) M.latentProduct) ⊗ₖ
        (ProbabilityTheory.Kernel.deterministic
          (Function.uncurry M.evalMap) M.evalMap_measurable)).map
        (M.randomToObserved ∘ Prod.snd) := by
  unfold obsKernel jointKernel
  exact (ProbabilityTheory.Kernel.map_comp_right _
    measurable_snd M.measurable_randomToObserved).symm

-- ============================================================
-- § `obsCondKernel` — jointly measurable conditional kernel
-- ============================================================

/-- The conditional-pair kernel pushes the observational law to conditioning coordinates paired with target coordinates. -/
noncomputable def obsCondPairKernel
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed) :
    ProbabilityTheory.Kernel (FixedValues M)
      (ValuesOn CC (swigΩ Ω) × ValuesOn Y (swigΩ Ω)) :=
  (M.obsKernel).map (fun ω =>
    (valuesProjection hCC ω, valuesProjection hY ω))

/-- The observational conditional kernel is a jointly measurable conditional law of target coordinates given conditioning coordinates.

    Jointly measurable conditional law of the `Y`-coordinates given the
    `CC`-coordinates under `M.obsKernel`. -/
noncomputable def obsCondKernel
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed)
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.obsKernel s)]
    [MeasurableSpace.CountableOrCountablyGenerated
      (FixedValues M) (ValuesOn CC (swigΩ Ω))] :
    ProbabilityTheory.Kernel
      (FixedValues M × ValuesOn CC (swigΩ Ω))
      (ValuesOn Y (swigΩ Ω)) :=
  letI : ProbabilityTheory.IsFiniteKernel (M.obsCondPairKernel Y CC hY hCC) := by
    letI : ProbabilityTheory.IsMarkovKernel (M.obsCondPairKernel Y CC hY hCC) := by
      unfold obsCondPairKernel
      exact ProbabilityTheory.Kernel.IsMarkovKernel.map _
        (Measurable.prodMk
          (measurable_valuesProjection hCC)
          (measurable_valuesProjection hY))
    infer_instance
  (M.obsCondPairKernel Y CC hY hCC).condKernel

/-- The observational conditional kernel agrees almost everywhere with the measure-level conditional distribution.

    **Bridge: `obsCondKernel` agrees with `condDistrib` a.e.**

    At a fixed `s : M.FixedValues`, the jointly measurable conditional kernel
    `M.obsCondKernel Y CC` evaluated at `(s, ·)` coincides
    `(M.obsKernel s).map π_CC`-a.e. with the measure-level `condDistrib π_Y π_CC
    (M.obsKernel s)`.  This is just the kernel-vs-measure disintegration
    uniqueness specialized to `M.obsCondPairKernel = M.obsKernel.map (π_CC, π_Y)`,
    whose `condKernel` is by definition `M.obsCondKernel`. -/
theorem obsCondKernel_ae_eq_condDistrib
    (M : Causalean.SCM N Ω) (Y CC : Finset (SWIGNode N))
    (hY : Y ⊆ M.observed) (hCC : CC ⊆ M.observed)
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.obsKernel s)]
    [MeasurableSpace.CountableOrCountablyGenerated
      (FixedValues M) (ValuesOn CC (swigΩ Ω))]
    (s : M.FixedValues) :
    (fun c => M.obsCondKernel Y CC hY hCC (s, c))
      =ᵐ[(M.obsKernel s).map (valuesProjection hCC)]
        ProbabilityTheory.condDistrib (valuesProjection hY)
          (valuesProjection hCC) (M.obsKernel s) := by
  letI : ProbabilityTheory.IsMarkovKernel (M.obsCondPairKernel Y CC hY hCC) := by
    unfold obsCondPairKernel
    exact ProbabilityTheory.Kernel.IsMarkovKernel.map _
      (Measurable.prodMk
        (measurable_valuesProjection hCC)
        (measurable_valuesProjection hY))
  -- `Kernel.condKernel_apply_eq_condKernel` gives a.e. equality with the
  -- measure-level `condKernel`; rewrite `Kernel.fst` of the pair kernel.
  have h := ProbabilityTheory.Kernel.condKernel_apply_eq_condKernel
    (M.obsCondPairKernel Y CC hY hCC) s
  -- `Kernel.fst (M.obsKernel.map (π_CC, π_Y)) s = (M.obsKernel s).map π_CC`.
  have hfst :
      ProbabilityTheory.Kernel.fst (M.obsCondPairKernel Y CC hY hCC) s
        = (M.obsKernel s).map (valuesProjection hCC) := by
    unfold obsCondPairKernel
    rw [ProbabilityTheory.Kernel.fst_map_prod _ (measurable_valuesProjection hY),
        ProbabilityTheory.Kernel.map_apply _ (measurable_valuesProjection hCC)]
  rw [hfst] at h
  -- `condDistrib π_Y π_CC μ = (μ.map (π_CC, π_Y)).condKernel = (obsCondPairKernel s).condKernel`.
  have hmap :
      (M.obsCondPairKernel Y CC hY hCC) s
        = MeasureTheory.Measure.map
            (fun ω => (valuesProjection hCC ω, valuesProjection hY ω))
            (M.obsKernel s) := by
    unfold obsCondPairKernel
    exact ProbabilityTheory.Kernel.map_apply M.obsKernel
      ((measurable_valuesProjection hCC).prodMk (measurable_valuesProjection hY)) s
  have hcd :
      ProbabilityTheory.condDistrib (valuesProjection hY)
          (valuesProjection hCC) (M.obsKernel s)
        = (M.obsCondPairKernel Y CC hY hCC s).condKernel := by
    rw [ProbabilityTheory.condDistrib]
    congr 1
    exact hmap.symm
  rw [hcd]
  exact h

end SCM

end Causalean
