/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Partially linear model under the backdoor PO framework (continuous treatment)

This file sets up the partially linear regression (PLR) model as a causal model
inside the potential-outcome framework, with a **real-valued (continuous)
treatment** `D ∈ ℝ`.  It parallels `POBackdoorSystem` (binary treatment) in
`PO/ID/Exact/ATE.lean`, swapping the treatment's value space `Bool → ℝ`.

* `POPartialLinearSystem` — the bare PO substrate: a real treatment node `D`, a
  real outcome node `Y`, a covariate variable `X`, plus the value-space equivs
  and the distinctness of the three nodes.  Derived: `YofD d` (the potential
  outcome `Y(d)`), the factual `D/Y/X`, and the σ-algebras `σ(X)`, `σ(X,D)`.
* `POPartialLinearModel` — adds the *homogeneous linear dose-response* structural
  restriction `Y(d) = b(X) + θ·d + U`, the standard backdoor assumption stated in
  conditional-mean form `E[U | σ(X,D)] = 0`, and consistency `Y = Y(D)`.
* `factualY_eq` — the observed-data form `Y = b(X) + θ·D + U`.
* `causal_homogeneity` — the causal reading `Y(d) − Y(d') = θ·(d − d')`.
-/

import Causalean.PO.Assumptions.ConsistencyLemmas
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.ConditionalExpectation

/-! # Partially Linear Model Setup

This file provides the potential-outcome substrate for the partially linear
model with a real-valued treatment. `POPartialLinearSystem` records the
treatment, outcome, and covariate nodes; packages them as `dVar`, `yVar`, and
`xVar`; defines potential outcomes `YofD`, factual maps, and the sigma-algebras
`sigmaX` and `sigmaXD`; and proves the measurability and inclusion lemmas used
by the identification proof.

`POPartialLinearModel` adds the homogeneous structural restriction
`Y(d) = b(X) + theta * d + U`, a conditional-mean backdoor assumption, and
consistency. Its two exported consequences are `factualY_eq`, the observed-data
regression form, and `causal_homogeneity`, the constant per-unit causal effect
identity. -/

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

/-- A continuous-treatment backdoor subsystem: a real-valued treatment node `D`, a
real outcome node `Y`, and a covariate variable `X` taking values in an
arbitrary measurable space.  This mirrors the binary backdoor subsystem but the
treatment now ranges over the real line, as required by the partially linear
model `Y = g(X) + θ·D + noise`. -/
structure POPartialLinearSystem (P : POSystem) (γ : Type*) [MeasurableSpace γ] where
  /-- The treatment node. -/
  D : P.V
  /-- The outcome node. -/
  Y : P.V
  /-- The covariate variable, valued in the covariate space. -/
  Xvar : POVar P γ
  /-- The treatment node's value space is the real line. -/
  hDreal : P.X D ≃ᵐ ℝ
  /-- The outcome node's value space is the real line. -/
  hYreal : P.X Y ≃ᵐ ℝ
  /-- Treatment and outcome are distinct nodes. -/
  hDY : D ≠ Y
  /-- Treatment and covariate are distinct nodes. -/
  hDX : D ≠ Xvar.v
  /-- Outcome and covariate are distinct nodes. -/
  hYX : Y ≠ Xvar.v

namespace POPartialLinearSystem

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POPartialLinearSystem P γ)

/-- The treatment regarded as a real-valued potential-outcome variable. -/
def dVar : POVar P ℝ := ⟨S.D, S.hDreal⟩
/-- The outcome regarded as a real-valued potential-outcome variable. -/
def yVar : POVar P ℝ := ⟨S.Y, S.hYreal⟩
/-- The covariate regarded as a potential-outcome variable. -/
def xVar : POVar P γ := S.Xvar

/-- The potential outcome under dose `d`: the value the outcome would take were
the treatment set to the real number `d`. -/
noncomputable def YofD (d : ℝ) : P.Ω → ℝ := S.yVar.cfUnder S.dVar d
/-- The factual (observed) treatment level of each unit. -/
noncomputable def factualD : P.Ω → ℝ := S.dVar.factual
/-- The factual (observed) outcome of each unit. -/
noncomputable def factualY : P.Ω → ℝ := S.yVar.factual
/-- The factual (observed) covariate of each unit. -/
noncomputable def factualX : P.Ω → γ := S.xVar.factual

/-- The potential outcome under a fixed dose is measurable. -/
lemma measurable_YofD (d : ℝ) : Measurable (S.YofD d) :=
  S.yVar.measurable_cfUnder S.dVar d
/-- The factual treatment level is measurable. -/
lemma measurable_factualD : Measurable S.factualD := S.dVar.measurable_factual
/-- The factual outcome is measurable. -/
lemma measurable_factualY : Measurable S.factualY := S.yVar.measurable_factual
/-- The factual covariate is measurable. -/
lemma measurable_factualX : Measurable S.factualX := S.xVar.measurable_factual

/-- The σ-algebra generated by the observed covariate. -/
noncomputable def sigmaX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualX inferInstance

/-- The covariate-generated sigma-algebra is a sub-sigma-algebra of the ambient space. -/
lemma sigmaX_le : S.sigmaX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_factualX.comap_le

/-- The joint observed covariate-and-treatment map `ω ↦ (X(ω), D(ω))`. -/
noncomputable def factualXD : P.Ω → γ × ℝ :=
  fun ω => (S.factualX ω, S.factualD ω)

/-- The joint observed covariate-and-treatment map is measurable. -/
lemma measurable_factualXD : Measurable S.factualXD :=
  S.measurable_factualX.prodMk S.measurable_factualD

/-- The σ-algebra generated by the observed covariate and treatment jointly. -/
noncomputable def sigmaXD : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualXD inferInstance

/-- The joint covariate-treatment sigma-algebra is a sub-sigma-algebra of the
ambient space. -/
lemma sigmaXD_le : S.sigmaXD ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_factualXD.comap_le

/-- The covariate σ-algebra is contained in the joint covariate-treatment
σ-algebra. -/
lemma sigmaX_le_sigmaXD : S.sigmaX ≤ S.sigmaXD := by
  have h : S.factualX = Prod.fst ∘ S.factualXD := rfl
  unfold sigmaX sigmaXD
  rw [h, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono measurable_fst.comap_le

end POPartialLinearSystem

/-- The partially linear model under the backdoor PO framework.  On top of the
PO substrate it records the structural decomposition of the potential outcome
into a covariate function, a constant per-unit treatment effect, and a unit
error; the standard backdoor (unconfoundedness) assumption in conditional-mean
form; and consistency.  Concretely: every unit's dose-response is the straight
line `Y(d) = b(X) + θ·d + U` with the same slope `θ` for everyone, the error has
zero conditional mean given the observed covariate and treatment, and the
observed outcome is the potential outcome at the realized treatment. -/
structure POPartialLinearModel (P : POSystem) (γ : Type*) [MeasurableSpace γ]
    extends POPartialLinearSystem P γ where
  /-- Consistency (SUTVA): the observed outcome equals the potential outcome of
  the realized treatment. -/
  consistency : P.Consistency
  /-- The covariate part `b(x)` of the structural dose-response (the nonparametric
  baseline `g(X)`). -/
  b : γ → ℝ
  /-- The covariate part is measurable. -/
  b_meas : Measurable b
  /-- The homogeneous (constant across units) per-unit treatment effect — the
  causal parameter the model is about. -/
  θ : ℝ
  /-- The structural error term. -/
  U : P.Ω → ℝ
  /-- The structural error is measurable. -/
  U_meas : Measurable U
  /-- Homogeneous linear dose-response: for almost every unit, the potential
  outcome is the straight line `b(X) + θ·d + U` in the dose `d`, simultaneously
  for all doses. -/
  structural : ∀ᵐ ω ∂P.μ, ∀ d : ℝ,
      toPOPartialLinearSystem.YofD d ω
        = b (toPOPartialLinearSystem.factualX ω) + θ * d + U ω
  /-- Backdoor unconfoundedness in conditional-mean form: the structural error
  has zero mean given the observed covariate and treatment.  This is the
  operative content of the standard backdoor assumption `U ⊥ D | σ(X)` together
  with `E[U | σ(X)] = 0`. -/
  backdoor :
    P.μ[U | toPOPartialLinearSystem.sigmaXD] =ᵐ[P.μ] 0

namespace POPartialLinearModel

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (M : POPartialLinearModel P γ)

/-- The observed-data form of the structural model: almost surely
`Y = b(X) + θ·D + U`.  Obtained from the homogeneous dose-response evaluated at
the realized treatment, using consistency `Y = Y(D)`. -/
lemma factualY_eq :
    M.factualY =ᵐ[P.μ]
      fun ω => M.b (M.factualX ω) + M.θ * M.factualD ω + M.U ω := by
  filter_upwards [M.structural] with ω hω
  have hcons :
      M.yVar.factual ω = M.yVar.cfUnder M.dVar (M.dVar.factual ω) ω :=
    POVar.factual_eq_cfUnder_self_selected M.consistency M.yVar M.dVar
      (Ne.symm M.hDY) ω
  have hstr := hω (M.factualD ω)
  simpa [POPartialLinearSystem.factualY, POPartialLinearSystem.YofD,
    POPartialLinearSystem.factualD, POPartialLinearSystem.factualX] using
    hcons.trans hstr

/-- The causal reading of `θ`: almost surely, the difference of two potential
outcomes is the slope `θ` times the difference of the doses.  In particular `θ`
is the constant per-unit causal effect of the treatment. -/
lemma causal_homogeneity :
    ∀ᵐ ω ∂P.μ, ∀ d d' : ℝ,
      M.YofD d ω - M.YofD d' ω = M.θ * (d - d') := by
  filter_upwards [M.structural] with ω hω
  intro d d'
  rw [hω d, hω d']
  ring

end POPartialLinearModel

end PO
end Causalean
