/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic.Cumulants
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic.Swaps
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Basic.World
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Handles
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AdmissibleSwaps
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AffineSpaceDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AffineSubspaceDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.AlgebraicSetChains
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarDefs
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernel
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelAux
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelDiff
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelIdentity
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarKernelRank
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarQD
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ApolarRankBridge
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ArrowPolynomialGeometry
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.BandDimensionTransfer
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.BandParameterCoordinates
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.BandWeightKernelDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CAD.CADInterface
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisImageGeometry
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisPrincipalEquations
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisReversal
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CommonAxisTwin
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ConfluentVandermonde
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CoordinateReversalGeometry
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.DirectLatentSwaps
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.CAD.EffectiveRationalGroebnerCADInterface
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.EmptyFiber
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalCodimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalCommonAxisJacobianTop
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalCommonAxisOrdinary
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalGeometryBasic
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalHeightReduction
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalImageDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalImageDimensionUpper
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalIncidence
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalJacobianCoordinates
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ExceptionalJacobianMinor
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiberDimensionDefs
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiberSlopeComponents
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiniteCodimensionTransfer
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FiniteCumBand
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FixedLoadingFiberDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.FullFiberSlopeRecovery
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.GenericFiberDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.GenericSlopes
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.IrreducibleFiniteRange
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LoadingWeightKernelDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderApolarKernel
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderApolarRank
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderApolarSeparation
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.LowerOrderEmptyFiber
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.MomentGate
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.PinSubst
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.PolynomialRetractDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.PrincipalHeightOne
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ReverseApolarKernel
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.SlopeUniqueness
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.Varieties
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.WeightSynthesisDimension
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Helpers.ZariskiLocus
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.Selector
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TAdmissibleSwaps
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TApolar
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TAtlas
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TExceptionalLocus
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TGenericSeparation
import CausalSmith.ExactID.EID_LingamDirectionMinOrderV1_Research.TInfoOrder

/-! # Run barrel (auto-generated)

Aggregates every module of this causalsmith run so the whole run is ONE buildable target
(`lake build <this module>`). Research modules are not reachable from the top-level
`CausalSmith.lean` barrel, so the default lake target skips them and reports green on stale
oleans. Rewritten from the run's module set on every F-stage entry — do not hand-edit. -/
