/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.SCM.Model.SCM
import Causalean.Mathlib.CondIndep.CondExp
import Mathlib.Probability.Independence.Conditional

/-! # Conditional Independence for Finite-Product Projections

This file provides the finite-product projection infrastructure used by SCM
conditional-independence proofs. It proves compositional and sigma-algebra facts
for `valuesProjection`, defines `valuesUnionMk` for assembling two coordinate
blocks into their union, and proves the specialized weak-union and contraction
rules `condIndep_valuesProjection_weak_union` and
`condIndep_valuesProjection_contraction`. These results specialize general
conditional-expectation semi-graphoid identities to the value-block projections
used by structural causal models. -/

namespace Causalean

open scoped MeasureTheory ProbabilityTheory

universe uM uΩ

/-- Composition identity for `valuesProjection`: restricting to `K ⊆ J ⊆ I`
    in one step equals composing the two restrictions. -/
theorem valuesProjection_comp {M : Type*} [DecidableEq M] [Fintype M]
    {I J K : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hKJ : K ⊆ J) (hJI : J ⊆ I) (hKI : K ⊆ I) :
    valuesProjection (Ω := Ω') hKI =
      valuesProjection hKJ ∘ valuesProjection hJI := by
  funext ξ ⟨k, hk⟩
  simp only [Function.comp_apply, valuesProjection]

/-- The comap σ-algebra is monotone in the projected set:
    if `A ⊆ B ⊆ I`, then `σ(π_A) ≤ σ(π_B)` on `ValuesOn I`. -/
theorem comap_valuesProjection_mono {M : Type*} [DecidableEq M] [Fintype M]
    {I A B : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hAB : A ⊆ B) (hBI : B ⊆ I) (hAI : A ⊆ I) :
    MeasurableSpace.comap (valuesProjection (Ω := Ω') hAI) inferInstance ≤
      MeasurableSpace.comap (valuesProjection (Ω := Ω') hBI) inferInstance := by
  have hcomp := valuesProjection_comp (Ω' := Ω') hAB hBI hAI
  rw [hcomp]
  intro s ⟨t, ht, hts⟩
  exact ⟨valuesProjection hAB ⁻¹' t, measurable_valuesProjection hAB ht, hts⟩

/-- The projection to `A ∪ B` is measurable for the supremum of the separate
    projection σ-algebras. -/
theorem measurable_valuesProjection_union_sup
    {M : Type*} [DecidableEq M] [Fintype M]
    {I A B : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hA : A ⊆ I) (hB : B ⊆ I) (hAB : A ∪ B ⊆ I) :
    @Measurable (ValuesOn I Ω') (ValuesOn (A ∪ B) Ω')
      (MeasurableSpace.comap (valuesProjection (Ω := Ω') hA) inferInstance ⊔
        MeasurableSpace.comap (valuesProjection (Ω := Ω') hB) inferInstance)
      inferInstance
      (valuesProjection (Ω := Ω') hAB) := by
  change @Measurable (ValuesOn I Ω') (∀ i : {i // i ∈ A ∪ B}, Ω' i.val)
    (MeasurableSpace.comap (valuesProjection (Ω := Ω') hA) inferInstance ⊔
      MeasurableSpace.comap (valuesProjection (Ω := Ω') hB) inferInstance)
    inferInstance
    (fun ξ : ValuesOn I Ω' => fun i : {i // i ∈ A ∪ B} =>
      ξ ⟨i.val, hAB i.property⟩)
  refine (@measurable_pi_iff (ValuesOn I Ω') {i // i ∈ A ∪ B}
    (fun i : {i // i ∈ A ∪ B} => Ω' i.val)
    (MeasurableSpace.comap (valuesProjection (Ω := Ω') hA) inferInstance ⊔
      MeasurableSpace.comap (valuesProjection (Ω := Ω') hB) inferInstance)
    inferInstance
    (fun ξ : ValuesOn I Ω' => fun i : {i // i ∈ A ∪ B} =>
      ξ ⟨i.val, hAB i.property⟩)).2 ?_
  intro ⟨i, hiAB⟩
  by_cases hiA : i ∈ A
  · have hπA :
        @Measurable (ValuesOn I Ω') (ValuesOn A Ω')
          (MeasurableSpace.comap (valuesProjection (Ω := Ω') hA) inferInstance ⊔
            MeasurableSpace.comap (valuesProjection (Ω := Ω') hB) inferInstance)
          inferInstance
          (valuesProjection (Ω := Ω') hA) :=
      Measurable.of_comap_le le_sup_left
    simpa [valuesProjection] using
      (measurable_pi_apply (⟨i, hiA⟩ : {j // j ∈ A})).comp hπA
  · have hiB : i ∈ B := (Finset.mem_union.mp hiAB).resolve_left hiA
    have hπB :
        @Measurable (ValuesOn I Ω') (ValuesOn B Ω')
          (MeasurableSpace.comap (valuesProjection (Ω := Ω') hA) inferInstance ⊔
            MeasurableSpace.comap (valuesProjection (Ω := Ω') hB) inferInstance)
          inferInstance
          (valuesProjection (Ω := Ω') hB) :=
      Measurable.of_comap_le le_sup_right
    simpa [valuesProjection] using
      (measurable_pi_apply (⟨i, hiB⟩ : {j // j ∈ B})).comp hπB

/-- The σ-algebra generated by the projection to `A ∪ B` is the supremum of
    the σ-algebras generated by the separate projections to `A` and to `B`. -/
theorem comap_valuesProjection_union_eq_sup
    {M : Type*} [DecidableEq M] [Fintype M]
    {I A B : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hA : A ⊆ I) (hB : B ⊆ I) (hAB : A ∪ B ⊆ I) :
    MeasurableSpace.comap (valuesProjection (Ω := Ω') hAB) inferInstance =
      MeasurableSpace.comap (valuesProjection (Ω := Ω') hA) inferInstance ⊔
        MeasurableSpace.comap (valuesProjection (Ω := Ω') hB) inferInstance := by
  apply le_antisymm
  · exact Measurable.comap_le (measurable_valuesProjection_union_sup (Ω' := Ω') hA hB hAB)
  · exact sup_le
      (comap_valuesProjection_mono (Ω' := Ω') Finset.subset_union_left hAB hA)
      (comap_valuesProjection_mono (Ω' := Ω') Finset.subset_union_right hAB hB)

-- `valuesUnionMk` and `measurable_valuesUnionMk` are the generic value-space
-- union-injection; they now live in
-- `Causalean/Mathlib/MeasureTheory/FinsetValues.lean` (namespace `Causalean`),
-- shared with the SWIG-specialized call sites in `Rule2Kernel/Helpers.lean`.

/-- Projecting to `A` and `B` and then assembling the union block recovers the
    direct projection to `A ∪ B`. -/
theorem valuesUnionMk_projection_comp
    {M : Type*} [DecidableEq M] [Fintype M]
    {I A B : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hA : A ⊆ I) (hB : B ⊆ I) (hAB : A ∪ B ⊆ I) :
    (fun ξ : ValuesOn I Ω' =>
      valuesUnionMk (Ω := Ω') (valuesProjection hA ξ) (valuesProjection hB ξ))
      = valuesProjection hAB := by
  funext ξ ⟨i, hiAB⟩
  by_cases hiA : i ∈ A
  · simp [valuesUnionMk, valuesProjection, hiA]
  · simp [valuesUnionMk, valuesProjection, hiA]

/-- Weak union for `CondIndepFun` specialized to finite-product coordinate projections.

Given `X ⊥ (Y ∪ W) | Z`, infer `X ⊥ Y | (Z ∪ W)`. -/
theorem condIndep_valuesProjection_weak_union
    {M : Type uM} [DecidableEq M] [Fintype M]
    {I X Y W Z : Finset M}
    {Ω : M → Type uΩ} [∀ n, MeasurableSpace (Ω n)]
    [StandardBorelSpace (ValuesOn I Ω)]
    (hX : X ⊆ I) (hYW : (Y ∪ W) ⊆ I) (hY : Y ⊆ I)
    (hZ : Z ⊆ I) (hZW : (Z ∪ W) ⊆ I)
    {μ : MeasureTheory.Measure (ValuesOn I Ω)} [MeasureTheory.IsFiniteMeasure μ]
    (h :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hYW)
        μ) :
    ProbabilityTheory.CondIndepFun
      (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZW) inferInstance)
      (comap_valuesProjection_le (Ω' := Ω) hZW)
      (valuesProjection (Ω := Ω) hX)
      (valuesProjection (Ω := Ω) hY)
      μ := by
  have hW : W ⊆ I := fun w hw => hZW (Finset.mem_union_right Z hw)
  have hpair_meas :
      Measurable
        (fun ξ : ValuesOn (Y ∪ W) Ω =>
          (valuesProjection (Ω := Ω) Finset.subset_union_left ξ,
           valuesProjection (Ω := Ω) Finset.subset_union_right ξ)) :=
    (measurable_valuesProjection (Ω' := Ω) Finset.subset_union_left).prod
      (measurable_valuesProjection (Ω' := Ω) Finset.subset_union_right)
  have hpair :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (fun ξ => (valuesProjection (Ω := Ω) hY ξ,
          valuesProjection (Ω := Ω) hW ξ))
        μ := by
    simpa [Function.comp_def, valuesProjection] using h.comp measurable_id hpair_meas
  have hweak :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance ⊔
          MeasurableSpace.comap (valuesProjection (Ω := Ω) hW) inferInstance)
        (sup_le (comap_valuesProjection_le (Ω' := Ω) hZ)
          (comap_valuesProjection_le (Ω' := Ω) hW))
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hY)
        μ :=
    condIndepFun_weak_union_of_prodMk
      (m := MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
      (mΩ := inferInstance)
      (μ := μ)
      (comap_valuesProjection_le (Ω' := Ω) hZ)
      (W := valuesProjection (Ω := Ω) hX)
      (V := valuesProjection (Ω := Ω) hY)
      (A := valuesProjection (Ω := Ω) hW)
      (measurable_valuesProjection (Ω' := Ω) hX)
      (measurable_valuesProjection (Ω' := Ω) hY)
      (measurable_valuesProjection (Ω' := Ω) hW)
      hpair
  have hσ :
      MeasurableSpace.comap (valuesProjection (Ω := Ω) hZW) inferInstance =
        MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance ⊔
          MeasurableSpace.comap (valuesProjection (Ω := Ω) hW) inferInstance :=
    comap_valuesProjection_union_eq_sup (Ω' := Ω) hZ hW hZW
  simpa [hσ] using hweak

/-- Contraction for `CondIndepFun` specialized to finite-product coordinate projections.

If `X ⊥ Y | (Z ∪ W)` and `X ⊥ W | Z`, then `X ⊥ (Y ∪ W) | Z`. -/
theorem condIndep_valuesProjection_contraction
    {M : Type uM} [DecidableEq M] [Fintype M]
    {I X Y W Z : Finset M}
    {Ω : M → Type uΩ} [∀ n, MeasurableSpace (Ω n)]
    [StandardBorelSpace (ValuesOn I Ω)]
    (hX : X ⊆ I) (hY : Y ⊆ I) (hW : W ⊆ I)
    (hZ : Z ⊆ I) (hYW : (Y ∪ W) ⊆ I) (hZW : (Z ∪ W) ⊆ I)
    {μ : MeasureTheory.Measure (ValuesOn I Ω)} [MeasureTheory.IsFiniteMeasure μ]
    (h1 :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZW) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZW)
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hY)
        μ)
    (h2 :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hW)
        μ) :
    ProbabilityTheory.CondIndepFun
      (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
      (comap_valuesProjection_le (Ω' := Ω) hZ)
      (valuesProjection (Ω := Ω) hX)
      (valuesProjection (Ω := Ω) hYW)
      μ := by
  have hσ :
      MeasurableSpace.comap (valuesProjection (Ω := Ω) hZW) inferInstance =
        MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance ⊔
          MeasurableSpace.comap (valuesProjection (Ω := Ω) hW) inferInstance :=
    comap_valuesProjection_union_eq_sup (Ω' := Ω) hZ hW hZW
  have h1' :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance ⊔
          MeasurableSpace.comap (valuesProjection (Ω := Ω) hW) inferInstance)
        (sup_le (comap_valuesProjection_le (Ω' := Ω) hZ)
          (comap_valuesProjection_le (Ω' := Ω) hW))
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hY)
        μ := by
    simpa [hσ] using h1
  have hpair :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (fun ξ : ValuesOn I Ω =>
          (valuesProjection (Ω := Ω) hY ξ, valuesProjection (Ω := Ω) hW ξ))
        μ :=
    condIndepFun_contraction_of_prodMk
      (m := MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
      (mΩ := inferInstance)
      (μ := μ)
      (comap_valuesProjection_le (Ω' := Ω) hZ)
      (measurable_valuesProjection (Ω' := Ω) hX)
      (measurable_valuesProjection (Ω' := Ω) hY)
      (measurable_valuesProjection (Ω' := Ω) hW)
      h1' h2
  have hassembled :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (fun ξ : ValuesOn I Ω =>
          valuesUnionMk (Ω := Ω) (valuesProjection (Ω := Ω) hY ξ)
            (valuesProjection (Ω := Ω) hW ξ))
        μ :=
    hpair.comp measurable_id (measurable_valuesUnionMk (Ω := Ω))
  simpa [Function.comp_def, valuesUnionMk_projection_comp (Ω' := Ω) hY hW hYW]
    using hassembled

end Causalean
