import Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension.Definitions
import Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension.AffineSpaceDimension

/-!
# Coordinate rings and chain dimension

This module identifies the ideal of a polynomial image closure with the kernel
of substitution and proves that the existing irreducible-chain dimension is
exactly the Krull dimension of the affine coordinate ring.
-/

namespace Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension

open Order
noncomputable section

/-- A target polynomial relation holds throughout a polynomial image closure
exactly when substituting the parameterization's coordinate polynomials makes
the relation identically zero. -/
theorem polynomialImageClosure_vanishingIdeal {ι κ : Type*} [Finite ι]
    (f : κ → MvPolynomial ι ℂ) :
    MvPolynomial.vanishingIdeal ℂ (polynomialImageClosure f) =
      RingHom.ker (polynomialPullback f) := by
  -- First replace the closure by the original range: a polynomial vanishes on
  -- a set iff it vanishes on the zero locus of that set's vanishing ideal.
  -- Membership in the range ideal is then `eval_polynomialPullback`; the
  -- reverse implication uses `MvPolynomial.funext` in the finite source.
  ext P
  constructor
  · intro hP
    change polynomialPullback f P = 0
    apply MvPolynomial.funext
    intro x
    rw [eval_polynomialPullback]
    exact hP _ (affineZariskiClosure_extensive _ ⟨x, rfl⟩)
  · intro hP
    change polynomialPullback f P = 0 at hP
    intro y hy
    change y ∈ MvPolynomial.zeroLocus ℂ
      (MvPolynomial.vanishingIdeal ℂ (Set.range (polynomialCoordinateMap f))) at hy
    exact hy P (by
      intro z hz
      obtain ⟨x, rfl⟩ := hz
      change MvPolynomial.eval (polynomialCoordinateMap f x) P = 0
      rw [← eval_polynomialPullback, hP]
      exact map_zero _)

/-- The coordinate ring of a polynomial image closure is canonically the same
complex algebra as the source-polynomial subalgebra generated by the image
coordinates. -/
noncomputable def polynomialImageClosure_coordinateRing {ι κ : Type*} [Finite ι]
    (f : κ → MvPolynomial ι ℂ) :
    (MvPolynomial κ ℂ ⧸ MvPolynomial.vanishingIdeal ℂ (polynomialImageClosure f))
      ≃ₐ[ℂ] polynomialCoordinateSubalgebra f := by
  rw [polynomialImageClosure_vanishingIdeal f]
  exact Ideal.quotientKerEquivRange (polynomialPullback f)

/-- For a nonempty finite-dimensional complex algebraic set, its geometric
dimension measured by irreducible chains equals the Krull dimension of its
coordinate ring. -/
theorem affineZariskiDimension_iff_coordinateRingKrullDim
    {ι : Type*} [Finite ι] {d : ℕ} {Z : Set (ι → ℂ)}
    (hclosed : affineZariskiClosure Z = Z) (hne : Z.Nonempty) :
    HasAffineZariskiDimension d Z ↔
      ringKrullDim
        (MvPolynomial ι ℂ ⧸ MvPolynomial.vanishingIdeal ℂ Z) = d := by
  -- Use `Ideal.primeSpectrumQuotientOrderIsoZeroLocus`.  Quotient primes are
  -- precisely primes containing `vanishingIdeal ℂ Z`; Nullstellensatz turns
  -- these into nonempty irreducible closed subsets of `Z`.  Strict chains are
  -- transported in both directions, reversing their indices with `Fin.rev`.
  rw [ringKrullDim_quotient]
  constructor
  · rintro ⟨⟨chain, hmono, hirr, hsub⟩, hno⟩
    apply le_antisymm
    · by_contra hlt
      have hle : (d + 1 : WithBot ℕ∞) ≤
          Order.krullDim (PrimeSpectrum.zeroLocus
            (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ))) := by
        exact WithBot.add_one_le_iff.mpr (lt_of_not_ge hlt)
      obtain ⟨series, hseries⟩ := Order.le_krullDim_iff.mp hle
      let castIndex : Fin (d + 2) → Fin (series.length + 1) :=
        Fin.cast (congrArg (· + 1) hseries.symm)
      apply hno
      let longChain : Fin (d + 2) → Set (ι → ℂ) := fun i =>
        MvPolynomial.zeroLocus ℂ ((series (castIndex i.rev)).1).asIdeal
      refine ⟨longChain, ?_, ?_, ?_⟩
      · intro i j hij
        have hrev : j.rev < i.rev := by simpa using hij
        have hcast : castIndex j.rev < castIndex i.rev := by
          simpa [castIndex] using hrev
        have hp : series (castIndex j.rev) < series (castIndex i.rev) :=
          series.strictMono hcast
        exact zeroLocus_strict_anti hp
      · intro i
        exact irreducible_zeroLocus_of_prime ((series (castIndex i.rev)).1).asIdeal
      · intro i
        rw [affineZariskiClosure_eq_zeroLocus hclosed]
        exact MvPolynomial.zeroLocus_anti_mono (series (castIndex i.rev)).2
    · have hle : (d : WithBot ℕ∞) ≤
          Order.krullDim (PrimeSpectrum.zeroLocus
            (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ))) := by
        let primes : Fin (d + 1) →
            PrimeSpectrum.zeroLocus
              (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ)) :=
          fun i => ⟨⟨MvPolynomial.vanishingIdeal ℂ (chain i.rev),
            (irreducibleAffineClosed_iff_isPrime
              (hirr i.rev).1 (hirr i.rev).2.1).mp (hirr i.rev)⟩,
            MvPolynomial.vanishingIdeal_anti_mono (hsub i.rev)⟩
        have hprimes : StrictMono primes := by
          intro i j hij
          have hrev : j.rev < i.rev := by simpa using hij
          exact vanishingIdeal_strict_anti (hirr j.rev).1 (hirr i.rev).1
            (hmono hrev)
        let witness : LTSeries (PrimeSpectrum.zeroLocus
            (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ))) :=
          LTSeries.mk d primes hprimes
        simpa [witness] using witness.length_le_krullDim
      exact hle
  · intro hdim
    constructor
    · have hle : (d : WithBot ℕ∞) ≤
          Order.krullDim (PrimeSpectrum.zeroLocus
            (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ))) := by
        exact hdim.ge
      obtain ⟨series, hseries⟩ := Order.le_krullDim_iff.mp hle
      let castIndex : Fin (d + 1) → Fin (series.length + 1) :=
        Fin.cast (congrArg (· + 1) hseries.symm)
      let chain : Fin (d + 1) → Set (ι → ℂ) := fun i =>
        MvPolynomial.zeroLocus ℂ ((series (castIndex i.rev)).1).asIdeal
      refine ⟨chain, ?_, ?_, ?_⟩
      · intro i j hij
        have hrev : j.rev < i.rev := by simpa using hij
        have hcast : castIndex j.rev < castIndex i.rev := by
          simpa [castIndex] using hrev
        have hp : series (castIndex j.rev) < series (castIndex i.rev) :=
          series.strictMono hcast
        exact zeroLocus_strict_anti hp
      · intro i
        exact irreducible_zeroLocus_of_prime ((series (castIndex i.rev)).1).asIdeal
      · intro i
        rw [affineZariskiClosure_eq_zeroLocus hclosed]
        exact MvPolynomial.zeroLocus_anti_mono (series (castIndex i.rev)).2
    · rintro ⟨chain, hmono, hirr, hsub⟩
      let primes : Fin (d + 2) →
          PrimeSpectrum.zeroLocus
            (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ)) :=
        fun i => ⟨⟨MvPolynomial.vanishingIdeal ℂ (chain i.rev),
          (irreducibleAffineClosed_iff_isPrime
            (hirr i.rev).1 (hirr i.rev).2.1).mp (hirr i.rev)⟩,
          MvPolynomial.vanishingIdeal_anti_mono (hsub i.rev)⟩
      have hprimes : StrictMono primes := by
        intro i j hij
        have hrev : j.rev < i.rev := by simpa using hij
        exact vanishingIdeal_strict_anti (hirr j.rev).1 (hirr i.rev).1
          (hmono hrev)
      let tooLong : LTSeries (PrimeSpectrum.zeroLocus
          (↑(MvPolynomial.vanishingIdeal ℂ Z) : Set (MvPolynomial ι ℂ))) :=
        LTSeries.mk (d + 1) primes hprimes
      have hbound := tooLong.length_le_krullDim
      rw [show tooLong.length = d + 1 by rfl] at hbound
      have htop : (d + 1 : WithTop ℕ) ≤ (d : WithTop ℕ) :=
        WithBot.coe_le_coe.mp (hbound.trans_eq hdim)
      have hnat : d + 1 ≤ d := WithTop.coe_le_coe.mp htop
      exact (Nat.not_succ_le_self d) hnat

end

end Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension
