/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.PO.ID.Partial.Sensitivity.MSM.Setup

/-! # Marginal Sensitivity Model (MSM) for the control mean `E[Y(0)]`

This file mirrors `Setup.lean` for the **control** arm. The treated MSM bounds
`E[Y(1)]` by inverse-probability weighting the indicator `1_{D=1}` against the
complete treated propensity `P[D=1 | σ(X, Y(1))]`; here we bound `E[Y(0)]` by
weighting `1_{D=0}` against the complete control propensity
`P[D=0 | σ(X, Y(0))]`, with the discrepancy from the observed
`P[D=0 | σ(X)] = propScore false` controlled by the same odds-ratio budget `Λ ≥ 1`.

Every definition and theorem is the `D=0` reflection of `Setup.lean`:
`sigmaXY1 → sigmaXY0`, `completeProp → completeProp0`, `candMean → candMean0`,
`Y1mean → Y0mean`, `MSMSet → MSMSet0`, etc. The odds-ratio object `OR` and the
structure-level pieces (`propScore`, `YofD`, consistency) are shared from `Setup.lean`
/ `ATE.lean`. This is the cheap symmetric extension that feeds the ATE interval
(`ATE.lean`). -/

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

namespace POBackdoorSystem

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POBackdoorSystem P γ)

/-- σ-algebra generated by BOTH the factual covariate `X` and the *control* potential
outcome `Y(0)`. Conditioning on this richer information set defines the complete
control propensity; it always refines `σ(X)`. -/
noncomputable def sigmaXY0 : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualX inferInstance
    ⊔ MeasurableSpace.comap (S.YofD false) inferInstance

/-- The joint σ-algebra `σ(X, Y(0))` is coarser than the ambient σ-algebra on `Ω`. -/
lemma sigmaXY0_le : S.sigmaXY0 ≤ (inferInstance : MeasurableSpace P.Ω) := by
  refine sup_le ?_ ?_
  · exact S.measurable_factualX.comap_le
  · exact (S.measurable_YofD false).comap_le

/-- The **complete control propensity** `P[D=0 | σ(X, Y(0))]`: the conditional
probability of *being untreated* given covariates and the control potential outcome.
Under unconfoundedness it collapses (a.e.) to `P[D=0 | σ(X)] = propScore false`. -/
noncomputable def completeProp0 : P.Ω → ℝ :=
  P.μ[S.dVar.indicator false | S.sigmaXY0]

/-- The candidate IPW mean `E[(1−A) · Y / ẽ]` for a candidate complete control
propensity `ẽ`, where `1−A = 1_{D=0}` is the control indicator and `Y` the factual
outcome. Evaluated at the true complete control propensity this returns `E[Y(0)]`. -/
noncomputable def candMean0 (etilde : P.Ω → ℝ) : ℝ :=
  ∫ ω, S.dVar.indicator false ω * S.factualY ω / etilde ω ∂P.μ

/-- The estimand `μ₀ = E[Y(0)]`, the mean of the control potential outcome. -/
noncomputable def Y0mean : ℝ := ∫ ω, S.YofD false ω ∂P.μ

/-- The **control MSM ambiguity set** at sensitivity level `Λ`: candidate complete
control propensities `ẽ` that are a.e. in `(0,1)` and whose odds ratio against the
observed control propensity `P[D=0 | σ(X)] = propScore false` is a.e. within `[1/Λ, Λ]`. -/
def MSMSet0 (Λ : ℝ) : Set (P.Ω → ℝ) :=
  { etilde |
      (∀ᵐ ω ∂P.μ, 0 < etilde ω ∧ etilde ω < 1) ∧
      (∀ᵐ ω ∂P.μ,
        1 / Λ ≤ OR (etilde ω) (S.propScore false ω)
          ∧ OR (etilde ω) (S.propScore false ω) ≤ Λ) }

/-- The **control MSM upper bound**: the supremum of the candidate mean over the
ambiguity set. -/
noncomputable def msmUpper0 (Λ : ℝ) : ℝ := sSup (S.candMean0 '' S.MSMSet0 Λ)

/-- The **control MSM lower bound**: the infimum of the candidate mean over the
ambiguity set. -/
noncomputable def msmLower0 (Λ : ℝ) : ℝ := sInf (S.candMean0 '' S.MSMSet0 Λ)

/-- **IPW / tower bridge (control arm).** Evaluated at the true complete control
propensity `e₀ = P[D=0 | σ(X, Y(0))]`, the candidate IPW mean recovers `E[Y(0)]`. The
`D=0` reflection of `candMean_completeProp_eq_Y1mean`. -/
theorem candMean0_completeProp0_eq_Y0mean
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hcons : P.Consistency)
    (hpos : ∀ᵐ ω ∂P.μ, 0 < S.completeProp0 ω)
    (hint : Integrable (S.YofD false) P.μ)
    (hcand_int :
      Integrable
        (fun ω => S.dVar.indicator false ω * S.factualY ω / S.completeProp0 ω) P.μ) :
    S.candMean0 S.completeProp0 = S.Y0mean := by
  classical
  set f : P.Ω → ℝ := S.dVar.indicator false with hf_def
  set e : P.Ω → ℝ := S.completeProp0 with he_def
  set g : P.Ω → ℝ := fun ω => S.YofD false ω / e ω with hg_def
  have hcons_fn :
      (fun ω => S.factualY ω * f ω) = (fun ω => S.YofD false ω * f ω) := by
    have h := POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar false (Ne.symm S.hDY)
    funext ω
    have := congr_fun h ω
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY, hf_def] using this
  have hcandMean_eq : S.candMean0 e = ∫ ω, g ω * f ω ∂P.μ := by
    unfold POBackdoorSystem.candMean0
    refine integral_congr_ae (Filter.Eventually.of_forall ?_)
    intro ω
    have hcw : S.factualY ω * f ω = S.YofD false ω * f ω := congr_fun hcons_fn ω
    simp only [hg_def, hf_def] at hcw ⊢
    rw [div_eq_mul_inv, div_eq_mul_inv]
    linear_combination (e ω)⁻¹ * hcw
  have hY0_meas : Measurable[S.sigmaXY0] (S.YofD false) := by
    have hle : MeasurableSpace.comap (S.YofD false) inferInstance ≤ S.sigmaXY0 :=
      le_sup_right
    exact (comap_measurable (S.YofD false)).mono hle le_rfl
  have he_smeas : StronglyMeasurable[S.sigmaXY0] e := by
    rw [he_def]
    exact stronglyMeasurable_condExp
  have hg_smeas : StronglyMeasurable[S.sigmaXY0] g := by
    have he_meas : Measurable[S.sigmaXY0] e := he_smeas.measurable
    exact (hY0_meas.div he_meas).stronglyMeasurable
  have hf_int : Integrable f P.μ := S.dVar.integrable_indicator false
  have hgf_int : Integrable (fun ω => g ω * f ω) P.μ := by
    refine hcand_int.congr (Filter.Eventually.of_forall ?_)
    intro ω
    have hcw : S.factualY ω * f ω = S.YofD false ω * f ω := congr_fun hcons_fn ω
    simp only [hg_def, hf_def] at hcw ⊢
    rw [div_eq_mul_inv, div_eq_mul_inv]
    linear_combination (e ω)⁻¹ * hcw
  have hpull :
      P.μ[fun ω => g ω * f ω | S.sigmaXY0] =ᵐ[P.μ] (fun ω => g ω * e ω) := by
    have h := MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (m := S.sigmaXY0) (μ := P.μ) hg_smeas hgf_int hf_int
    have he_cond : (P.μ[f | S.sigmaXY0]) = e := by
      rw [hf_def, he_def]; rfl
    refine h.trans ?_
    rw [he_cond]
    rfl
  have htower : ∫ ω, g ω * f ω ∂P.μ = ∫ ω, g ω * e ω ∂P.μ := by
    have h1 :
        ∫ ω, P.μ[fun ω => g ω * f ω | S.sigmaXY0] ω ∂P.μ
          = ∫ ω, g ω * f ω ∂P.μ :=
      MeasureTheory.integral_condExp S.sigmaXY0_le
    rw [← h1]
    exact integral_congr_ae hpull
  have hcancel : ∫ ω, g ω * e ω ∂P.μ = S.Y0mean := by
    unfold POBackdoorSystem.Y0mean
    refine integral_congr_ae ?_
    filter_upwards [hpos] with ω hω
    rw [hg_def]
    field_simp
  rw [hcandMean_eq, htower, hcancel]

/-- **The control MSM assumption: the truth lies in the ambiguity set.** -/
theorem completeProp0_mem_MSMSet0 (Λ : ℝ)
    (hMSM :
      (∀ᵐ ω ∂P.μ, 0 < S.completeProp0 ω ∧ S.completeProp0 ω < 1) ∧
      (∀ᵐ ω ∂P.μ,
        1 / Λ ≤ OR (S.completeProp0 ω) (S.propScore false ω)
          ∧ OR (S.completeProp0 ω) (S.propScore false ω) ≤ Λ)) :
    S.completeProp0 ∈ S.MSMSet0 Λ := by
  simp only [MSMSet0, Set.mem_setOf_eq]
  exact hMSM

/-- **The control MSM bound: `E[Y(0)]` lies in the control MSM interval.** -/
theorem Y0mean_mem_Icc (Λ : ℝ)
    (hmem : S.completeProp0 ∈ S.MSMSet0 Λ)
    (hbridge : S.candMean0 S.completeProp0 = S.Y0mean)
    (hbdd : BddBelow (S.candMean0 '' S.MSMSet0 Λ))
    (hbdd' : BddAbove (S.candMean0 '' S.MSMSet0 Λ)) :
    S.Y0mean ∈ Set.Icc (S.msmLower0 Λ) (S.msmUpper0 Λ) := by
  have hmemImg : S.candMean0 S.completeProp0 ∈ S.candMean0 '' S.MSMSet0 Λ :=
    Set.mem_image_of_mem _ hmem
  rw [Set.mem_Icc, ← hbridge]
  refine ⟨?_, ?_⟩
  · exact csInf_le hbdd hmemImg
  · exact le_csSup hbdd' hmemImg

/-- **Monotonicity of the control ambiguity set in the sensitivity parameter.** -/
theorem MSMSet0_mono {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ') :
    S.MSMSet0 Λ ⊆ S.MSMSet0 Λ' := by
  have hΛpos : 0 < Λ := lt_of_lt_of_le one_pos hΛ
  intro etilde hetilde
  obtain ⟨hint, hor⟩ := hetilde
  refine ⟨hint, ?_⟩
  filter_upwards [hor] with ω hω
  obtain ⟨hlo, hhi⟩ := hω
  constructor
  · have h1 : 1 / Λ' ≤ 1 / Λ := one_div_le_one_div_of_le hΛpos hΛΛ'
    exact le_trans h1 hlo
  · exact le_trans hhi hΛΛ'

/-- **The control MSM interval widens with `Λ` (upper endpoint).** -/
theorem msmUpper0_mono {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ')
    (hne : (S.candMean0 '' S.MSMSet0 Λ).Nonempty)
    (hbdd' : BddAbove (S.candMean0 '' S.MSMSet0 Λ')) :
    S.msmUpper0 Λ ≤ S.msmUpper0 Λ' := by
  have hsub : S.MSMSet0 Λ ⊆ S.MSMSet0 Λ' := S.MSMSet0_mono hΛ hΛΛ'
  have himg : S.candMean0 '' S.MSMSet0 Λ ⊆ S.candMean0 '' S.MSMSet0 Λ' :=
    Set.image_mono hsub
  exact csSup_le_csSup hbdd' hne himg

/-- **The control MSM interval widens with `Λ` (lower endpoint).** -/
theorem msmLower0_anti {Λ Λ' : ℝ} (hΛ : 1 ≤ Λ) (hΛΛ' : Λ ≤ Λ')
    (hne : (S.candMean0 '' S.MSMSet0 Λ).Nonempty)
    (hbdd' : BddBelow (S.candMean0 '' S.MSMSet0 Λ')) :
    S.msmLower0 Λ' ≤ S.msmLower0 Λ := by
  have hsub : S.MSMSet0 Λ ⊆ S.MSMSet0 Λ' := S.MSMSet0_mono hΛ hΛΛ'
  have himg : S.candMean0 '' S.MSMSet0 Λ ⊆ S.candMean0 '' S.MSMSet0 Λ' :=
    Set.image_mono hsub
  exact csInf_le_csInf hbdd' hne himg

/-- **Point identification at `Λ = 1` (control arm, NUC collapse).** -/
theorem MSMSet0_one_eq (etilde : P.Ω → ℝ)
    (hprop : ∀ᵐ ω ∂P.μ, 0 < S.propScore false ω ∧ S.propScore false ω < 1)
    (hmem : etilde ∈ S.MSMSet0 1) :
    ∀ᵐ ω ∂P.μ, etilde ω = S.propScore false ω := by
  obtain ⟨hint, hor⟩ := hmem
  filter_upwards [hprop, hint, hor] with ω hq hp hOR
  obtain ⟨hqpos, hqlt⟩ := hq
  obtain ⟨hppos, hplt⟩ := hp
  obtain ⟨hlo, hhi⟩ := hOR
  rw [one_div, inv_one] at hlo
  have hOReq : OR (etilde ω) (S.propScore false ω) = 1 := le_antisymm hhi hlo
  set p := etilde ω with hpdef
  set q := S.propScore false ω with hqdef
  have h1p : (0:ℝ) < 1 - p := by linarith
  have h1q : (0:ℝ) < 1 - q := by linarith
  have hqratio : q / (1 - q) ≠ 0 := by
    apply div_ne_zero
    · exact ne_of_gt hqpos
    · exact ne_of_gt h1q
  rw [OR, div_eq_one_iff_eq hqratio] at hOReq
  field_simp at hOReq
  nlinarith [hOReq]

end POBackdoorSystem

end PO
end Causalean
