# Higher Cumulants Separate Latent-Source Arrows

TL;DR: With a fixed number of middle source slots and an axis normalization, population cumulants generically exclude the opposite representation fiber at order \(2m+2\), and at order \(2m+1\) over the real feasible region when \(m\ge3\).

---

## The Punchline

- The paper studies two axis-normalized latent-source representations of \((X,Y)\): one tagged \(X\to Y\), one tagged \(Y\to X\).
- The maintained inputs are a fixed number \(m\) of middle source slots and independent non-Gaussian sources.
- At order \(2m+2\), higher-order population cumulants generically recover the unordered loading-slope support.
- That recovered support generically selects one axis convention and leaves the opposite-arrow cumulant-map fiber empty.
- The exceptional compatibility locus has codimension exactly one inside each arrow image variety.
- For real feasible parameters with \(m\ge3\), generic opposite-arrow exclusion already holds at order \(2m+1\).

---

## Why This Question Matters

- In Gaussian linear models, covariance restrictions are symmetric enough that arrows are hard to orient.
- Non-Gaussian higher moments contain directional asymmetries that covariance does not see.
- Latent sources make the bivariate problem harder because shared factors can mimic direct dependence.
- The econometric question is: when do population cumulants rule out the competing recursive representation?
- The paper answers this question inside a fixed source-count, axis-normalized latent LiNGAM class.

---

## Running Example: Two Outcomes with Shared Latent Shocks

- Think of \(X\) and \(Y\) as two economic outcomes affected by independent latent shocks.
- Each candidate story pins one shock to a coordinate axis, gives one shock the direct slope, and lets \(m\) middle shocks load on both coordinates.
- The forward story fixes the vertical-axis slot and tags the direct slot \(X\to Y\); the reverse story fixes the horizontal-axis slot and tags its direct slot \(Y\to X\).
- The observed object is the population joint cumulant vector through a finite order.
- The question is whether the same cumulants can be generated by the opposite story with the same \(m\).

@figure latent-source-axis-normalization: The diagram shows the two axis-normalized representations side by side — the forward one built from a free-slope direct slot, \(m\) middle slots, and a fixed vertical-axis slot; the reverse one from a fixed horizontal-axis slot, \(m\) middle slots, and its own direct slot — both feeding the same truncated cumulant vector.

---

## The Minimal Model

- There are \(m+2\) centered latent source slots \(S_0,\ldots,S_{m+1}\).
- Independence makes cumulants add across source slots.
- Finite \(K\)-th moments make cumulants through order \(K\) well-defined.
- Non-Gaussianity supplies higher-order information beyond covariance.
- Genericity means distinct finite loading slopes, nonzero direct slope, and nonzero retained source cumulants.

@formal ass:independent-sources

---

## The Two Axis Conventions

- In the forward convention, the direct slot has loading direction \((1,\gamma)\), the middle slots have \((1,\rho_j)\), and the fixed vertical slot has \((0,1)\).
- In the reverse convention, the fixed horizontal slot has \((1,0)\), the middle slots have \((\sigma_j,1)\), and the direct slot has \((\delta,1)\).
- The axis normalization makes the two representations directly comparable.
- In the running example, the normalization says which latent shock slot is treated as the direct recursive component.

@formal ass:forward-axis-model

@formal ass:reverse-axis-model

---

## What the Cumulant Map Records

- \(T_L(P)\), the truncated cumulant vector, collects all mixed cumulants of \(X\) and \(Y\) from orders \(2\) through \(L\).
- Each source contributes one order-specific cumulant weight times a monomial in its loading direction.
- The forward and reverse cumulant maps are polynomial maps from loading slopes and source cumulant weights to \(T_L(P)\).
- A fiber is the set of parameters that produce the same truncated cumulant vector.
- An arrow image variety is the set of cumulant vectors one arrow convention can reach, closed up in the Zariski sense.
- The target is opposite-fiber emptiness: a cumulant vector from one arrow has no full representation under the other arrow.

---

## The Key Idea

- At order \(2m+2\), the cumulant blocks behave like a simultaneous binary-form decomposition with \(m+2\) loading directions.
- Apolarity here means: a form \(q\) is apolar to the blocks when the differential operator \(q(\partial)\) kills every retained cumulant form, which happens exactly when \(q\) vanishes on the loading directions.
- Apolar equations recover the unordered support of those loading directions on a generic locus.
- The recovered support carries an axis signature: forward support contains the vertical-axis pattern, while reverse support contains the horizontal-axis pattern.
- Once the support is recovered, the opposite axis convention would require an incompatible axis signature.
- This is the reason cumulants separate arrows at the representation level.

@figure apolar-support-recovery: The diagram shows cumulant blocks feeding an apolar recovery step, which outputs an unordered loading-direction support whose axis membership distinguishes the forward and reverse conventions.

---

## Where the Literature Stands

- Structural causal models and graphical identification give the broad language for observational direction questions.
- LiNGAM and ICA show how non-Gaussianity can identify linear structure under stronger source restrictions.
- Latent-variable LiNGAM work studies how hidden confounding changes what can be recovered.
- Recent cumulant and tensor methods use higher-order restrictions to recover latent causal information.
- The immediate comparator proves a direction test under an arbitrary number of latent confounders, using an order-\(2m+3\) rank-deficiency construction.
- This paper gives an algebraic representation-level separation result at order \(2m+2\), with a sharper real generic separation order for \(m\ge3\).

---

## Main Result 1: Support Recovery and Arrow Separation

@informal thm:generic-apolar-arrow-recovery: At order \(2m+2\), on relatively Zariski-open dense loci with real feasible patches, apolar equations recover the unordered loading-slope support and the opposite-arrow fiber is empty.

@formal thm:generic-apolar-arrow-recovery

---

## Main Result 2: Same-Arrow Fibers Still Matter

@informal thm:generic-arrow-recovery-and-fiber-obstruction: At order \(2m+2\), the same-arrow fiber preserves the unordered finite loading-slope multiset, while direct-slot and middle-slot swaps give residual ambiguity beyond admissible middle-source relabelling.

@formal thm:generic-arrow-recovery-and-fiber-obstruction

---

## Why the Novelty Wins

- A covariance-level comparison sees only second-order structure and cannot recover the finite loading support.
- A direct same-arrow parameter recovery target is too strong because direct and middle slots can swap while preserving cumulants.
- The paper targets the sharper object: the opposite-arrow fiber under the maintained axis convention.
- The apolar step uses order \(2m+2=2n-2\) with \(n=m+2\) loading directions to recover support.
- That support-level recovery removes the ambiguity that matters for opposite-arrow compatibility, while allowing same-arrow nonuniqueness.

---

## Main Result 3: The Exceptional Set

@informal thm:exceptional-locus-codimension-one: At order \(2m+2\), the closure of cumulant vectors compatible with both arrow conventions has codimension exactly one inside each arrow image variety.

@formal thm:exceptional-locus-codimension-one

---

## Main Result 4: The Real Order Improves

- The information order \(K^\star(m)\) is the smallest truncation order at which, for each arrow and outside a proper real algebraic subset, a real feasible cumulant vector has no representation under the opposite arrow.

@informal thm:improved-real-information-order: For \(m\ge3\), order \(2m+1\) is enough for generic real opposite-arrow exclusion, and \(K^\star(m)\) is at most \(2m+1\).

@formal thm:improved-real-information-order

---

## Also in the Paper

@informal thm:exact-real-exceptional-atlas: A stated future research direction asks whether, for every fixed \(m\), a finite computable semialgebraic atlas can exactly describe the real exceptional closure and feasible fibers.

---

## Why the Apolar Result Is True

- Independence turns the cumulant of \((X,Y)\) into a sum of source-level contributions.
- Each cumulant order becomes a binary form built from the same loading directions with different source weights.
- Across the retained orders, the common annihilator identifies the finite support of loading directions.
- On the generic locus, the annihilator is unique up to scale and squarefree.
- The recovered support reveals which coordinate axis is fixed by the representation.

---

## Why Opposite Compatibility Is Exceptional

- A cumulant vector compatible with both arrows must admit two simultaneous decompositions with different fixed-axis conventions.
- The comparison is made after quotienting only the admissible relabelling of middle source slots.
- The axis slots remain distinguished, so direct-axis and fixed-axis constraints still impose algebraic restrictions.
- The resulting compatibility locus is a hypersurface in each arrow image variety.
- For \(m=1\) and \(m=2\), the paper records explicit incidence systems for this compatibility event.

---

## Takeaways

- Higher-order cumulants establish generic representation-level arrow separation in a fixed, axis-normalized latent-source class.
- Order \(2m+2\) recovers the unordered loading-slope support and excludes the opposite-arrow fiber on generic loci.
- Same-arrow parametrizations retain structured ambiguity beyond middle-source relabelling.
- The opposite-arrow compatibility locus has codimension exactly one at the apolar order.
- For \(m\ge3\), real feasible generic separation holds already at order \(2m+1\).
- The results characterize population information available before finite-sample estimation.
