/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# σ-algebra-based conditional expectation on `POCFBundle`s

Lifts the single-`POVar` conditioning machinery in `CondExpTooling.lean` to a
`POCFBundle`, i.e. conditioning on the joint cf-value map of a tuple of
regimed variables.  Used by the DTR / multi-stage backdoor identification
arguments where the conditioning σ-algebra is generated by a *bundle* of
covariates rather than a single one.
-/

import Causalean.PO.Assumptions.IndepCF
import Causalean.PO.Conditioning.CondExpTooling
import Mathlib.Probability.ConditionalExpectation
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-! # Bundle Conditional Expectations

This file defines the σ-algebra generated by a bundle of regimed
potential-outcome variables and provides conditional expectations, conditional
ratios, and bundle-conditioned independence statements relative to that
σ-algebra. It extends the single-variable conditioning interface to finite
counterfactual bundles.

The key definitions are `POCFBundle.sigma`, `POCFBundle.condExpGiven`,
`POCFBundle.condExpRatio`, and `POSystem.CondIndepCFBundle`.  The file also
provides measurability, integrability, tower, pull-out, a.e.-congruence, ratio,
and projection lemmas used by bundle-conditioned identification arguments. -/

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

noncomputable section

namespace POCFBundle

variable {P : POSystem} (B : POCFBundle P)

/-- The conditioning σ-algebra of a counterfactual bundle `B` (a finite collection
of counterfactual variables over a potential-outcome system): the σ-algebra on the
sample space generated by jointly observing all of `B`'s counterfactual values —
i.e. the information content of the whole bundle. It is the bundle analogue of the
single-variable conditioning σ-algebra `σ(c.factual)` (the information in one
variable `c`), generalised from one variable to the bundle's joint value map. -/
def sigma : MeasurableSpace P.Ω :=
  MeasurableSpace.comap B.jointValue inferInstance

/-- The conditioning σ-algebra `B.sigma` is a sub-σ-algebra of the ambient
σ-algebra on `P.Ω`. -/
lemma sigma_le : B.sigma ≤ (inferInstance : MeasurableSpace P.Ω) :=
  B.measurable_jointValue.comap_le

/-- The bundle conditional expectation averages a real-valued sample-space
quantity given the sigma-algebra generated by the bundle's joint
counterfactual-value map.

Bundle analogue of `POVar.condExpGiven`. -/
def condExpGiven (g : P.Ω → ℝ) (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  μ[g | B.sigma]

/-- `condExpGiven` yields a function strongly measurable w.r.t. `B.sigma`. -/
lemma stronglyMeasurable_condExpGiven_comap (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    StronglyMeasurable[B.sigma] (B.condExpGiven g μ) :=
  MeasureTheory.stronglyMeasurable_condExp
    (μ := μ) (m := B.sigma) (f := g)

/-- `condExpGiven` yields a strongly measurable function w.r.t. the ambient
σ-algebra. -/
lemma stronglyMeasurable_condExpGiven (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    StronglyMeasurable (B.condExpGiven g μ) :=
  (B.stronglyMeasurable_condExpGiven_comap g).mono B.sigma_le

/-- Mathlib's totalized conditional expectation given the bundle's σ-algebra is
integrable, even when the original sample-space function is not assumed
integrable. -/
lemma integrable_condExpGiven (g : P.Ω → ℝ) {μ : Measure P.Ω} :
    Integrable (B.condExpGiven g μ) μ := by
  simpa [POCFBundle.condExpGiven] using
    (MeasureTheory.integrable_condExp (μ := μ) (m := B.sigma) (f := g))

/-! ### Tower property and pull-out (mirrors `POVar` versions) -/

/-- Tower property over an arbitrary smaller sub-σ-algebra `m ≤ B.sigma`.
Requires the usual `SigmaFinite` hypothesis on the trim of `μ` to
`B.sigma`. -/
lemma condExpGiven_tower_of_le {g : P.Ω → ℝ} {μ : Measure P.Ω}
    {m : MeasurableSpace P.Ω} (hm : m ≤ B.sigma)
    [SigmaFinite (μ.trim B.sigma_le)] :
    μ[B.condExpGiven g μ | m] =ᵐ[μ] μ[g | m] := by
  simpa [POCFBundle.condExpGiven] using
    MeasureTheory.condExp_condExp_of_le (μ := μ) (f := g) hm B.sigma_le

/-- Pull-out-left for `condExpGiven`: if `f` is strongly measurable w.r.t.
`B.sigma`, then `μ[f·g | B.sigma] =ᵐ f · μ[g | B.sigma]`. -/
lemma condExpGiven_mul_of_stronglyMeasurable_left
    {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : StronglyMeasurable[B.sigma] f)
    (hfg : Integrable (f * g) μ) (hg : Integrable g μ) :
    B.condExpGiven (f * g) μ =ᵐ[μ] f * B.condExpGiven g μ := by
  simpa [POCFBundle.condExpGiven] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (μ := μ) (m := B.sigma) hf hfg hg

/-- Pull-out-right for `condExpGiven`. -/
lemma condExpGiven_mul_of_stronglyMeasurable_right
    {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hg : StronglyMeasurable[B.sigma] g)
    (hfg : Integrable (f * g) μ) (hf : Integrable f μ) :
    B.condExpGiven (f * g) μ =ᵐ[μ] B.condExpGiven f μ * g := by
  simpa [POCFBundle.condExpGiven] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_right
      (μ := μ) (m := B.sigma) hg hfg hf

/-- Indicator pull-out for `condExpGiven`: if `s` is `B.sigma`-measurable, the
indicator `1_s` factors out of the bundle conditional expectation. -/
lemma condExpGiven_indicator_mul
    {s : Set P.Ω} {g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hs : MeasurableSet[B.sigma] s)
    (hsg : Integrable (s.indicator (fun _ => (1 : ℝ)) * g) μ) (hg : Integrable g μ) :
    B.condExpGiven (s.indicator (fun _ => (1 : ℝ)) * g) μ
      =ᵐ[μ] s.indicator (fun _ => (1 : ℝ)) * B.condExpGiven g μ :=
  B.condExpGiven_mul_of_stronglyMeasurable_left
    ((stronglyMeasurable_const (b := (1 : ℝ))).indicator hs) hsg hg

/-- a.e. congruence for `condExpGiven`: if `f =ᵐ g`, then their bundle
conditional expectations agree a.e. -/
lemma condExpGiven_congr_ae {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (h : f =ᵐ[μ] g) : B.condExpGiven f μ =ᵐ[μ] B.condExpGiven g μ := by
  unfold POCFBundle.condExpGiven
  exact MeasureTheory.condExp_congr_ae h

/-! ### Conditional ratio (bundle analogue of `POVar.condExpRatio`) -/

/-- The bundle conditional-expectation ratio compares two real-valued
sample-space quantities after conditioning on the sigma-algebra generated by
the bundle's joint counterfactual-value map. -/
def condExpRatio (g h : P.Ω → ℝ) (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  fun ω => (B.condExpGiven g μ ω) / (B.condExpGiven h μ ω)

/-- The conditional-ratio function of two real integrands given a
counterfactual bundle is measurable. -/
lemma measurable_condExpRatio (g h : P.Ω → ℝ) {μ : Measure P.Ω} :
    Measurable (B.condExpRatio g h μ) := by
  unfold POCFBundle.condExpRatio
  exact (B.stronglyMeasurable_condExpGiven g).measurable.div
    (B.stronglyMeasurable_condExpGiven h).measurable

/-- The conditional-ratio function of two real integrands given a
counterfactual bundle is strongly measurable. -/
lemma stronglyMeasurable_condExpRatio (g h : P.Ω → ℝ) {μ : Measure P.Ω} :
    StronglyMeasurable (B.condExpRatio g h μ) :=
  (B.measurable_condExpRatio g h).stronglyMeasurable

/-- **Characterisation of bundle `condExpRatio` via a product identity.** -/
lemma condExpRatio_eq_of_mul {g h target : P.Ω → ℝ} {μ : Measure P.Ω}
    (hprod : B.condExpGiven g μ =ᵐ[μ] B.condExpGiven h μ * target)
    (hne : ∀ᵐ ω ∂μ, B.condExpGiven h μ ω ≠ 0) :
    B.condExpRatio g h μ =ᵐ[μ] target := by
  unfold POCFBundle.condExpRatio
  filter_upwards [hprod, hne] with ω hω hne
  simp only [Pi.mul_apply] at hω
  rw [hω]
  field_simp

end POCFBundle

/-- A regimed potential-outcome variable and one counterfactual bundle are
conditionally independent given the sigma-algebra generated by another
counterfactual bundle's joint counterfactual-value map.

Bundle analogue of `POSystem.CondIndepCF`. -/
def POSystem.CondIndepCFBundle
    (P : POSystem) [StandardBorelSpace P.Ω]
    {α : Type*} [MeasurableSpace α]
    (a : RegimedVar P α) (B : POCFBundle P) (C : POCFBundle P)
    (μ : Measure P.Ω := P.μ) [IsFiniteMeasure μ] : Prop :=
  ProbabilityTheory.CondIndepFun C.sigma C.sigma_le a.value B.jointValue μ

namespace POSystem

variable {P : POSystem}

/-- Bridge: `CondIndepCFBundle` unfolds to `CondIndepFun` w.r.t. `C.sigma`. -/
lemma CondIndepCFBundle.toCondIndepFun
    [StandardBorelSpace P.Ω]
    {α : Type*} [MeasurableSpace α]
    {a : RegimedVar P α} {B C : POCFBundle P}
    {μ : Measure P.Ω} [IsFiniteMeasure μ] :
    P.CondIndepCFBundle a B C μ →
      ProbabilityTheory.CondIndepFun C.sigma C.sigma_le a.value B.jointValue μ := id

/-- Project a `CondIndepCFBundle` onto a measurable function of the bundle's
joint value. -/
lemma CondIndepCFBundle.project
    [StandardBorelSpace P.Ω]
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β]
    {a : RegimedVar P α} {B C : POCFBundle P}
    {μ : Measure P.Ω} [IsFiniteMeasure μ]
    {ψ : (∀ i, B.type i) → β} (h : P.CondIndepCFBundle a B C μ)
    (hψ : Measurable ψ) :
    ProbabilityTheory.CondIndepFun C.sigma C.sigma_le a.value (ψ ∘ B.jointValue) μ :=
  h.toCondIndepFun.comp measurable_id hψ

end POSystem

end

end PO
end Causalean
