/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Causalean.PO.Core.Variable
import Mathlib.Probability.ConditionalExpectation
import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut

/-! # Conditional Expectations Given Potential-Outcome Variables

This file wraps conditional expectation so that the conditioning information is
the σ-algebra generated by the factual value of a potential-outcome variable.
It supports regression-style identification arguments by also defining ratios of
conditional expectations and their basic algebraic properties.

The public interface is centered on `POVar.condExpGiven`,
`POVar.condExpRatio`, tower and pull-out lemmas for `condExpGiven`, the product
identity `POVar.condExpRatio_eq_of_mul`, and the CATE-to-ATE integration lemma
`POVar.integral_sub_eq_integral_sub_of_condExpGiven_ae_eq`. -/

namespace Causalean.PO
open MeasureTheory ProbabilityTheory

noncomputable section

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]

/-- For a conditioning potential-outcome variable, a real-valued function on the
sample space, and a measure on the sample space, this is the conditional
expectation of that function given the σ-algebra generated by the factual value
of the conditioning variable.

Conditional expectation of an integrand `g : P.Ω → ℝ` given the
σ-algebra generated by the factual map of a `POVar` `c`.  Equal to
`μ[g | σ(c.factual)]` in Mathlib notation. -/
def POVar.condExpGiven (c : POVar P γ) (g : P.Ω → ℝ)
    (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  μ[g | MeasurableSpace.comap c.factual inferInstance]

/-- The conditioning σ-algebra `σ(c.factual)` is a sub-σ-algebra of the ambient
σ-algebra on `P.Ω`. -/
lemma POVar.comap_factual_le (c : POVar P γ) :
    MeasurableSpace.comap c.factual inferInstance ≤ (inferInstance : MeasurableSpace P.Ω) :=
  c.measurable_factual.comap_le

/-! ### Integrability helpers -/

/-- Multiplying an integrable function by a `POVar` factual indicator preserves
integrability. -/
lemma POVar.integrable_mul_indicator
    {α : Type*} [MeasurableSpace α] [MeasurableSingletonClass α]
    (a : POVar P α) (x : α)
    {f : P.Ω → ℝ} (hf : Integrable f P.μ) (hf_meas : Measurable f) :
    Integrable (fun ω => f ω * a.indicator x ω) P.μ := by
  refine hf.mono (hf_meas.mul (a.measurable_indicator x)).aestronglyMeasurable ?_
  refine Filter.Eventually.of_forall (fun ω => ?_)
  rcases a.indicator_eq_one_or_zero x ω with h | h <;> simp [h]

/-! ### Basic algebra wrappers -/

/-- Linearity of `condExpGiven`: additivity. -/
lemma POVar.condExpGiven_add (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) (hg : Integrable g μ) :
    c.condExpGiven (f + g) μ =ᵐ[μ] c.condExpGiven f μ + c.condExpGiven g μ := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_add (μ := μ) hf hg (MeasurableSpace.comap c.factual inferInstance)

/-- Linearity of `condExpGiven`: subtraction. -/
lemma POVar.condExpGiven_sub (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : Integrable f μ) (hg : Integrable g μ) :
    c.condExpGiven (f - g) μ =ᵐ[μ] c.condExpGiven f μ - c.condExpGiven g μ := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_sub (μ := μ) hf hg (MeasurableSpace.comap c.factual inferInstance)

/-- Scalar homogeneity of `condExpGiven`. -/
lemma POVar.condExpGiven_smul (c : POVar P γ) (k : ℝ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} :
    c.condExpGiven (k • g) μ =ᵐ[μ] k • c.condExpGiven g μ := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_smul (μ := μ) k g (MeasurableSpace.comap c.factual inferInstance)

/-- `condExpGiven` yields a function strongly measurable w.r.t. `σ(c.factual)`. -/
lemma POVar.stronglyMeasurable_condExpGiven_comap (c : POVar P γ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} :
    StronglyMeasurable[MeasurableSpace.comap c.factual inferInstance] (c.condExpGiven g μ) :=
  MeasureTheory.stronglyMeasurable_condExp
    (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) (f := g)

/-- `condExpGiven` yields a strongly measurable function w.r.t. the ambient σ-algebra. -/
lemma POVar.stronglyMeasurable_condExpGiven (c : POVar P γ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} : StronglyMeasurable (c.condExpGiven g μ) :=
  (c.stronglyMeasurable_condExpGiven_comap g).mono c.comap_factual_le

/-- Mathlib's totalized conditional expectation given the variable's σ-algebra
is integrable, even when the original sample-space function is not assumed
integrable. -/
lemma POVar.integrable_condExpGiven (c : POVar P γ) (g : P.Ω → ℝ)
    {μ : Measure P.Ω} : Integrable (c.condExpGiven g μ) μ := by
  simpa [POVar.condExpGiven] using
    (MeasureTheory.integrable_condExp
      (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) (f := g))

/-! ### Pull-out-left (product with a `σ(c.factual)`-measurable factor) -/

/-- Pull-out-left for `condExpGiven`: if `f` is strongly measurable w.r.t.
`σ(c.factual)`, then `μ[f·g | σ(c.factual)] =ᵐ f · μ[g | σ(c.factual)]`. -/
lemma POVar.condExpGiven_mul_of_stronglyMeasurable_left
    (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hf : StronglyMeasurable[MeasurableSpace.comap c.factual inferInstance] f)
    (hfg : Integrable (f * g) μ) (hg : Integrable g μ) :
    c.condExpGiven (f * g) μ =ᵐ[μ] f * c.condExpGiven g μ := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_left
      (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) hf hfg hg

/-- Pull-out-right for `condExpGiven`. -/
lemma POVar.condExpGiven_mul_of_stronglyMeasurable_right
    (c : POVar P γ) {f g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hg : StronglyMeasurable[MeasurableSpace.comap c.factual inferInstance] g)
    (hfg : Integrable (f * g) μ) (hf : Integrable f μ) :
    c.condExpGiven (f * g) μ =ᵐ[μ] c.condExpGiven f μ * g := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_mul_of_stronglyMeasurable_right
      (μ := μ) (m := MeasurableSpace.comap c.factual inferInstance) hg hfg hf

/-- Pull-out version specialised to indicator functions of sets measurable
w.r.t. `σ(c.factual)`.  If the event is measurable with respect to the
conditioning variable's factual σ-algebra, its indicator factors out of the
conditional expectation just like any other strongly measurable multiplier. -/
lemma POVar.condExpGiven_indicator_mul
    (c : POVar P γ) {s : Set P.Ω} {g : P.Ω → ℝ} {μ : Measure P.Ω}
    (hs : MeasurableSet[MeasurableSpace.comap c.factual inferInstance] s)
    (hsg : Integrable (s.indicator (fun _ => (1 : ℝ)) * g) μ) (hg : Integrable g μ) :
    c.condExpGiven (s.indicator (fun _ => (1 : ℝ)) * g) μ
      =ᵐ[μ] s.indicator (fun _ => (1 : ℝ)) * c.condExpGiven g μ :=
  c.condExpGiven_mul_of_stronglyMeasurable_left
    ((stronglyMeasurable_const (b := (1 : ℝ))).indicator hs) hsg hg

/-! ### Tower property -/

/-- Tower property over an arbitrary smaller sub-σ-algebra `m ≤ σ(c.factual)`.
Requires the usual `SigmaFinite` hypothesis on the trim of `μ` to
`σ(c.factual)`. -/
lemma POVar.condExpGiven_tower_of_le (c : POVar P γ) {g : P.Ω → ℝ} {μ : Measure P.Ω}
    {m : MeasurableSpace P.Ω} (hm : m ≤ MeasurableSpace.comap c.factual inferInstance)
    [SigmaFinite (μ.trim c.comap_factual_le)] :
    μ[c.condExpGiven g μ | m] =ᵐ[μ] μ[g | m] := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_condExp_of_le (μ := μ) (f := g) hm c.comap_factual_le

/-- Tower property between two POVars: if `σ(c₁.factual) ≤ σ(c₂.factual)`, then
`μ[μ[g|σ(c₂)] | σ(c₁)] =ᵐ μ[g|σ(c₁)]`. -/
lemma POVar.condExpGiven_tower {δ : Type*} [MeasurableSpace δ]
    (c₁ : POVar P γ) (c₂ : POVar P δ) {g : P.Ω → ℝ} {μ : Measure P.Ω}
    (h : MeasurableSpace.comap c₁.factual inferInstance
          ≤ MeasurableSpace.comap c₂.factual inferInstance)
    [SigmaFinite (μ.trim c₂.comap_factual_le)] :
    c₁.condExpGiven (c₂.condExpGiven g μ) μ =ᵐ[μ] c₁.condExpGiven g μ := by
  simpa [POVar.condExpGiven] using
    MeasureTheory.condExp_condExp_of_le (μ := μ) (f := g) h c₂.comap_factual_le

/-! ### Conditional ratios -/

/-- For a conditioning potential-outcome variable, two real-valued functions on
the sample space, and a measure on the sample space, this is the pointwise ratio
of the conditional expectation of the first function to the conditional
expectation of the second function, both given the σ-algebra generated by the
factual value of the conditioning variable.

Pointwise ratio of two conditional expectations given `σ(c.factual)`.
Used as the adjusted regression in the backdoor ATE proof:
`condExpRatio c (Y·1_{D=d}) (1_{D=d}) = E[Y|D=d,X]` under overlap. -/
def POVar.condExpRatio (c : POVar P γ) (g h : P.Ω → ℝ)
    (μ : Measure P.Ω := P.μ) : P.Ω → ℝ :=
  fun ω => (c.condExpGiven g μ ω) / (c.condExpGiven h μ ω)

/-- `condExpRatio` is measurable (pointwise division of two
strongly measurable functions is measurable). -/
lemma POVar.measurable_condExpRatio (c : POVar P γ) (g h : P.Ω → ℝ)
    {μ : Measure P.Ω} : Measurable (c.condExpRatio g h μ) := by
  unfold POVar.condExpRatio
  exact (c.stronglyMeasurable_condExpGiven g).measurable.div
    (c.stronglyMeasurable_condExpGiven h).measurable

/-- `condExpRatio` is strongly measurable. -/
lemma POVar.stronglyMeasurable_condExpRatio (c : POVar P γ) (g h : P.Ω → ℝ)
    {μ : Measure P.Ω} : StronglyMeasurable (c.condExpRatio g h μ) :=
  (c.measurable_condExpRatio g h).stronglyMeasurable

/-- **Characterisation of `condExpRatio` via a product identity.**
If `μ[g|σ(c)] = μ[h|σ(c)] · target` a.s. and `μ[h|σ(c)] ≠ 0` a.s., then
`condExpRatio c g h =ᵐ target`.  This is the reusable algebraic step for
turning a conditional-expectation product identity into a ratio identity. -/
lemma POVar.condExpRatio_eq_of_mul (c : POVar P γ) {g h target : P.Ω → ℝ}
    {μ : Measure P.Ω}
    (hprod : c.condExpGiven g μ =ᵐ[μ] c.condExpGiven h μ * target)
    (hne : ∀ᵐ ω ∂μ, c.condExpGiven h μ ω ≠ 0) :
    c.condExpRatio g h μ =ᵐ[μ] target := by
  unfold POVar.condExpRatio
  filter_upwards [hprod, hne] with ω hω hne
  simp only [Pi.mul_apply] at hω
  rw [hω]
  field_simp

/-- **CATE-to-ATE integrator.**  If `μ[f|σ(c)] =ᵐ f'` and `μ[g|σ(c)] =ᵐ g'`
(both a.e.), and `f`, `g` are integrable, then
    ∫ (f - g) dμ = ∫ (f' - g') dμ.

This is the last step of any outcome-regression identification: turn a
CATE-level identity (`μ[Y(1)|σX] =ᵐ adjusted₁`, `μ[Y(0)|σX] =ᵐ adjusted₀`)
into an ATE-level identity (`∫ (Y(1) − Y(0)) dμ = ∫ (adjusted₁ − adjusted₀) dμ`). -/
theorem POVar.integral_sub_eq_integral_sub_of_condExpGiven_ae_eq
    (c : POVar P γ) {f g f' g' : P.Ω → ℝ} {μ : Measure P.Ω}
    [SigmaFinite (μ.trim c.comap_factual_le)]
    (hf : Integrable f μ) (hg : Integrable g μ)
    (hf' : c.condExpGiven f μ =ᵐ[μ] f')
    (hg' : c.condExpGiven g μ =ᵐ[μ] g') :
    ∫ ω, f ω - g ω ∂μ = ∫ ω, f' ω - g' ω ∂μ := by
  have hIf : ∫ ω, f ω ∂μ = ∫ ω, c.condExpGiven f μ ω ∂μ := by
    unfold POVar.condExpGiven
    exact (MeasureTheory.integral_condExp c.comap_factual_le).symm
  have hIg : ∫ ω, g ω ∂μ = ∫ ω, c.condExpGiven g μ ω ∂μ := by
    unfold POVar.condExpGiven
    exact (MeasureTheory.integral_condExp c.comap_factual_le).symm
  rw [MeasureTheory.integral_sub hf hg, hIf, hIg,
    ← MeasureTheory.integral_sub (c.integrable_condExpGiven f)
      (c.integrable_condExpGiven g)]
  exact MeasureTheory.integral_congr_ae (hf'.sub hg')

end

end Causalean.PO
