import Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension.ZariskiClosure
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Polynomial maps and their coordinate algebras

This module fixes the concrete conventions used by the affine polynomial-image
dimension bridge. It uses the neutral affine Zariski closure substrate.
-/

namespace Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension

noncomputable section

/-- A polynomial coordinate map sends a complex parameter vector to the vector
of values of a specified finite family of coordinate polynomials. -/
def polynomialCoordinateMap {ι κ : Type*} (f : κ → MvPolynomial ι ℂ) :
    (ι → ℂ) → (κ → ℂ) :=
  fun x k => MvPolynomial.eval x (f k)

/-- Polynomial pullback replaces each target coordinate in a polynomial relation
by its corresponding source-coordinate polynomial. -/
def polynomialPullback {ι κ : Type*} (f : κ → MvPolynomial ι ℂ) :
    MvPolynomial κ ℂ →ₐ[ℂ] MvPolynomial ι ℂ :=
  MvPolynomial.aeval f

/-- The coordinate subalgebra is the complex algebra generated by the coordinate
polynomials of a polynomial parameterization. -/
abbrev polynomialCoordinateSubalgebra {ι κ : Type*}
    (f : κ → MvPolynomial ι ℂ) : Subalgebra ℂ (MvPolynomial ι ℂ) :=
  (polynomialPullback f).range

/-- The polynomial image closure is the smallest complex algebraic set containing
all values attained by the polynomial parameterization. -/
abbrev polynomialImageClosure {ι κ : Type*} (f : κ → MvPolynomial ι ℂ) :
    Set (κ → ℂ) :=
  affineZariskiClosure (Set.range (polynomialCoordinateMap f))

/-- Substitution by `f` agrees pointwise with evaluation after the coordinate map. -/
lemma eval_polynomialPullback {ι κ : Type*} (f : κ → MvPolynomial ι ℂ)
    (x : ι → ℂ) (P : MvPolynomial κ ℂ) :
    MvPolynomial.eval x (polynomialPullback f P) =
      MvPolynomial.eval (polynomialCoordinateMap f x) P := by
  change MvPolynomial.eval x (MvPolynomial.eval₂ MvPolynomial.C f P) = _
  rw [MvPolynomial.eval_eval₂]
  rw [show (MvPolynomial.eval x).comp MvPolynomial.C = RingHom.id ℂ by
    ext c
    simp]
  rfl

end

end Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension
