/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Cell-level potential outcomes for a panel

This file defines the core potential-outcome object for panel regression.  The
structure `PanelPOSystem` bundles:

* observed cells `R ⊆ I × T` with positive normalized weights;
* a treatment-path-valued random variable `D : Ω → TreatmentPath I T A`;
* an observed-cell exposure mapping `e` and baseline `e0`;
* potential outcomes `Y r e ω : ℝ` and observed outcomes `Yobs r ω` for
  each observed cell `r ∈ R`.

It also defines:

* `observedExposure r hr ω = e r hr (D ω)` — the realized exposure at an
  observed cell;
* `DSigmaAlg` — the σ-algebra `σ(D)` generated by the treatment path;
* `m0 r hr ω = E[Y r hr (e0 r hr) | σ(D)](ω)` — the baseline conditional
  mean;
* `tau r hr e ω = E[Y r hr e − Y r hr (e0 r hr) | σ(D)](ω)` — the
  cell-level exposure response.
-/

import Causalean.Panel.Cells
import Causalean.Panel.PO.Exposure
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.ConditionalExpectation

/-! # Cell-Level Potential Outcomes

This file defines `PanelPOSystem`, the bundled finite-panel
potential-outcomes system used by panel regression arguments. A system contains
observed weighted cells, a treatment-path random variable, cell-specific
exposure maps and baseline exposures, potential outcomes, and factual observed
outcomes.

The namespace also provides the realized exposure `observedExposure`, the
factual-outcome accessor `observedY`, the treatment-path sigma algebra
`DSigmaAlg`, the baseline conditional mean `m0`, the exposure response `tau`,
and the realized response `realizedTau`. -/

namespace Causalean
namespace Panel

open MeasureTheory

/-- Bundled data of a panel potential-outcomes system: observed cells with weights,
the treatment-path-valued random variable, the exposure mapping with a baseline, the
observed-cell-indexed family of potential outcomes, and independent factual outcomes. -/
structure PanelPOSystem where
  /-- Unit index type. -/
  I : Type*
  /-- Time index type. -/
  T : Type*
  [fintypeI : Fintype I]
  [fintypeT : Fintype T]
  [decI : DecidableEq I]
  [decT : DecidableEq T]
  /-- Observed unit-period cells with positive normalized weights. -/
  cells : Cells I T
  /-- Action type for treatment assignments. -/
  A : Type*
  /-- Observed-cell-indexed exposure set `E_r`. -/
  E : (r : I × T) → r ∈ cells.observed → Type*
  /-- Each observed-cell exposure set carries a measurable structure. -/
  [measE : ∀ r hr, MeasurableSpace (E r hr)]
  /-- Exposure mapping `e_r : (I → T → A) → E_r` for observed cells. -/
  e : ∀ r hr, TreatmentPath I T A → E r hr
  /-- Baseline exposure `e_r^0 ∈ E_r` for observed cells. -/
  e0 : ∀ r hr, E r hr
  /-- Sample space. -/
  Ω : Type*
  [measΩ : MeasurableSpace Ω]
  [measA : MeasurableSpace A]
  /-- Probability measure. -/
  μ : Measure Ω
  [probμ : IsProbabilityMeasure μ]
  /-- Treatment path random variable `D : Ω → I → T → A`. -/
  D : Ω → TreatmentPath I T A
  /-- `D` is measurable as a map into the function space.  Encoded
  cellwise: each `(D ·) i t : Ω → A` is measurable. -/
  D_meas : ∀ i t, Measurable (fun ω => D ω i t)
  /-- Cell-level potential outcome family `Y r e : Ω → ℝ` on observed cells. -/
  Y : (r : I × T) → (hr : r ∈ cells.observed) → E r hr → Ω → ℝ
  /-- Each potential outcome is measurable. -/
  Y_meas : ∀ r hr e, Measurable (Y r hr e)
  /-- Each potential outcome is integrable. -/
  Y_integrable : ∀ r hr e, Integrable (Y r hr e) μ
  /-- Factual observed outcome family on observed cells. -/
  Yobs : (r : I × T) → r ∈ cells.observed → Ω → ℝ
  /-- Each factual observed outcome is measurable. -/
  Yobs_meas : ∀ r hr, Measurable (Yobs r hr)
  /-- Each factual observed outcome is integrable. -/
  Yobs_integrable : ∀ r hr, Integrable (Yobs r hr) μ

attribute [instance] PanelPOSystem.fintypeI PanelPOSystem.fintypeT
  PanelPOSystem.decI PanelPOSystem.decT PanelPOSystem.measE
  PanelPOSystem.measΩ PanelPOSystem.measA PanelPOSystem.probμ

namespace PanelPOSystem

variable (P : PanelPOSystem)

/-- The realized exposure at an observed cell `r`: `E_r = e_r(D)`. -/
def observedExposure (r : P.I × P.T) (hr : r ∈ P.cells.observed) (ω : P.Ω) :
    P.E r hr :=
  P.e r hr (P.D ω)

/-- The factual observed outcome at an observed cell.  It is stored independently from
the potential-outcome schedule; the consistency assumption relates it to the potential
outcome at the realized exposure. -/
def observedY (r : P.I × P.T) (hr : r ∈ P.cells.observed) (ω : P.Ω) : ℝ :=
  P.Yobs r hr ω

/-- The σ-algebra generated by the treatment path `D`.  This is the
"information of the assignment vector" — the σ-algebra in `\bbE[· | D]`
of Definition 2.4. -/
def DSigmaAlg : MeasurableSpace P.Ω :=
  ⨆ (i : P.I) (t : P.T), MeasurableSpace.comap (fun ω => P.D ω i t) inferInstance

/-- `σ(D)` is a sub-σ-algebra of the ambient σ-algebra on `Ω`. -/
lemma DSigmaAlg_le : P.DSigmaAlg ≤ (inferInstance : MeasurableSpace P.Ω) := by
  rw [DSigmaAlg]
  exact iSup_le (fun i =>
    iSup_le (fun t => measurable_iff_comap_le.mp (P.D_meas i t)))

/-- Baseline conditional mean `m_r^0(D) := E[Y_r(e_r^0) | D]`. -/
noncomputable def m0 (r : P.I × P.T) (hr : r ∈ P.cells.observed) : P.Ω → ℝ :=
  MeasureTheory.condExp P.DSigmaAlg P.μ (P.Y r hr (P.e0 r hr))

/-- Cell-level exposure response
`τ_r(e | D) := E[Y_r(e) − Y_r(e_r^0) | D]`. -/
noncomputable def tau (r : P.I × P.T) (hr : r ∈ P.cells.observed)
    (e : P.E r hr) : P.Ω → ℝ :=
  MeasureTheory.condExp P.DSigmaAlg P.μ
    (fun ω => P.Y r hr e ω - P.Y r hr (P.e0 r hr) ω)

/-- The realized exposure response `τ_r(E_r | D)`, obtained by evaluating `tau`
at the exposure induced by the realized treatment path. -/
noncomputable def realizedTau (r : P.I × P.T) (hr : r ∈ P.cells.observed)
    (ω : P.Ω) : ℝ :=
  P.tau r hr (P.observedExposure r hr ω) ω

end PanelPOSystem

end Panel
end Causalean
