/- Barrel import for the theorem-specific helper split. -/
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.Spectral
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.Compactness
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.CovarianceHull
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.Separation
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.ExtremePoints
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.SimplexMinimax
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.AffineHull
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.GramDiagonal
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.LeverageProfile
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.OrbitReduction
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.BlockSpectrum
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.HomogeneousBlocks
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.RegretRepresentation
import CausalSmith.Experimentation.EXP_PrognosticDesignAdmissibility_Research.Helpers.FourUnit
