/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/
import Causalean.SCM.Do.Rule2
import Causalean.SCM.Do.Rule2Kernel.Structural.StructCrossSCM
import Causalean.SCM.Do.Rule2Kernel.Helpers
import Causalean.SCM.Do.Rule2Kernel.DiscreteZHelpers
import Causalean.SCM.Do.Rule3
import Causalean.SCM.Do.CutsetDSep
import Causalean.SCM.Do.GlobalMarkov
import Causalean.SCM.Model.CutsetLatent
import Causalean.SCM.Model.Kernel
import Causalean.Mathlib.CondDistrib
import Causalean.Mathlib.CondDistribWitness

/-!
# Cross-SCM `obsCondKernel` identity via the posterior witness kernel

This file isolates the genuinely-hard analytic step of the continuous-`Z`
Rule 2 (backdoor) argument and assembles the cross-SCM bridge
`obsCondKernel_fixSet_M1_eq_ae_product` around it.

## Posterior witness kernel

Both the obs-side and the do-side equal the **posterior** witness kernel

    `(condDistrib C_W (πW ∘ E) μ_lat).map (h t w)`

where `μ_lat = M.latentProduct`, `E = M.evalMap s`, `C_W = M.cutsetLatent Y (Zr∪W)`
is the latent cut-set, and `h` is the cut-set override map.  This is the law of
`Y | W` under the *posterior* of the cut-set given `W`, which — crucially —
respects the W–Y confounding allowed by the backdoor criterion.  (The old
`obsCondKernel_struct` route pushed the *prior* latent law forward, giving
`Y | do(C)`, which is wrong under confounding; that route is deleted.)

The spine is:

* `condDistrib_map_comp` (Mathlib helper): transport the obs-level
  `condDistrib π_Y π_{Zr∪W} (obsKernel s)` onto the latent space
  `latentProduct`, where `π ∘ E` are the pulled-back coordinate maps.
* `condDistrib_map_of_condDistrib_fst_eq` (witness lemma, `CondDistribWitness.lean`):
  given the pointwise factorization `Y = h X Z C` and the conditional
  independence `C ⊥ X | Z` (in `condDistrib`-equality form), it yields the
  posterior witness-kernel form of `condDistrib Y (X,Z)`.
* the do-side under `M2 := M'.fixSet Z` mirrors the obs-side (random `Zr` has no
  children in `M2`), and the two witness kernels are identified via
  `fixSet_latentProduct_compat` plus the `fillZrW` override agreement; positivity
  (Rule 3) transports onto the product `νZ ⊗ₘ μW`.

## Analytic cores

The construction is assembled from the following named lemmas:

* `cutset_factor_pointwise` — the pointwise factorization
  `π_Y ∘ E = h (π_Zr∘E) (π_W∘E) C_W`, together with the OFF-diagonal override
  characterization `h zr w' (π_{C_W} ℓ) = evalMap_overrideC … (valuesUnionMk zr w') ℓ`
  (needed do-side, where the treatment is pinned at `t` off the M1 diagonal).
* `cutset_condIndep_condDistrib` — the CI `C_W ⊥ (π_Zr∘E) | (π_W∘E)` under
  `latentProduct`, in the `condDistrib`-pair form the witness lemma consumes,
  from `cutsetLatent_dSep_of_dSep` + `full_globalMarkov_with_fixed`.
* `obsSide_eq_witness`, `doSide_eq_witness` — the two witness-kernel identities.
* `doSide_M2_pullback_eq_M1_witness` — the `fillZrW` cross-SCM identification of the
  `M2`-pullback `W`-conditional with the M1 witness kernel.  Closed via the no-X
  witness corollary `condDistrib_map_of_funext` (`Mathlib/CondDistribWitness.lean`)
  plus the override chain `evalMap_overrideC_at_self`@M2 →
  `evalMap_overrideC_dropZr_on_fillZrW` → `evalMap_overrideC_fixSet_compat_on_fillZrW`
  → the override characterization of `h`.
* `obsCondKernel_fixSet_M1_eq_ae_product` — the product-form connect + positivity
  transport (consumed by `condDistrib_fixSet_cross_SCM_bridge` in `Rule2AE`).
-/

namespace Causalean

variable {N : Type*} [DecidableEq N] [Fintype N]

namespace SCM

variable {Ω : N → Type*} [∀ n, MeasurableSpace (Ω n)]

open scoped MeasureTheory ProbabilityTheory

-- ============================================================
-- § Plumbing: measurability of a measure-valued agreement set
-- ============================================================

/-- **The agreement set of two measurable measure-valued maps is measurable.**

    If `f g : γ → Measure β` are measurable into the Giry monad, `β` is countably
    generated, and every `f p` is a finite measure, then the set
    `{p | f p = g p}` is measurable.  Two finite measures on a countably generated
    space are equal iff they agree on the (countable) π-system generated by the
    countable generating set together with `univ`; the agreement set is therefore a
    countable intersection of the measurable sets `{p | f p s = g p s}`. -/
theorem measurableSet_measure_eq
    {γ β : Type*} [MeasurableSpace γ] [MeasurableSpace β]
    [MeasurableSpace.CountablyGenerated β]
    {f g : γ → MeasureTheory.Measure β}
    (hf : Measurable f) (hg : Measurable g)
    (hf_fin : ∀ p, MeasureTheory.IsFiniteMeasure (f p)) :
    MeasurableSet {p | f p = g p} := by
  classical
  -- The countable π-system generated by `countableGeneratingSet β ∪ {univ}`.
  set C₀ : Set (Set β) :=
    MeasurableSpace.countableGeneratingSet β ∪ {Set.univ} with hC₀
  have hC₀_count : C₀.Countable :=
    MeasurableSpace.countable_countableGeneratingSet.union (Set.countable_singleton _)
  set C : Set (Set β) := generatePiSystem C₀ with hC
  -- Countability of the generated π-system (image of finite intersections).
  have hC_count : C.Countable := by
    have hsub : generatePiSystem C₀ ⊆
        (fun F : Finset (Set β) => ⋂₀ (F : Set (Set β))) '' {F : Finset (Set β) | ↑F ⊆ C₀} := by
      intro t ht
      induction ht with
      | base h_s => exact ⟨{_}, by simpa using h_s, by simp⟩
      | inter _ _ _ ihs ihu =>
          obtain ⟨Fs, hFs, rfl⟩ := ihs
          obtain ⟨Fu, hFu, rfl⟩ := ihu
          refine ⟨Fs ∪ Fu, ?_, ?_⟩
          · simp only [Set.mem_setOf_eq, Finset.coe_union, Set.union_subset_iff]
            exact ⟨hFs, hFu⟩
          · simp [Set.sInter_union]
    refine Set.Countable.mono hsub (Set.Countable.image ?_ _)
    haveI : Countable C₀ := hC₀_count.to_subtype
    have hr : {F : Finset (Set β) | ↑F ⊆ C₀} ⊆
        Set.range (fun (G : Finset C₀) => G.map (Function.Embedding.subtype _)) := by
      intro F hF
      refine ⟨F.subtype (· ∈ C₀), ?_⟩
      ext x
      simp only [Finset.mem_map, Finset.mem_subtype, Function.Embedding.coe_subtype]
      constructor
      · rintro ⟨a, ha, rfl⟩; exact ha
      · intro hx; exact ⟨⟨x, hF hx⟩, by simpa using hx, rfl⟩
    exact Set.Countable.mono hr (Set.countable_range _)
  have hC_pi : IsPiSystem C := isPiSystem_generatePiSystem _
  have hC_meas : ∀ s ∈ C, MeasurableSet s := by
    intro s hs
    refine generatePiSystem_measurableSet ?_ s hs
    intro t ht
    rcases ht with ht | ht
    · exact MeasurableSpace.measurableSet_countableGeneratingSet ht
    · rw [Set.mem_singleton_iff] at ht; exact ht ▸ MeasurableSet.univ
  have hUniv_C : Set.univ ∈ C :=
    subset_generatePiSystem_self _ (Or.inr rfl)
  have hgenC : (inferInstance : MeasurableSpace β) = MeasurableSpace.generateFrom C := by
    rw [hC, generateFrom_generatePiSystem_eq, hC₀, ← MeasurableSpace.generateFrom_sup_generateFrom,
      MeasurableSpace.generateFrom_countableGeneratingSet]
    have h1 : MeasurableSpace.generateFrom ({Set.univ} : Set (Set β)) = ⊥ :=
      MeasurableSpace.generateFrom_singleton_univ
    rw [h1, sup_bot_eq]
  -- Rewrite the agreement set as a countable intersection over `C`.
  have hset : {p | f p = g p} = ⋂ s ∈ C, {p | f p s = g p s} := by
    ext p
    simp only [Set.mem_setOf_eq, Set.mem_iInter]
    constructor
    · intro hp s _; rw [hp]
    · intro hp
      haveI := hf_fin p
      refine MeasureTheory.Measure.ext_of_generateFrom_of_iUnion C
        (fun _ => Set.univ) hgenC hC_pi ?_ (fun _ => hUniv_C) ?_ ?_
      · rw [Set.iUnion_const]
      · intro _; exact (MeasureTheory.measure_ne_top (f p) _)
      · intro s hs; exact hp s hs
  rw [hset]
  -- Each `{p | f p s = g p s}` is measurable; countable intersection.
  refine MeasurableSet.biInter hC_count (fun s hs => ?_)
  have hfs : Measurable (fun p => f p s) :=
    (MeasureTheory.Measure.measurable_coe (hC_meas s hs)).comp hf
  have hgs : Measurable (fun p => g p s) :=
    (MeasureTheory.Measure.measurable_coe (hC_meas s hs)).comp hg
  exact measurableSet_eq_fun hfs hgs

-- ============================================================
-- § Plumbing: `obsKernel s` as a latent pushforward
-- ============================================================

/-- **`obsKernel s` is the latent product pushed through `randomToObserved ∘ evalMap s`.**

    Folds `obsKernel = jointKernel.map randomToObserved` (`Kernel.obsKernel`) and
    `jointKernel s = latentProduct.map (evalMap s)` (`jointKernel_apply_eq`) into a
    single pushforward of `latentProduct`.  This is the form consumed by
    `condDistrib_map_comp` to move the obs-level conditional onto the latent
    space. -/
theorem obsKernel_eq_latentProduct_map (M : Causalean.SCM N Ω) (s : M.FixedValues) :
    M.obsKernel s
      = M.latentProduct.map (fun ℓ => M.randomToObserved (M.evalMap s ℓ)) := by
  have hev : Measurable (fun ℓ : M.LatentValues => M.evalMap s ℓ) := by
    have : M.evalMap s = fun ℓ => Function.uncurry M.evalMap (s, ℓ) := rfl
    rw [this]
    exact M.evalMap_measurable.comp (Measurable.prodMk measurable_const measurable_id)
  rw [obsKernel, ProbabilityTheory.Kernel.map_apply _ M.measurable_randomToObserved,
    jointKernel_apply_eq, MeasureTheory.Measure.map_map M.measurable_randomToObserved hev]
  rfl

/-- The pulled-back observed-coordinate projection through `randomToObserved ∘ evalMap s`
    is the latent projection of the evaluation, `valuesProjection hY ∘ randomToObserved ∘ E`.
    This is definitional unfolding, exposed so downstream `condDistrib_map_comp`
    rewrites can name the composite. -/
theorem valuesProjection_randomToObserved_evalMap_meas
    (M : Causalean.SCM N Ω) {Y : Finset (SWIGNode N)} (hY : Y ⊆ M.observed)
    (s : M.FixedValues) :
    Measurable (fun ℓ : M.LatentValues =>
        valuesProjection hY (M.randomToObserved (M.evalMap s ℓ))) := by
  have hev : Measurable (fun ℓ : M.LatentValues => M.evalMap s ℓ) := by
    have : M.evalMap s = fun ℓ => Function.uncurry M.evalMap (s, ℓ) := rfl
    rw [this]
    exact M.evalMap_measurable.comp (Measurable.prodMk measurable_const measurable_id)
  exact (measurable_valuesProjection hY).comp (M.measurable_randomToObserved.comp hev)

-- ============================================================
-- § The witness factorization map `h` and pointwise identity
-- ============================================================

/-- **Cut-set factorization, pointwise, at the realized override.**

    The evaluation projected to `Y` factors through the cut-set projection and the
    realized conditioning value: there is a measurable `h` (taking the
    `(Zr, W)`-conditioning value as its `(x, z)` arguments and the cut-set value as
    its `c` argument) with

      `π_Y (E ℓ) = h (π_Zr (E ℓ)) (π_W (E ℓ)) (π_{C_W} ℓ)`   for every `ℓ`.

    Combine `exists_evalMap_overrideC_factors_cutset` (for each fixed override `c`,
    a cut-set map `h_c` with `evalMap_overrideC … c = h_c ∘ π_{C_W}`) with
    `evalMap_overrideC_at_self` (at `c = π_C (E ℓ)`, the override equals the real
    `E`), so `h (x, z) cw := h_{fill(x,z)} cw`.

    The canonical `h` is the override map `h x z c := evalMap_overrideC … s
    (valuesUnionMk x z) (extendCutset c)`; its joint measurability comes from
    `measurable_evalMap_overrideC`.  Besides the realized-`s` factorization, `h`
    satisfies an OFF-diagonal override characterization (`hoverride`): for any
    override block `(zr, w')` and any latent `ℓ`, `h zr w' (π_{C_W} ℓ) =
    evalMap_overrideC … s (valuesUnionMk zr w') ℓ`.  This pins `h` off the
    realized-`s` diagonal, which the do-side bridge needs (its treatment
    coordinate is held at `t`, off the M1 diagonal). -/
theorem cutset_factor_pointwise (M : Causalean.SCM N Ω)
    [∀ n, Nonempty (Ω n)]
    (Y W : Finset (SWIGNode N)) (Z : Finset N)
    (hY : Y ⊆ M.observed)
    (hZr : Z.image SWIGNode.random ⊆ M.observed)
    (hW : W ⊆ M.observed)
    (hZrW : Z.image SWIGNode.random ∪ W ⊆ M.observed)
    (s : M.FixedValues) :
    ∃ h : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) → ValuesOn W (swigΩ Ω)
            → ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω)
            → ValuesOn Y (swigΩ Ω),
      Measurable (fun p :
          (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
            × ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
          h p.1.1 p.1.2 p.2) ∧
      (∀ ℓ : M.LatentValues,
        valuesProjection hY (M.randomToObserved (M.evalMap s ℓ))
          = h (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)))
              (valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
              (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)) ℓ)) ∧
      -- Override-form characterization: `h` evaluated at the cut-set projection of
      -- *any* latent `ℓ` equals the override map at that `ℓ` with override block
      -- `(zr, w')`.  This pins `h` OFF the realized-`s` diagonal — needed do-side,
      -- where the treatment coordinate is fixed at `t` (off the M1 diagonal).
      (∀ (zr : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω)) (w' : ValuesOn W (swigΩ Ω))
          (ℓ : M.LatentValues),
        h zr w'
            (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)) ℓ)
          = M.evalMap_overrideC hY hZrW s (valuesUnionMk zr w') ℓ) := by
  classical
  set C := Z.image SWIGNode.random ∪ W with hC_def
  set CW := M.cutsetLatent Y C with hCW_def
  have hCWsub : CW ⊆ M.unobserved := M.cutsetLatent_subset Y C
  -- Default latent vector for filling non-cutset coords.
  have hNEΩ : ∀ w : SWIGNode N, Nonempty (swigΩ Ω w) := by
    intro w; cases w <;> exact inferInstance
  let ℓ₀ : M.LatentValues := fun u => (hNEΩ u.val).some
  -- The measurable section restoring the cutset coordinates.
  let extendCutset : ValuesOn CW (swigΩ Ω) → M.LatentValues :=
    fun cwProj u => if h : u.val ∈ CW then cwProj ⟨u.val, h⟩ else ℓ₀ u
  have hext_meas : Measurable extendCutset := by
    refine measurable_pi_lambda _ (fun u => ?_)
    by_cases h : u.val ∈ CW
    · have : (fun cwProj : ValuesOn CW (swigΩ Ω) => extendCutset cwProj u)
          = fun cwProj => cwProj ⟨u.val, h⟩ := by funext cwProj; simp [extendCutset, h]
      rw [this]; exact measurable_pi_apply _
    · have : (fun cwProj : ValuesOn CW (swigΩ Ω) => extendCutset cwProj u)
          = fun _ => ℓ₀ u := by funext cwProj; simp [extendCutset, h]
      rw [this]; exact measurable_const
  -- The section restores cutset coordinates.
  have hext_restore : ∀ cwProj : ValuesOn CW (swigΩ Ω),
      valuesProjection hCWsub (extendCutset cwProj) = cwProj := by
    intro cwProj; funext u
    simp only [valuesProjection, extendCutset, dif_pos u.property]
  refine ⟨fun zr w c => M.evalMap_overrideC hY hZrW s (valuesUnionMk zr w) (extendCutset c),
    ?_, ?_, ?_⟩
  · -- Joint measurability via `measurable_evalMap_overrideC`.
    have hcomp :
        (fun p :
            (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
              × ValuesOn CW (swigΩ Ω) =>
            M.evalMap_overrideC hY hZrW s (valuesUnionMk p.1.1 p.1.2) (extendCutset p.2))
          =
        (fun q : (M.FixedValues × ValuesOn C (swigΩ Ω)) × M.LatentValues =>
            M.evalMap_overrideC hY hZrW q.1.1 q.1.2 q.2)
          ∘ (fun p => ((s, valuesUnionMk p.1.1 p.1.2), extendCutset p.2)) := by
      funext p; rfl
    rw [hcomp]
    refine (measurable_evalMap_overrideC M hY hZrW).comp ?_
    refine Measurable.prodMk ?_ (hext_meas.comp measurable_snd)
    refine measurable_const.prodMk ?_
    exact measurable_valuesUnionMk.comp measurable_fst
  · -- Factorization at the realized point.
    intro ℓ
    set E := M.randomToObserved (M.evalMap s ℓ) with hE_def
    -- (a) valuesUnionMk of the two projections of E equals the (Zr∪W)-projection of E.
    have ha : valuesUnionMk (valuesProjection hZr E) (valuesProjection hW E)
        = valuesProjection hZrW E := by
      funext ⟨v, hv⟩
      by_cases hvZr : v ∈ Z.image SWIGNode.random
      · rw [valuesUnionMk_apply_left _ _ hv hvZr]; rfl
      · have hvW : v ∈ W := (Finset.mem_union.mp hv).resolve_left hvZr
        rw [valuesUnionMk_apply_right _ _ hv hvZr hvW]; rfl
    -- (b) override agrees with `ℓ` after the cutset section, by cutset agreement.
    have hb : M.evalMap_overrideC hY hZrW s (valuesProjection hZrW E)
                (extendCutset (valuesProjection hCWsub ℓ))
            = M.evalMap_overrideC hY hZrW s (valuesProjection hZrW E) ℓ := by
      refine evalMap_overrideC_agree_cutset M hY hZrW s _ _ _ ?_
      rw [hext_restore]
    -- (c) the override at its "self" C-value equals the real eval on Y.
    have hc : M.evalMap_overrideC hY hZrW s (valuesProjection hZrW E) ℓ
            = valuesProjection hY E := by
      -- Both sides are the (cast-transported) `evalObservedAux` at observed nodes.
      have hself : valuesProjection hZrW E
          = (fun v' : {v // v ∈ C} =>
              (M.observedAt_observedIndex ⟨v'.val, hZrW v'.property⟩) ▸
                evalObservedAux M s ℓ
                  (M.observedIndex ⟨v'.val, hZrW v'.property⟩).val
                  (M.observedIndex ⟨v'.val, hZrW v'.property⟩).isLt) := by
        funext v'
        change E ⟨v'.val, hZrW v'.property⟩ = _
        change M.evalMap s ℓ ⟨v'.val, _⟩ = _
        rw [M.evalMap_observed s ℓ _ (hZrW v'.property)]
      rw [hself, M.evalMap_overrideC_at_self hY hZrW s ℓ]
      funext v
      change _ = E ⟨v.val, hY v.property⟩
      change _ = M.evalMap s ℓ ⟨v.val, _⟩
      rw [M.evalMap_observed s ℓ _ (hY v.property)]
    -- Assemble.
    calc valuesProjection hY E
        = M.evalMap_overrideC hY hZrW s (valuesProjection hZrW E) ℓ := hc.symm
      _ = M.evalMap_overrideC hY hZrW s (valuesProjection hZrW E)
            (extendCutset (valuesProjection hCWsub ℓ)) := hb.symm
      _ = M.evalMap_overrideC hY hZrW s
            (valuesUnionMk (valuesProjection hZr E) (valuesProjection hW E))
            (extendCutset (valuesProjection hCWsub ℓ)) := by rw [ha]
  · -- Override-form characterization (off-diagonal pinning of `h`).
    -- `h zr w' (π_{C_W} ℓ) = override (valuesUnionMk zr w') (extendCutset (π_{C_W} ℓ))`,
    -- and the override depends on the latent only through the cut-set projection,
    -- so we may replace `extendCutset (π_{C_W} ℓ)` by `ℓ` itself.
    intro zr w' ℓ
    change M.evalMap_overrideC hY hZrW s (valuesUnionMk zr w')
        (extendCutset (valuesProjection hCWsub ℓ))
      = M.evalMap_overrideC hY hZrW s (valuesUnionMk zr w') ℓ
    refine evalMap_overrideC_agree_cutset M hY hZrW s _ _ _ ?_
    rw [hext_restore]

-- ============================================================
-- § Conditional independence of the cut-set, condDistrib form
-- ============================================================

/-- **Cut-set conditional independence, in `condDistrib`-pair form.**

    Under `latentProduct`, the cut-set `C_W = cutsetLatent Y (Zr∪W)` is
    conditionally independent of the (pulled-back) treatment coordinate
    `X = π_Zr ∘ E` given the conditioning coordinate `Z = π_W ∘ E`:

      `condDistrib C_W (X, Z) latentProduct =ᵐ condDistrib C_W Z latentProduct ∘ snd`.

    This is the form `condDistrib_map_of_condDistrib_fst_eq` consumes.  Derivation:
    `cutsetLatent_dSep_of_dSep` gives the graph d-sep `C_W ⊥ Zr | (W ∪ fixed)`;
    `full_globalMarkov_with_fixed` turns it into `FullCondIndep` (= `CondIndepFun`
    under `jointKernel s`); since `jointKernel s = latentProduct.map (evalMap s)`,
    `CondIndepFun` transfers to `latentProduct` for the pulled-back coordinates;
    finally `condIndepFun_iff_condDistrib_prod_ae_eq_prodMkRight` rewrites
    `CondIndepFun` into the `condDistrib`-pair equality.

    The proof packages the chain
    `FullCondIndep(jointKernel) → CondIndepFun(latentProduct, pulled-back coords)
    → condDistrib-pair form`, including the coordinate-order rewrite from
    `prodMkRight`/`prodMkLeft` to the witness lemma's `(X, Z) → Z` shape. -/
theorem cutset_condIndep_condDistrib (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.jointKernel s)]
    (Y W : Finset (SWIGNode N)) (Z : Finset N)
    [StandardBorelSpace (ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty (ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    (hZr : Z.image SWIGNode.random ⊆ M.observed)
    (hW : W ⊆ M.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hdSepCW : M.dag.dSep (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W))
      (Z.image SWIGNode.random) (W ∪ M.fixed))
    (s : M.FixedValues) :
    (fun p : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω) =>
        ProbabilityTheory.condDistrib
          (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
          (fun ℓ : M.LatentValues =>
            (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)),
             valuesProjection hW (M.randomToObserved (M.evalMap s ℓ))))
          M.latentProduct p)
      =ᵐ[M.latentProduct.map (fun ℓ : M.LatentValues =>
          (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)),
           valuesProjection hW (M.randomToObserved (M.evalMap s ℓ))))]
        (fun p =>
          ProbabilityTheory.condDistrib
            (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
            (fun ℓ : M.LatentValues =>
              valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
            M.latentProduct p.2) := by
  classical
  set Zr := Z.image SWIGNode.random with hZr_def
  set CW := M.cutsetLatent Y (Zr ∪ W) with hCW_def
  have hCWsub : CW ⊆ M.unobserved := M.cutsetLatent_subset Y (Zr ∪ W)
  -- Subset facts into `randomVars`.
  have hobs_rv : M.observed ⊆ M.randomVars := by
    intro v hv; exact Finset.mem_union_left _ hv
  have hunobs_rv : M.unobserved ⊆ M.randomVars := by
    intro v hv; exact Finset.mem_union_right _ hv
  have hZr_rv : Zr ⊆ M.randomVars := hZr.trans hobs_rv
  have hW_rv : W ⊆ M.randomVars := hW.trans hobs_rv
  have hCW_rv : CW ⊆ M.randomVars := hCWsub.trans hunobs_rv
  -- Bridge: for an observed set `D`, projecting `randomToObserved (evalMap s ℓ)`
  -- equals projecting `evalMap s ℓ` directly (same underlying values).
  have hbridge_obs : ∀ {D : Finset (SWIGNode N)} (hD : D ⊆ M.observed)
      (hD_rv : D ⊆ M.randomVars) (ℓ : M.LatentValues),
      valuesProjection hD (M.randomToObserved (M.evalMap s ℓ))
        = valuesProjection hD_rv (M.evalMap s ℓ) := by
    intro D hD hD_rv ℓ; funext v; rfl
  -- Bridge: for the latent cutset, projecting `evalMap s ℓ` equals projecting `ℓ`.
  have hbridge_lat : ∀ ℓ : M.LatentValues,
      valuesProjection hCW_rv (M.evalMap s ℓ) = valuesProjection hCWsub ℓ := by
    intro ℓ; funext v
    change M.evalMap s ℓ ⟨v.val, hCW_rv v.property⟩ = ℓ ⟨v.val, hCWsub v.property⟩
    rw [M.evalMap_unobserved s ℓ _ (hCWsub v.property)]
  -- Measurability of the pulled-back coordinate maps (as compositions with evalMap s).
  have hev : Measurable (fun ℓ : M.LatentValues => M.evalMap s ℓ) := by
    have : M.evalMap s = fun ℓ => Function.uncurry M.evalMap (s, ℓ) := rfl
    rw [this]
    exact M.evalMap_measurable.comp (Measurable.prodMk measurable_const measurable_id)
  -- Abbreviations for the pulled-back coordinate maps.
  set Xmap : M.LatentValues → ValuesOn Zr (swigΩ Ω) :=
    fun ℓ => valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)) with hX_def
  set Zmap : M.LatentValues → ValuesOn W (swigΩ Ω) :=
    fun ℓ => valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)) with hZmap_def
  set Cmap : M.LatentValues → ValuesOn CW (swigΩ Ω) :=
    valuesProjection hCWsub with hC_def
  have hXmeas : Measurable Xmap :=
    (measurable_valuesProjection hZr).comp (M.measurable_randomToObserved.comp hev)
  have hZmeas : Measurable Zmap :=
    (measurable_valuesProjection hW).comp (M.measurable_randomToObserved.comp hev)
  have hCmeas : Measurable Cmap := measurable_valuesProjection hCWsub
  -- Step 1: cutset graph d-sep is now a direct hypothesis; global Markov
  -- (FullCondIndep under jointKernel) follows.  (Previously derived internally
  -- via `cutsetLatent_dSep_of_dSep` from `dSep Y Zr`, which is FALSE at M1; the
  -- cutset d-sep `dSep C_W Zr` is the satisfiable input and is threaded directly.)
  have hdSepCW : M.dag.dSep CW Zr (W ∪ M.fixed) := hdSepCW
  have hDisj_CWZr : Disjoint CW Zr := by
    rw [Finset.disjoint_left]; intro a haCW haZr
    exact M.not_obs_of_unobs (hCWsub haCW) (hZr haZr)
  have hDisj_CWW : Disjoint CW W := by
    rw [Finset.disjoint_left]; intro a haCW haW
    exact M.not_obs_of_unobs (hCWsub haCW) (hW haW)
  have hFCI : FullCondIndep M CW Zr W hCW_rv hZr_rv hW_rv (M.jointKernel s) :=
    full_globalMarkov_with_fixed M CW Zr W M.fixed hCW_rv hZr_rv hW_rv (Finset.Subset.refl _)
      hDisj_CWZr hDisj_CWW hDisj_ZrW hdSepCW s
  -- `Zr ⟂ CW | W` form (swap X↔Y), which the Mathlib iff consumes as `g ⟂ᵢ[k] f`.
  have hFCI_symm : FullCondIndep M Zr CW W hZr_rv hCW_rv hW_rv (M.jointKernel s) :=
    fullCondIndep_symm M hCW_rv hZr_rv hW_rv hFCI
  haveI : MeasureTheory.IsProbabilityMeasure M.latentProduct := inferInstance
  -- Measurability of the `valuesProjection` maps on `RandomValues`.
  have hCW_proj_meas : Measurable (valuesProjection (Ω := swigΩ Ω) hCW_rv) :=
    measurable_valuesProjection hCW_rv
  have hZr_proj_meas : Measurable (valuesProjection (Ω := swigΩ Ω) hZr_rv) :=
    measurable_valuesProjection hZr_rv
  have hW_proj_meas : Measurable (valuesProjection (Ω := swigΩ Ω) hW_rv) :=
    measurable_valuesProjection hW_rv
  -- Step 2: Mathlib iff turns `FullCondIndep` into a condDistrib-pair equality
  -- under `jointKernel s`, conditioning on the pair `(W, Zr)`.
  have hCI_joint :
      (fun p => ProbabilityTheory.condDistrib (valuesProjection hCW_rv)
          (fun ξ => (valuesProjection hW_rv ξ, valuesProjection hZr_rv ξ)) (M.jointKernel s) p)
        =ᵐ[(M.jointKernel s).map
            (fun ξ => (valuesProjection hW_rv ξ, valuesProjection hZr_rv ξ))]
          (fun p => ((ProbabilityTheory.condDistrib (valuesProjection hCW_rv)
              (valuesProjection hW_rv) (M.jointKernel s)).prodMkRight _) p) := by
    have := (ProbabilityTheory.condIndepFun_iff_condDistrib_prod_ae_eq_prodMkRight
      (μ := M.jointKernel s) (f := valuesProjection hCW_rv) (g := valuesProjection hZr_rv)
      (k := valuesProjection hW_rv) hCW_proj_meas hZr_proj_meas hW_proj_meas).mp hFCI_symm
    exact this
  -- The two coordinate maps on `RandomValues`, and their compositions with `evalMap s`.
  set Wmap_rv : M.RandomValues → ValuesOn W (swigΩ Ω) := valuesProjection hW_rv with hWmap_rv
  set Zrmap_rv : M.RandomValues → ValuesOn Zr (swigΩ Ω) := valuesProjection hZr_rv with hZrmap_rv
  set CWmap_rv : M.RandomValues → ValuesOn CW (swigΩ Ω) := valuesProjection hCW_rv with hCWmap_rv
  set pairWZr : M.RandomValues → ValuesOn W (swigΩ Ω) × ValuesOn Zr (swigΩ Ω) :=
    fun ξ => (Wmap_rv ξ, Zrmap_rv ξ) with hpairWZr
  have hpairWZr_meas : Measurable pairWZr := hW_proj_meas.prodMk hZr_proj_meas
  -- Rewrite `jointKernel s` as the pushforward of `latentProduct`.
  have hjk : M.jointKernel s = M.latentProduct.map (fun ℓ => M.evalMap s ℓ) :=
    jointKernel_apply_eq M s
  simp only [hjk] at hCI_joint
  -- Compositions with `evalMap s` reduce to `Zmap`, `Xmap`, `Cmap`.
  have hcomp_pair : pairWZr ∘ (fun ℓ => M.evalMap s ℓ) = fun ℓ => (Zmap ℓ, Xmap ℓ) := by
    funext ℓ
    simp only [hpairWZr, hWmap_rv, hZrmap_rv, Function.comp_apply, hZmap_def, hX_def]
    rw [hbridge_obs hW hW_rv ℓ, hbridge_obs hZr hZr_rv ℓ]
  have hcomp_W : Wmap_rv ∘ (fun ℓ => M.evalMap s ℓ) = Zmap := by
    funext ℓ; simp only [hWmap_rv, Function.comp_apply, hZmap_def]
    rw [hbridge_obs hW hW_rv ℓ]
  have hcomp_CW : CWmap_rv ∘ (fun ℓ => M.evalMap s ℓ) = Cmap := by
    funext ℓ
    change CWmap_rv (M.evalMap s ℓ) = Cmap ℓ
    rw [hbridge_lat ℓ]
  -- Transfer the pair-conditioned `condDistrib` onto `latentProduct`.
  have htr_pair := condDistrib_map_comp (𝒴 := ValuesOn CW (swigΩ Ω)) M.latentProduct
    (φ := fun ℓ => M.evalMap s ℓ) (g := CWmap_rv) (f := pairWZr)
    hev hCW_proj_meas hpairWZr_meas
  have htr_W := condDistrib_map_comp (𝒴 := ValuesOn CW (swigΩ Ω)) M.latentProduct
    (φ := fun ℓ => M.evalMap s ℓ) (g := CWmap_rv) (f := Wmap_rv)
    hev hCW_proj_meas hW_proj_meas
  -- The `(W, Zr)`-ordered latent pair map and its marginal measure facts.
  set pairWZr_lat : M.LatentValues → ValuesOn W (swigΩ Ω) × ValuesOn Zr (swigΩ Ω) :=
    fun ℓ => (Zmap ℓ, Xmap ℓ) with hpairWZr_lat
  have hpairWZr_lat_meas : Measurable pairWZr_lat := hZmeas.prodMk hXmeas
  -- Push `htr_pair`/`htr_W`/`hCI_joint` filters into `LP.map (·∘E)` form.
  rw [MeasureTheory.Measure.map_map hpairWZr_meas hev, hcomp_pair, hcomp_CW]
    at htr_pair
  rw [MeasureTheory.Measure.map_map hpairWZr_meas hev, hcomp_pair] at hCI_joint
  rw [MeasureTheory.Measure.map_map hW_proj_meas hev, hcomp_W, hcomp_CW] at htr_W
  -- `htr_pair` now: condDistrib CWmap_rv pairWZr (LP.map E) =ᵐ[LP.map pairWZr_lat]
  --                condDistrib Cmap pairWZr_lat LP
  -- `hCI_joint` now RHS uses prodMkRight of condDistrib CWmap_rv Wmap_rv (LP.map E).
  -- Reduce prodMkRight to evaluation at `.1`.
  have hCI_joint' :
      (fun p => ProbabilityTheory.condDistrib CWmap_rv pairWZr
          (M.latentProduct.map (fun ℓ => M.evalMap s ℓ)) p)
        =ᵐ[M.latentProduct.map pairWZr_lat]
          (fun p => ProbabilityTheory.condDistrib CWmap_rv Wmap_rv
            (M.latentProduct.map (fun ℓ => M.evalMap s ℓ)) p.1) := by
    filter_upwards [hCI_joint] with p hp
    rw [hp, ProbabilityTheory.Kernel.prodMkRight_apply]
  -- Lift `htr_W` from the `W`-marginal to the pair-marginal along `Prod.fst`.
  have htr_W_fst :
      (fun p => ProbabilityTheory.condDistrib CWmap_rv Wmap_rv
          (M.latentProduct.map (fun ℓ => M.evalMap s ℓ)) p.1)
        =ᵐ[M.latentProduct.map pairWZr_lat]
          (fun p : ValuesOn W (swigΩ Ω) × ValuesOn Zr (swigΩ Ω) =>
            ProbabilityTheory.condDistrib Cmap Zmap M.latentProduct p.1) := by
    have hfst_marg : (M.latentProduct.map pairWZr_lat).map Prod.fst
        = M.latentProduct.map Zmap := by
      rw [MeasureTheory.Measure.map_map measurable_fst hpairWZr_lat_meas]; rfl
    have := MeasureTheory.ae_eq_comp (μ := M.latentProduct.map pairWZr_lat)
      (f := Prod.fst) (g := fun q => ProbabilityTheory.condDistrib CWmap_rv Wmap_rv
        (M.latentProduct.map (fun ℓ => M.evalMap s ℓ)) q)
      (g' := fun q => ProbabilityTheory.condDistrib Cmap Zmap M.latentProduct q)
      measurable_fst.aemeasurable (by rw [hfst_marg]; exact htr_W)
    exact this
  -- Assemble the `(W, Zr)`-ordered equality on `LP.map pairWZr_lat`.
  have keyWZr :
      (fun p => ProbabilityTheory.condDistrib Cmap pairWZr_lat M.latentProduct p)
        =ᵐ[M.latentProduct.map pairWZr_lat]
          (fun p : ValuesOn W (swigΩ Ω) × ValuesOn Zr (swigΩ Ω) =>
            ProbabilityTheory.condDistrib Cmap Zmap M.latentProduct p.1) :=
    (htr_pair.symm.trans hCI_joint').trans htr_W_fst
  -- Swap `(W, Zr)` to `(Zr, W)` via the product-comm measurable equivalence.
  set e : (ValuesOn W (swigΩ Ω) × ValuesOn Zr (swigΩ Ω)) ≃ᵐ
      (ValuesOn Zr (swigΩ Ω) × ValuesOn W (swigΩ Ω)) := MeasurableEquiv.prodComm with he_def
  have hpair_swap : (fun ℓ => (Xmap ℓ, Zmap ℓ)) = e ∘ pairWZr_lat := by
    funext ℓ; rfl
  -- `condDistrib Cmap (e ∘ pairWZr_lat) LP (e p) = condDistrib Cmap pairWZr_lat LP p`, a.e.
  have hreparam := condDistrib_comp_right_measurableEquiv (μ := M.latentProduct)
    (Y := Cmap) (X := pairWZr_lat) e hCmeas hpairWZr_lat_meas
  -- Transport the goal (over `LP.map (Xmap, Zmap) = (LP.map pairWZr_lat).map e`) to `keyWZr`.
  have hmap_e : M.latentProduct.map (fun ℓ => (Xmap ℓ, Zmap ℓ))
      = (M.latentProduct.map pairWZr_lat).map e := by
    rw [hpair_swap, ← MeasureTheory.Measure.map_map e.measurable hpairWZr_lat_meas]
  -- Final: rewrite the goal's conditioning into `Xmap`/`Zmap`, then chain.
  change (fun p => ProbabilityTheory.condDistrib Cmap (fun ℓ => (Xmap ℓ, Zmap ℓ))
        M.latentProduct p)
      =ᵐ[M.latentProduct.map (fun ℓ => (Xmap ℓ, Zmap ℓ))]
        (fun p => ProbabilityTheory.condDistrib Cmap Zmap M.latentProduct p.2)
  rw [hmap_e]
  -- On `(LP.map pairWZr_lat).map e`, pull back along the measurable embedding `e`.
  rw [Filter.EventuallyEq, e.measurableEmbedding.ae_map_iff]
  filter_upwards [keyWZr, hreparam] with p hkey hrep
  -- LHS at `e p`: condDistrib Cmap (Xmap,Zmap) LP (e p) = condDistrib Cmap pairWZr_lat LP p.
  have hLHS : ProbabilityTheory.condDistrib Cmap (fun ℓ => (Xmap ℓ, Zmap ℓ))
        M.latentProduct (e p)
      = ProbabilityTheory.condDistrib Cmap pairWZr_lat M.latentProduct p := by
    rw [hpair_swap]; exact hrep
  change ProbabilityTheory.condDistrib Cmap (fun ℓ => (Xmap ℓ, Zmap ℓ)) M.latentProduct (e p)
      = ProbabilityTheory.condDistrib Cmap Zmap M.latentProduct (e p).2
  rw [hLHS, hkey]
  -- RHS: `condDistrib Cmap Zmap LP p.1 = condDistrib Cmap Zmap LP (e p).2`.
  rfl

-- ============================================================
-- § Obs-side: `condDistrib π_Y (π_Zr, π_W) (latentProduct)` = witness kernel
-- ============================================================

/-- **Obs-side witness-kernel identity (pair-conditioned, on the latent space).**

    Under `latentProduct`, the conditional law of `Y` given the pair
    `(π_Zr ∘ E, π_W ∘ E)` is the posterior witness kernel
    `(condDistrib C_W (π_W∘E) latentProduct).map (h x z)`.  This is a direct
    application of the witness lemma `condDistrib_map_of_condDistrib_fst_eq` with
    the cut-set factorization `cutset_factor_pointwise` and the conditional
    independence `cutset_condIndep_condDistrib`. -/
theorem obsSide_eq_witness (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.jointKernel s)]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.obsKernel s)]
    (Y W : Finset (SWIGNode N)) (Z : Finset N)
    [StandardBorelSpace (ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty (ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))] [Nonempty (ValuesOn Y (swigΩ Ω))]
    (hY : Y ⊆ M.observed)
    (hZr : Z.image SWIGNode.random ⊆ M.observed)
    (hW : W ⊆ M.observed)
    (_hZrW : Z.image SWIGNode.random ∪ W ⊆ M.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hdSepCW : M.dag.dSep (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W))
      (Z.image SWIGNode.random) (W ∪ M.fixed))
    (s : M.FixedValues)
    (h : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) → ValuesOn W (swigΩ Ω)
            → ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω)
            → ValuesOn Y (swigΩ Ω))
    (hh : Measurable (fun p :
        (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
          × ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
        h p.1.1 p.1.2 p.2))
    (hfac : ∀ ℓ : M.LatentValues,
        valuesProjection hY (M.randomToObserved (M.evalMap s ℓ))
          = h (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)))
              (valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
              (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)) ℓ)) :
    (fun p : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω) =>
        ProbabilityTheory.condDistrib
          (fun ℓ : M.LatentValues =>
            valuesProjection hY (M.randomToObserved (M.evalMap s ℓ)))
          (fun ℓ : M.LatentValues =>
            (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)),
             valuesProjection hW (M.randomToObserved (M.evalMap s ℓ))))
          M.latentProduct p)
      =ᵐ[M.latentProduct.map (fun ℓ : M.LatentValues =>
          (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)),
           valuesProjection hW (M.randomToObserved (M.evalMap s ℓ))))]
        (fun p =>
          (ProbabilityTheory.condDistrib
            (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
            (fun ℓ : M.LatentValues =>
              valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
            M.latentProduct p.2).map (h p.1 p.2)) := by
  haveI : MeasureTheory.IsProbabilityMeasure M.latentProduct := inferInstance
  have hX : Measurable (fun ℓ : M.LatentValues =>
      valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ))) :=
    M.valuesProjection_randomToObserved_evalMap_meas hZr s
  have hZmeas : Measurable (fun ℓ : M.LatentValues =>
      valuesProjection hW (M.randomToObserved (M.evalMap s ℓ))) :=
    M.valuesProjection_randomToObserved_evalMap_meas hW s
  have hCmeas : Measurable
      (valuesProjection (Ω := swigΩ Ω)
        (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W))) :=
    measurable_valuesProjection _
  -- The witness lemma's `Y = h X Z C` pointwise (from `hfac`).
  have hY_eq : (fun ℓ : M.LatentValues =>
        valuesProjection hY (M.randomToObserved (M.evalMap s ℓ)))
      = fun ℓ => h
          (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)))
          (valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
          (valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)) ℓ) :=
    funext hfac
  have hwit := ProbabilityTheory.condDistrib_map_of_condDistrib_fst_eq
    (Ω := M.LatentValues)
    (𝒳 := ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
    (𝒵 := ValuesOn W (swigΩ Ω))
    (𝒞 := ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))
    (𝒴 := ValuesOn Y (swigΩ Ω))
    (μ := M.latentProduct)
    (X := fun ℓ => valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)))
    (Z := fun ℓ => valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
    (C := valuesProjection (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
    (h := h)
    hX hZmeas hCmeas hh
    (cutset_condIndep_condDistrib M Y W Z hZr hW hDisj_ZrW hdSepCW s)
  -- `hwit` conditions `condDistrib (fun ℓ => h (X ℓ)(Z ℓ)(C ℓ)) ...`; rewrite via `hY_eq`.
  rw [hY_eq]
  exact hwit

/-- **The `(Zr∪W)`-conditional packaged as the witness kernel.**

    For any model `M`, the observational conditional of `Y` given the union block
    `Zr∪W` is, `μ_C`-a.e. (μ_C the `(Zr∪W)`-marginal of `obsKernel s`), the posterior
    witness kernel evaluated at the `(Zr, W)`-split of the conditioning value.
    Assembled from `obsCondKernel_ae_eq_condDistrib` (obsCondKernel ↔ condDistrib),
    `condDistrib_map_comp` (transport onto `latentProduct`),
    `condDistrib_comp_right_measurableEquiv` with `valuesUnionEquiv` (re-split the
    union conditioning into the pair), and `obsSide_eq_witness` (the witness
    identity). -/
theorem obsCondKernel_union_eq_witness (M : Causalean.SCM N Ω)
    [StandardBorelSpace M.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.jointKernel s)]
    [∀ s : M.FixedValues, MeasureTheory.IsFiniteMeasure (M.obsKernel s)]
    (Y W : Finset (SWIGNode N)) (Z : Finset N)
    [StandardBorelSpace
      (ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty (ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))] [Nonempty (ValuesOn Y (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated M.FixedValues
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    (hY : Y ⊆ M.observed)
    (hZr : Z.image SWIGNode.random ⊆ M.observed)
    (hW : W ⊆ M.observed)
    (hZrW : Z.image SWIGNode.random ∪ W ⊆ M.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hdSepCW : M.dag.dSep (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W))
      (Z.image SWIGNode.random) (W ∪ M.fixed))
    (s : M.FixedValues)
    (h : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) → ValuesOn W (swigΩ Ω)
            → ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω)
            → ValuesOn Y (swigΩ Ω))
    (hh : Measurable (fun p :
        (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
          × ValuesOn (M.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
        h p.1.1 p.1.2 p.2))
    (hfac : ∀ ℓ : M.LatentValues,
        valuesProjection hY (M.randomToObserved (M.evalMap s ℓ))
          = h (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)))
              (valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
              (valuesProjection (M.cutsetLatent_subset Y
                (Z.image SWIGNode.random ∪ W)) ℓ)) :
    (fun c => M.obsCondKernel Y (Z.image SWIGNode.random ∪ W) hY hZrW (s, c))
      =ᵐ[(M.obsKernel s).map (valuesProjection hZrW)]
        (fun c =>
          ((ProbabilityTheory.condDistrib
              (valuesProjection
                (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
              (fun ℓ : M.LatentValues =>
                valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
              M.latentProduct)
            (valuesProjection (Finset.subset_union_right) c)).map
            (h (valuesProjection (Finset.subset_union_left) c)
               (valuesProjection (Finset.subset_union_right) c))) := by
  classical
  -- Abbreviations: the observed-eval pullback `E` and the conditioning maps.
  set E : M.LatentValues → M.ObservedValues :=
    fun ℓ => M.randomToObserved (M.evalMap s ℓ) with hE_def
  have hEmeas : Measurable E :=
    M.measurable_randomToObserved.comp (by
      have : (fun ℓ : M.LatentValues => M.evalMap s ℓ)
          = fun ℓ => Function.uncurry M.evalMap (s, ℓ) := rfl
      rw [show E = M.randomToObserved ∘ (fun ℓ => M.evalMap s ℓ) from rfl] at *
      exact M.evalMap_measurable.comp (measurable_const.prodMk measurable_id))
  have hπY : Measurable (valuesProjection (Ω := swigΩ Ω) hY) :=
    measurable_valuesProjection hY
  have hπZrW : Measurable (valuesProjection (Ω := swigΩ Ω) hZrW) :=
    measurable_valuesProjection hZrW
  -- Step 1: obsCondKernel ↔ condDistrib.
  have h1 := M.obsCondKernel_ae_eq_condDistrib Y (Z.image SWIGNode.random ∪ W) hY hZrW s
  -- Step 2: transport the condDistrib onto `latentProduct` along `E`.
  have hobs : M.obsKernel s = M.latentProduct.map E := M.obsKernel_eq_latentProduct_map s
  have h2 := condDistrib_map_comp (𝒴 := ValuesOn Y (swigΩ Ω))
    M.latentProduct (φ := E) (g := valuesProjection hY) (f := valuesProjection hZrW)
    hEmeas hπY hπZrW
  -- Step 3: reparametrize the `πZrW∘E` conditioning by the union iso.
  have h3 := condDistrib_comp_right_measurableEquiv (Ω := ValuesOn Y (swigΩ Ω))
    M.latentProduct (Y := valuesProjection hY ∘ E) (X := valuesProjection hZrW ∘ E)
    (valuesUnionEquiv hDisj_ZrW) (hπY.comp hEmeas) (hπZrW.comp hEmeas)
  -- Step 4: the witness identity (pair-conditioned).
  have h4 := obsSide_eq_witness M Y W Z hY hZr hW hZrW hDisj_ZrW hdSepCW s h hh hfac
  -- The pair map equals `e ∘ (π_{Zr∪W} ∘ E)` (both pick the `Zr`- and `W`-coords).
  have hpair : (fun ℓ : M.LatentValues =>
        (valuesProjection hZr (E ℓ), valuesProjection hW (E ℓ)))
      = (⇑(valuesUnionEquiv hDisj_ZrW)) ∘ (valuesProjection hZrW ∘ E) := by
    funext ℓ; rfl
  -- Common base measure `ν` and the base alignments.
  have hbase1 : MeasureTheory.Measure.map (valuesProjection hZrW) (M.obsKernel s)
      = MeasureTheory.Measure.map (valuesProjection hZrW ∘ E) M.latentProduct := by
    rw [hobs, MeasureTheory.Measure.map_map hπZrW hEmeas]
  simp only [← hobs] at h2
  -- Chain h1, h2: obsCondKernel = condDistrib of the pulled-back coords.
  have h12 := h1.trans h2
  -- Transport h4 from base `map pair lat` to `ν` via the iso `e`.
  have hh4base : MeasureTheory.Measure.map
        (fun ℓ : M.LatentValues =>
          (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)),
           valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))) M.latentProduct
      = MeasureTheory.Measure.map (valuesUnionEquiv hDisj_ZrW)
          (MeasureTheory.Measure.map (valuesProjection hZrW ∘ E) M.latentProduct) := by
    rw [show (fun ℓ : M.LatentValues =>
        (valuesProjection hZr (M.randomToObserved (M.evalMap s ℓ)),
         valuesProjection hW (M.randomToObserved (M.evalMap s ℓ))))
        = (⇑(valuesUnionEquiv hDisj_ZrW)) ∘ (valuesProjection hZrW ∘ E) from hpair,
      ← MeasureTheory.Measure.map_map (valuesUnionEquiv hDisj_ZrW).measurable
        (hπZrW.comp hEmeas)]
  rw [hh4base] at h4
  -- The witness kernel (its coe is defeq to `h4`'s RHS), used for measurability.
  have hwk_meas : Measurable (fun p :
        ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω) =>
        (ProbabilityTheory.condDistrib
            (valuesProjection
              (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
            (fun ℓ => valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
            M.latentProduct p.2).map (h p.1 p.2)) :=
    ProbabilityTheory.Kernel.measurable
      (ProbabilityTheory.witnessKernel M.latentProduct
        (Z := fun ℓ => valuesProjection hW (M.randomToObserved (M.evalMap s ℓ)))
        (C := valuesProjection
          (M.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W))) hh)
  have h4' := (MeasureTheory.ae_map_iff
      (valuesUnionEquiv hDisj_ZrW).measurable.aemeasurable
      (measurableSet_measure_eq (ProbabilityTheory.Kernel.measurable _) hwk_meas
        (fun _ => inferInstance))).mp h4
  -- Final assembly (all a.e. statements share base `ν = map (πZrW ∘ E) latentProduct`).
  rw [hbase1] at h12 ⊢
  filter_upwards [h12, h3, h4'] with c hc12 hc3 hc4
  rw [hc12, ← hc3]
  exact hc4

set_option maxHeartbeats 1000000 in
-- The cross-SCM override-compat unfolding (`evalMap_overrideC_fixSet_compat_on_fillZrW`
-- transported through `evalMap_overrideC_eq` at each `Y`-node) is `whnf`-heavy, so the
-- default heartbeat budget is raised for this single filled-assignment identification lemma.
/-- **Do-side cross-SCM core: the M2-pullback `W`-conditional on
    `M2.latentProduct` equals the M1 posterior witness kernel.**

    This is the genuinely-new analytic content of the do-side bridge, isolated
    *after* the mechanical Step-A transport (`condDistrib_map_comp`@M2).  The LHS
    is the conditional law of `π_Y ∘ E2` given `π_W ∘ E2` under `M2.latentProduct`
    (`E2 := M2.randomToObserved ∘ M2.evalMap s'`, `s' := fixSetExtend s0 t`);
    the RHS is `M1`'s posterior witness kernel `(condDistrib C_W (π_W∘E1)
    M1.latentProduct w).map (h t w)` (`C_W := M'.cutsetLatent Y (Zr∪W)`,
    `E1 := randomToObserved ∘ M'.evalMap s0`).

    **Content (M2 witness chain + cross-SCM identification).**  At `M2`, random
    `Zr` is childless (`fixSet_random_not_isAncestor`), so `Y` factors through
    `(W, C_W@M2)` with no treatment coordinate; the witness lemma
    `condDistrib_map_of_condDistrib_fst_eq` (with the `M2` cut-set factorization
    `cutset_factor_pointwise`@M2 and the `M2` cut-set CI
    `cutset_condIndep_condDistrib`@M2) yields the `M2` posterior witness kernel.
    The two witness kernels are then identified along the `fillZrW` assignment via
    `fixSet_latentProduct_compat` (`M2.latentProduct.map reindex = M1.latentProduct`)
    and `evalMap_overrideC_fixSet_compat_on_fillZrW` (override maps agree on
    observed nodes), with the `W`-coordinate aligned by `fixSet_evalMap_nonAnc_compat`
    (`W` non-descendant via `hWNonDesc`) — needing the cross-SCM cut-set identity
    `M2.cutsetLatent Y (Zr∪W) = M'.cutsetLatent Y (Zr∪W)` (Zr-avoidance automatic
    at M2 since `Zr` is childless).

    This uses the posterior witness-kernel construction and does not rely on
    the retired rectangle identity `obsKernel_fixSet_rect_eq`.

    The theorem isolates the M2-side witness chain plus the cross-SCM
    identification of the M2 witness kernel with the M1 witness kernel, so the
    surrounding Step-A reduction can use it as a named bridge. -/
theorem doSide_M2_pullback_eq_M1_witness
    (M' : Causalean.SCM N Ω) (Z : Finset N)
    (hZ_obs : ∀ D ∈ Z, SWIGNode.random D ∈ M'.observed)
    (hZ_fixed : ∀ D ∈ Z, SWIGNode.fixed D ∉ M'.fixed)
    (Y W : Finset (SWIGNode N))
    (hY : Y ⊆ M'.observed) (hW : W ⊆ M'.observed)
    (hZr : Z.image SWIGNode.random ⊆ M'.observed)
    (hZrW : Z.image SWIGNode.random ∪ W ⊆ M'.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hDisj_YZr : Disjoint Y (Z.image SWIGNode.random))
    (hWNonDesc : ∀ z ∈ Z, ∀ v ∈ W,
      ¬ (M'.fixSet Z hZ_obs hZ_fixed).dag.isAncestor (SWIGNode.fixed z) v)
    [StandardBorelSpace M'.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [StandardBorelSpace
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).RandomValues]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).ObservedValues]
    [StandardBorelSpace (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [Nonempty (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.jointKernel s)]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.obsKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).jointKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).obsKernel s)]
    [MeasurableSpace.CountableOrCountablyGenerated
      (M'.fixSet Z hZ_obs hZ_fixed).FixedValues (ValuesOn W (swigΩ Ω))]
    [MeasurableSingletonClass
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    (s0 : M'.FixedValues)
    (t : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
    (h : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) → ValuesOn W (swigΩ Ω)
            → ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω)
            → ValuesOn Y (swigΩ Ω))
    (hh : Measurable (fun p :
        (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
          × ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
        h p.1.1 p.1.2 p.2))
    (_hfac : ∀ ℓ : M'.LatentValues,
        valuesProjection hY (M'.randomToObserved (M'.evalMap s0 ℓ))
          = h (valuesProjection hZr (M'.randomToObserved (M'.evalMap s0 ℓ)))
              (valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
              (valuesProjection (M'.cutsetLatent_subset Y
                (Z.image SWIGNode.random ∪ W)) ℓ))
    (hoverride : ∀ (zr : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
          (w' : ValuesOn W (swigΩ Ω)) (ℓ : M'.LatentValues),
        h zr w'
            (valuesProjection (M'.cutsetLatent_subset Y
              (Z.image SWIGNode.random ∪ W)) ℓ)
          = M'.evalMap_overrideC hY hZrW s0 (valuesUnionMk zr w') ℓ) :
    (fun w => ProbabilityTheory.condDistrib
          (valuesProjection ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY)
            ∘ fun ℓ : (M'.fixSet Z hZ_obs hZ_fixed).LatentValues =>
              (M'.fixSet Z hZ_obs hZ_fixed).randomToObserved
                ((M'.fixSet Z hZ_obs hZ_fixed).evalMap
                  (M'.fixSetExtend Z hZ_obs hZ_fixed s0 t) ℓ))
          (valuesProjection ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW)
            ∘ fun ℓ : (M'.fixSet Z hZ_obs hZ_fixed).LatentValues =>
              (M'.fixSet Z hZ_obs hZ_fixed).randomToObserved
                ((M'.fixSet Z hZ_obs hZ_fixed).evalMap
                  (M'.fixSetExtend Z hZ_obs hZ_fixed s0 t) ℓ))
          (M'.fixSet Z hZ_obs hZ_fixed).latentProduct w)
      =ᵐ[(M'.obsKernel s0).map (valuesProjection hW)]
        (fun w => ((ProbabilityTheory.condDistrib
              (valuesProjection
                (M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
              (fun ℓ : M'.LatentValues =>
                valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
              M'.latentProduct) w).map (h t w)) := by
  classical
  set M2 := M'.fixSet Z hZ_obs hZ_fixed with hM2
  set s' := M'.fixSetExtend Z hZ_obs hZ_fixed s0 t with hs'
  haveI : MeasureTheory.IsProbabilityMeasure M'.latentProduct := inferInstance
  haveI : MeasureTheory.IsFiniteMeasure M'.latentProduct := inferInstance
  set hY_M2 : Y ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY with hhY_M2
  set hW_M2 : W ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW with hhW_M2
  set hZrW_M2 : Z.image SWIGNode.random ∪ W ⊆ M2.observed :=
    (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hZrW with hhZrW_M2
  -- The M2 / M1 observed-eval pullbacks.  Both act on `M'.LatentValues = M2.LatentValues`.
  set E2 : M2.LatentValues → M2.ObservedValues :=
    fun ℓ => M2.randomToObserved (M2.evalMap s' ℓ) with hE2_def
  set E1 : M'.LatentValues → M'.ObservedValues :=
    fun ℓ => M'.randomToObserved (M'.evalMap s0 ℓ) with hE1_def
  -- Cut-set subset (the SAME finset on the M1 side; latent index spaces agree by `rfl`).
  have hCWsub : M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W) ⊆ M'.unobserved :=
    M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)
  -- (P2): the `W`-projection of `E2` equals that of `E1` (W non-descendant of the do-targets).
  have hP2 : ∀ ℓ : M2.LatentValues,
      valuesProjection hW_M2 (E2 ℓ) = valuesProjection hW (E1 ℓ) := by
    intro ℓ; funext v
    have hvW : v.val ∈ W := v.property
    have hvObs : v.val ∈ M'.observed := hW v.property
    have hkey := fixSet_evalMap_nonAnc_compat M' Z hZ_obs hZ_fixed s' ℓ (v := v.val) hvObs
      (fun z hz => hWNonDesc z hz v.val hvW)
    rw [M'.fixSetProj_fixSetExtend Z hZ_obs hZ_fixed s0 t] at hkey
    change M2.evalMap s' ℓ _ = M'.evalMap s0 _ _
    rw [hkey]; rfl
  -- (P1): the `Y`-projection of `E2` is the M1 witness map at treatment `t`.
  -- Proof: M2's override at `Y` reduces — via `evalMap_overrideC_dropZr_on_fillZrW` and the
  -- cross-SCM compat `evalMap_overrideC_fixSet_compat_on_fillZrW` — to M1's override at the
  -- block value `valuesUnionMk t (π_W (E2 ℓ))`, which `hoverride` identifies with `h t ·`.
  have hP1 : ∀ ℓ : M2.LatentValues,
      valuesProjection hY_M2 (E2 ℓ)
        = h t (valuesProjection hW_M2 (E2 ℓ)) (valuesProjection hCWsub ℓ) := by
    intro ℓ
    -- Abbreviate the realized `W`-value of `E2 ℓ`.
    set w := valuesProjection hW_M2 (E2 ℓ) with hw_def
    -- (a) M2.evalMap_overrideC over `W` at its self-value equals `π_Y (E2 ℓ)`.
    have hself_W : (w : ValuesOn W (swigΩ Ω))
        = (fun v' : {v // v ∈ W} =>
            (M2.observedAt_observedIndex ⟨v'.val, hW_M2 v'.property⟩) ▸
              evalObservedAux M2 s' ℓ
                (M2.observedIndex ⟨v'.val, hW_M2 v'.property⟩).val
                (M2.observedIndex ⟨v'.val, hW_M2 v'.property⟩).isLt) := by
      funext v'
      change (E2 ℓ) ⟨v'.val, hW_M2 v'.property⟩ = _
      change M2.evalMap s' ℓ ⟨v'.val, _⟩ = _
      rw [M2.evalMap_observed s' ℓ _ (hW_M2 v'.property)]
    have hcW : M2.evalMap_overrideC hY_M2 hW_M2 s' w ℓ
            = valuesProjection hY_M2 (E2 ℓ) := by
      rw [hself_W, M2.evalMap_overrideC_at_self hY_M2 hW_M2 s' ℓ]
      funext v
      change _ = (E2 ℓ) ⟨v.val, hY_M2 v.property⟩
      change _ = M2.evalMap s' ℓ ⟨v.val, _⟩
      rw [M2.evalMap_observed s' ℓ _ (hY_M2 v.property)]
    -- (b) override over `W` = override over `Zr∪W` at the `fillZrW`-filled block (`dropZr`).
    have hdrop : M2.evalMap_overrideC hY_M2 hZrW_M2 s'
            (M'.fillZrW Z hZ_obs hZ_fixed W s' w) ℓ
          = M2.evalMap_overrideC hY_M2 hW_M2 s' w ℓ :=
      evalMap_overrideC_dropZr_on_fillZrW M' Z hZ_obs hZ_fixed Y W
        hY_M2 hW_M2 hZrW_M2 hDisj_YZr s' ℓ w
    -- (c) cross-SCM compat: M2 override over `Zr∪W` at `fillZrW` = M1 override over `Zr∪W`
    --     at `fillZrW`, base `fixSetProj s' = s0`, latent reindex = identity.
    have hcompat : M2.evalMap_overrideC hY_M2 hZrW_M2 s'
            (M'.fillZrW Z hZ_obs hZ_fixed W s' w) ℓ
          = M'.evalMap_overrideC hY hZrW s0 (valuesUnionMk t w) ℓ := by
      -- Rewrite the `M2`-side fill block to `valuesUnionMk t w` (`s' = fixSetExtend s0 t`).
      rw [hs', fillZrW_fixSetExtend M' Z hZ_obs hZ_fixed W s0 t w, ← hs']
      funext v
      -- unfold both overrides to `evalObservedAuxOverride` at the SAME node `v.val`.
      rw [evalMap_overrideC_eq M2 hY_M2 hZrW_M2 s' _ ℓ v,
          evalMap_overrideC_eq M' hY hZrW s0 _ ℓ v]
      -- the compat lemma compares the full-observed-output overrides at node `v.val`;
      -- both unfold to the same `evalObservedAuxOverride` value, so transport via it.
      have hcv := evalMap_overrideC_fixSet_compat_on_fillZrW M' Z hZ_obs hZ_fixed W
        hZrW_M2 hZrW s' w ℓ (v := v.val) (hY_M2 v.property)
      -- `hcv` (read right→left) equates M2 and M1 full-output overrides at `⟨v.val, _⟩`.
      rw [evalMap_overrideC_eq M2 (Finset.Subset.refl _) hZrW_M2 s' _ ℓ
            ⟨v.val, hY_M2 v.property⟩,
          evalMap_overrideC_eq M' (Finset.Subset.refl _) hZrW
            (M'.fixSetProj Z hZ_obs hZ_fixed s')
            _ _ ⟨v.val, hY v.property⟩] at hcv
      -- `s0 = fixSetProj s'`, `valuesUnionMk t w = fillZrW W s' w`, reindex ℓ = ℓ.
      rw [M'.fixSetProj_fixSetExtend Z hZ_obs hZ_fixed s0 t,
          fillZrW_fixSetExtend M' Z hZ_obs hZ_fixed W s0 t w] at hcv
      exact hcv.symm
    -- (d) `hoverride` identifies the M1 override at `(t, w)` with `h t w (π_{C_W} ℓ)`.
    rw [← hcW, ← hdrop, hcompat]
    exact (hoverride t w ℓ).symm
  -- Measurability of the M1 conditioning / cut-set maps (reuse the SCM helper).
  have hZmeas : Measurable (fun ℓ : M'.LatentValues => valuesProjection hW (E1 ℓ)) :=
    M'.valuesProjection_randomToObserved_evalMap_meas hW s0
  have hCmeas : Measurable
      (valuesProjection (Ω := swigΩ Ω) hCWsub) := measurable_valuesProjection hCWsub
  -- `H := fun w c => h t w c` packages the witness map at the fixed treatment `t`.
  have hH : Measurable (fun p : ValuesOn W (swigΩ Ω)
        × ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
        h t p.1 p.2) :=
    hh.comp (((measurable_const.prodMk measurable_fst).prodMk measurable_snd))
  -- The no-treatment witness corollary on `M'.latentProduct`, conditioning on `π_W ∘ E1`.
  have hwit := ProbabilityTheory.condDistrib_map_of_funext (Ω := M'.LatentValues)
    (𝒵 := ValuesOn W (swigΩ Ω))
    (𝒞 := ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))
    (𝒴 := ValuesOn Y (swigΩ Ω))
    M'.latentProduct
    (Z := fun ℓ : M'.LatentValues => valuesProjection hW (E1 ℓ))
    (C := valuesProjection hCWsub) (H := fun w c => h t w c)
    hZmeas hCmeas hH
  -- The corollary's LHS factorized map `fun ℓ => h t (π_W (E1 ℓ)) (π_{C_W} ℓ)` equals `π_Y ∘ E2`.
  have hYeq : (fun ℓ : M'.LatentValues =>
        h t (valuesProjection hW (E1 ℓ)) (valuesProjection hCWsub ℓ))
      = fun ℓ : M2.LatentValues => valuesProjection hY_M2 (E2 ℓ) := by
    funext ℓ; rw [hP1 ℓ, hP2 ℓ]
  rw [hYeq] at hwit
  -- The base `M'.latentProduct.map (π_W ∘ E1)` equals `μW = (obsKernel s0).map π_W`.
  have hE1meas : Measurable (fun ℓ : M'.LatentValues => M'.randomToObserved (M'.evalMap s0 ℓ)) :=
    M'.measurable_randomToObserved.comp
      (M'.evalMap_measurable.comp (measurable_const.prodMk measurable_id))
  have hbaseμW : M'.latentProduct.map (fun ℓ : M'.LatentValues => valuesProjection hW (E1 ℓ))
      = (M'.obsKernel s0).map (valuesProjection hW) := by
    rw [M'.obsKernel_eq_latentProduct_map s0,
      MeasureTheory.Measure.map_map (measurable_valuesProjection hW) hE1meas]
    rfl
  rw [hbaseμW] at hwit
  -- The goal's LHS conditioning map `π_W ∘ E2` equals `π_W ∘ E1` (by (P2)); rewrite `hwit`'s
  -- conditioning back to the `E2`-form so its LHS matches the goal's LHS (defeq otherwise).
  have hWmapeq : (fun ℓ : M2.LatentValues => valuesProjection hW_M2 (E2 ℓ))
      = fun ℓ : M'.LatentValues => valuesProjection hW (E1 ℓ) := funext hP2
  convert hwit using 3
  congr 1

/-- **Do-side analytic core: the M2 `W`-conditional equals the M1 witness kernel.**

    At the extended base slice `s' := fixSetExtend s0 t`, the measure-level
    conditional law of `Y` given `W` under the do-model `M2 := M'.fixSet Z`'s
    observational kernel is — `μW`-a.e. in `w`, where
    `μW = (M'.obsKernel s0).map π_W` — the *original* model `M1`'s posterior
    witness kernel at `(t, w)`:

      `condDistrib π_Y π_W (M2.obsKernel s') w
         = (condDistrib C_W (π_W∘E1) M1.latentProduct w).map (h t w)`.

    This is the genuinely-new analytic content of the do-side bridge.  It bundles
    the `M2`-side witness chain (transport the `M2` obs-level conditional onto
    `M2.latentProduct` via `condDistrib_map_comp`, then apply the witness lemma
    with the `M2` cut-set factorization — where random `Zr` is childless, so it
    contributes no treatment coordinate) together with the cross-SCM
    identification of the resulting `M2` witness kernel with the `M1` witness
    kernel (`fixSet_latentProduct_compat` + `evalMap_overrideC_fixSet_compat_on_fillZrW`),
    all transported onto the common `μW` base by Rule 3's `W`-marginal equality
    `obsKernel_fixSet_W_marginal_eq_M1_marginal` (with `fixSetProj_fixSetExtend`).

    This uses the posterior witness-kernel construction and does not rely on
    the retired rectangle identity `obsKernel_fixSet_rect_eq`.

    This is the full `M2`-witness mirror of `obsSide_eq_witness` plus the
    `fillZrW` cross-SCM kernel identification. It is isolated as a named bridge
    used by the surrounding `doSide_eq_witness` assembly for base alignment,
    the obsCondKernel/condDistrib bridge, and a.e. plumbing. -/
theorem doSide_M2_condDistrib_eq_M1_witness
    (M' : Causalean.SCM N Ω) (Z : Finset N)
    (hZ_obs : ∀ D ∈ Z, SWIGNode.random D ∈ M'.observed)
    (hZ_fixed : ∀ D ∈ Z, SWIGNode.fixed D ∉ M'.fixed)
    (Y W : Finset (SWIGNode N))
    (hY : Y ⊆ M'.observed) (hW : W ⊆ M'.observed)
    (hZr : Z.image SWIGNode.random ⊆ M'.observed)
    (hZrW : Z.image SWIGNode.random ∪ W ⊆ M'.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hDisj_YZr : Disjoint Y (Z.image SWIGNode.random))
    (hWNonDesc : ∀ z ∈ Z, ∀ v ∈ W,
      ¬ (M'.fixSet Z hZ_obs hZ_fixed).dag.isAncestor (SWIGNode.fixed z) v)
    [StandardBorelSpace M'.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [StandardBorelSpace
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).RandomValues]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).ObservedValues]
    [StandardBorelSpace (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [Nonempty (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.jointKernel s)]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.obsKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).jointKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).obsKernel s)]
    [MeasurableSpace.CountableOrCountablyGenerated
      (M'.fixSet Z hZ_obs hZ_fixed).FixedValues (ValuesOn W (swigΩ Ω))]
    [MeasurableSingletonClass
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    (s0 : M'.FixedValues)
    (t : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
    (h : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) → ValuesOn W (swigΩ Ω)
            → ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω)
            → ValuesOn Y (swigΩ Ω))
    (hh : Measurable (fun p :
        (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
          × ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
        h p.1.1 p.1.2 p.2))
    (hfac : ∀ ℓ : M'.LatentValues,
        valuesProjection hY (M'.randomToObserved (M'.evalMap s0 ℓ))
          = h (valuesProjection hZr (M'.randomToObserved (M'.evalMap s0 ℓ)))
              (valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
              (valuesProjection (M'.cutsetLatent_subset Y
                (Z.image SWIGNode.random ∪ W)) ℓ))
    (hoverride : ∀ (zr : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
          (w' : ValuesOn W (swigΩ Ω)) (ℓ : M'.LatentValues),
        h zr w'
            (valuesProjection (M'.cutsetLatent_subset Y
              (Z.image SWIGNode.random ∪ W)) ℓ)
          = M'.evalMap_overrideC hY hZrW s0 (valuesUnionMk zr w') ℓ) :
    (fun w => ProbabilityTheory.condDistrib
          (valuesProjection ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY))
          (valuesProjection ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW))
          ((M'.fixSet Z hZ_obs hZ_fixed).obsKernel
            (M'.fixSetExtend Z hZ_obs hZ_fixed s0 t)) w)
      =ᵐ[(M'.obsKernel s0).map (valuesProjection hW)]
        (fun w => ((ProbabilityTheory.condDistrib
              (valuesProjection
                (M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
              (fun ℓ : M'.LatentValues =>
                valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
              M'.latentProduct) w).map (h t w)) := by
  classical
  set M2 := M'.fixSet Z hZ_obs hZ_fixed with hM2
  set s' := M'.fixSetExtend Z hZ_obs hZ_fixed s0 t with hs'
  set hY_M2 : Y ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY with hhY_M2
  set hW_M2 : W ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW with hhW_M2
  set μW := (M'.obsKernel s0).map (valuesProjection hW) with hμW
  -- Abbreviation: the M2 observed-eval pullback `E2`.
  set E2 : M2.LatentValues → M2.ObservedValues :=
    fun ℓ => M2.randomToObserved (M2.evalMap s' ℓ) with hE2_def
  have hE2meas : Measurable E2 := by
    have hev : Measurable (fun ℓ : M2.LatentValues => M2.evalMap s' ℓ) := by
      have : M2.evalMap s' = fun ℓ => Function.uncurry M2.evalMap (s', ℓ) := rfl
      rw [this]
      exact M2.evalMap_measurable.comp (Measurable.prodMk measurable_const measurable_id)
    exact M2.measurable_randomToObserved.comp hev
  have hπY : Measurable (valuesProjection (Ω := swigΩ Ω) hY_M2) :=
    measurable_valuesProjection hY_M2
  have hπW : Measurable (valuesProjection (Ω := swigΩ Ω) hW_M2) :=
    measurable_valuesProjection hW_M2
  -- Base alignment: the M2 `W`-marginal at the slice `s'` equals `μW` (Rule 3).
  have hbase : (M2.obsKernel s').map (valuesProjection hW_M2) = μW := by
    have hRule3 := obsKernel_fixSet_W_marginal_eq_M1_marginal M' Z hZ_obs hZ_fixed W hW
      hWNonDesc s'
    rw [hμW]
    rw [show (M2.obsKernel s').map (valuesProjection hW_M2)
        = (M2.obsKernel s').map
            (valuesProjection ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW))
        from rfl, hRule3,
      M'.fixSetProj_fixSetExtend Z hZ_obs hZ_fixed s0 t]
  -- Step A: transport the M2 LHS `condDistrib π_Y π_W (M2.obsKernel s')` onto
  -- `M2.latentProduct` via `obsKernel_eq_latentProduct_map` + `condDistrib_map_comp`.
  have hobs : M2.obsKernel s' = M2.latentProduct.map E2 :=
    M2.obsKernel_eq_latentProduct_map s'
  have hstepA := condDistrib_map_comp (𝒴 := ValuesOn Y (swigΩ Ω))
    M2.latentProduct (φ := E2) (g := valuesProjection hY_M2) (f := valuesProjection hW_M2)
    hE2meas hπY hπW
  -- `hstepA : condDistrib π_Y π_W (latentProduct.map E2)
  --            =ᵐ[(latentProduct.map E2).map π_W] condDistrib (π_Y∘E2) (π_W∘E2) latentProduct`.
  -- Align the base of `hstepA` to `μW`.
  have hbase' : (M2.latentProduct.map E2).map (valuesProjection hW_M2) = μW := by
    rw [← hobs]; exact hbase
  rw [hbase'] at hstepA
  -- Step B+C (isolated TRUE core): the M2-pullback condDistrib equals the M1 witness kernel.
  have hcore := doSide_M2_pullback_eq_M1_witness M' Z hZ_obs hZ_fixed Y W hY hW hZr
    hZrW hDisj_ZrW hDisj_YZr hWNonDesc s0 t h hh hfac hoverride
  -- Align the goal's LHS (over `M2.obsKernel s'`) to `hstepA`'s LHS (over `latentProduct.map E2`)
  -- via `hobs`, handling the dependent `IsFiniteMeasure` instance with `subst`.
  refine Filter.EventuallyEq.trans ?_ (hstepA.trans hcore)
  have hcongr : (ProbabilityTheory.condDistrib (valuesProjection hY_M2)
        (valuesProjection hW_M2) (M2.obsKernel s'))
      = ProbabilityTheory.condDistrib (valuesProjection hY_M2)
        (valuesProjection hW_M2) (M2.latentProduct.map E2) := by
    congr 1
  rw [hcongr]

/-- **Do-side per-slice witness identity (M1-witness-kernel form).**

    At a fixed treatment value `t`, the do-model `M2 := M'.fixSet Z` `W`-conditional
    intervened at `t` (i.e. at the extended base slice `fixSetExtend s0 t`)
    equals — `μW`-a.e. in `w`, where `μW = (M'.obsKernel s0).map π_W` — the
    *original* model `M1`'s **posterior witness kernel** at `(t, w)`:

      `(condDistrib C_W (π_W∘E1) M1.latentProduct w).map (h t w)`,

    the SAME witness kernel `obsCondKernel_union_eq_witness`@M1 produces (so the
    export can connect the two by transitivity without any positivity assumption in
    *this* lemma).  The `h`/`hh`/`hfac` arguments are the M1 cut-set factorization
    data (obtained by the export from `cutset_factor_pointwise M' Y W Z … s0`,
    exactly as `obsSide_eq_witness` consumes them).

    This gives the per-slice comparison directly through posterior witness
    kernels, without using the retired rectangle identity `obsCondKernel_fixSet_eq`.

    * **LHS = M2 witness, then = M1 witness.**  Mirroring
      `obsCondKernel_union_eq_witness` at `M2` conditioned on `W` *alone* (random
      `Zr` has no children in `M2` — `fixSet_random_not_isAncestor` — so `Zr`
      contributes no treatment coordinate and `M2.cutsetLatent Y W` coincides with
      `M1.cutsetLatent Y (Zr∪W)`).  The two witness kernels are then identified on
      the `fillZrW` assignment via `fixSet_latentProduct_compat`
      (`M2.latentProduct.map (reindex) = M1.latentProduct`) and
      `evalMap_overrideC_fixSet_compat_on_fillZrW` (the override maps agree on
      observed nodes), with the `W`-marginals aligned by
      `obsKernel_fixSet_W_marginal_eq_M1_marginal` (Rule 3).

    The theorem combines the `M2`-side mirror of the obs-side witness chain
    (`obsCondKernel_ae_eq_condDistrib`@M2 → `condDistrib_map_comp`@M2 → the
    `M2` cut-set factorization → the `M2` witness identity) with the cross-SCM
    identification of the `M2` witness kernel and the `M1` witness kernel,
    transported onto the common `μW` base via Rule 3's `W`-marginal equality. -/
theorem doSide_eq_witness
    (M' : Causalean.SCM N Ω) (Z : Finset N)
    (hZ_obs : ∀ D ∈ Z, SWIGNode.random D ∈ M'.observed)
    (hZ_fixed : ∀ D ∈ Z, SWIGNode.fixed D ∉ M'.fixed)
    (Y W : Finset (SWIGNode N))
    (hY : Y ⊆ M'.observed) (hW : W ⊆ M'.observed)
    (hZr : Z.image SWIGNode.random ⊆ M'.observed)
    (hZrW : Z.image SWIGNode.random ∪ W ⊆ M'.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hDisj_YZr : Disjoint Y (Z.image SWIGNode.random))
    (hWNonDesc : ∀ z ∈ Z, ∀ v ∈ W,
      ¬ (M'.fixSet Z hZ_obs hZ_fixed).dag.isAncestor (SWIGNode.fixed z) v)
    [StandardBorelSpace M'.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [StandardBorelSpace
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).RandomValues]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).ObservedValues]
    [StandardBorelSpace (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [Nonempty (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.jointKernel s)]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.obsKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).jointKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).obsKernel s)]
    [MeasurableSpace.CountableOrCountablyGenerated
      M'.FixedValues (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated
      (M'.fixSet Z hZ_obs hZ_fixed).FixedValues
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated
      (M'.fixSet Z hZ_obs hZ_fixed).FixedValues (ValuesOn W (swigΩ Ω))]
    [MeasurableSingletonClass
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    (s0 : M'.FixedValues)
    (t : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
    (h : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) → ValuesOn W (swigΩ Ω)
            → ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω)
            → ValuesOn Y (swigΩ Ω))
    (hh : Measurable (fun p :
        (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω))
          × ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω) =>
        h p.1.1 p.1.2 p.2))
    (hfac : ∀ ℓ : M'.LatentValues,
        valuesProjection hY (M'.randomToObserved (M'.evalMap s0 ℓ))
          = h (valuesProjection hZr (M'.randomToObserved (M'.evalMap s0 ℓ)))
              (valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
              (valuesProjection (M'.cutsetLatent_subset Y
                (Z.image SWIGNode.random ∪ W)) ℓ))
    (hoverride : ∀ (zr : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
          (w' : ValuesOn W (swigΩ Ω)) (ℓ : M'.LatentValues),
        h zr w'
            (valuesProjection (M'.cutsetLatent_subset Y
              (Z.image SWIGNode.random ∪ W)) ℓ)
          = M'.evalMap_overrideC hY hZrW s0 (valuesUnionMk zr w') ℓ) :
    ∀ᵐ w ∂((M'.obsKernel s0).map (valuesProjection hW)),
      (M'.fixSet Z hZ_obs hZ_fixed).obsCondKernel Y W
          ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY)
          ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW)
          (M'.fixSetExtend Z hZ_obs hZ_fixed s0 t, w)
        = ((ProbabilityTheory.condDistrib
              (valuesProjection
                (M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
              (fun ℓ : M'.LatentValues =>
                valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
              M'.latentProduct) w).map (h t w) := by
  -- Witness-route per-slice identity, **M1-witness-kernel form**.  The LHS (the M2
  -- `W`-conditional intervened at `t`) equals the M1 posterior witness kernel at
  -- `(t, w)`. The M2 witness chain (`obsCondKernel_ae_eq_condDistrib`@M2 →
  -- `condDistrib_map_comp`@M2 → the M2 cut-set factorization with trivial `Zr`
  -- coordinate → the M2 witness identity) and the cross-SCM identification of the M2
  -- witness kernel with the M1 witness kernel via `fixSet_latentProduct_compat` +
  -- `evalMap_overrideC_fixSet_compat_on_fillZrW`, transported onto the common `μW`
  -- base by Rule 3 (`obsKernel_fixSet_W_marginal_eq_M1_marginal`).  The analytic
  -- core is isolated as `doSide_M2_condDistrib_eq_M1_witness`; here we discharge
  -- the assembly (obsCondKernel ↔ condDistrib bridge at M2 + base alignment).
  classical
  set M2 := M'.fixSet Z hZ_obs hZ_fixed with hM2
  set s' := M'.fixSetExtend Z hZ_obs hZ_fixed s0 t with hs'
  set hY_M2 : Y ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY with hhY_M2
  set hW_M2 : W ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW with hhW_M2
  set μW := (M'.obsKernel s0).map (valuesProjection hW) with hμW
  -- Base alignment: the M2 `W`-marginal at the slice `s'` equals `μW` (Rule 3 +
  -- `fixSetProj (fixSetExtend s0 t) = s0`).
  have hbase : (M2.obsKernel s').map (valuesProjection hW_M2) = μW := by
    have hRule3 := obsKernel_fixSet_W_marginal_eq_M1_marginal M' Z hZ_obs hZ_fixed W hW
      hWNonDesc s'
    rw [hμW]
    rw [show (M2.obsKernel s').map (valuesProjection hW_M2)
        = (M2.obsKernel s').map
            (valuesProjection ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW))
        from rfl, hRule3,
      M'.fixSetProj_fixSetExtend Z hZ_obs hZ_fixed s0 t]
  -- Step 1: at M2, `obsCondKernel Y W (s', ·) =ᵐ condDistrib π_Y π_W (M2.obsKernel s')`,
  -- with base `(M2.obsKernel s').map π_W`.
  have h1 := M2.obsCondKernel_ae_eq_condDistrib Y W hY_M2 hW_M2 s'
  rw [hbase] at h1
  -- Step 2: the analytic core — that condDistrib equals the M1 witness kernel.
  have h2 := doSide_M2_condDistrib_eq_M1_witness M' Z hZ_obs hZ_fixed Y W hY hW hZr
    hZrW hDisj_ZrW hDisj_YZr hWNonDesc s0 t h hh hfac hoverride
  -- Both `h1` and `h2` are stated over the base `μW`; chain.
  filter_upwards [h1, h2] with w hw1 hw2
  -- `hw1 : M2.obsCondKernel Y W (s', w) = condDistrib π_Y π_W (M2.obsKernel s') w`
  -- `hw2 : condDistrib π_Y π_W (M2.obsKernel s') w = witness`
  rw [hw1, hw2]

/-- **Product-form cross-SCM bridge for the do-side conditional kernel.**

    For `(νZ ⊗ₘ const μW)`-a.e. `(t, w)`, the do-model `W`-conditional intervened
    at `t` equals the original model's `(Zr∪W)`-conditional at the filled point
    `valuesUnionMk t w`.  Consumed by `condDistrib_fixSet_cross_SCM_bridge`
    (`Rule2AE.lean`).

    **Witness-route assembly** (replacing the deleted, mis-routed
    `obsCondKernel_struct` chain):

    * Obs side: `obsCondKernel_ae_eq_condDistrib` pins
      `M1.obsCondKernel Y (Zr∪W) (s0, ·) =ᵐ condDistrib π_Y π_{Zr∪W} (obsKernel s0)`;
      `condDistrib_map_comp` (with `φ = randomToObserved ∘ evalMap s0`) transports
      this onto `latentProduct`; reparametrizing the `(Zr∪W)`-conditioning by the
      disjoint-union iso `valuesUnionEquiv` (via
      `condDistrib_comp_right_measurableEquiv`) lands it on the pair
      `(π_Zr∘E, π_W∘E)`, where `obsSide_eq_witness` rewrites it as the posterior
      witness kernel `(condDistrib C_W (π_W∘E) latentProduct).map (h t w)`.
    * Do side: the same chain under `M2 := M'.fixSet Z` (random `Zr` has no
      children, `fixSet_random_not_isAncestor`), giving the M2 witness kernel; the
      two witness kernels coincide along the `fillZrW` assignment via `fixSet_latentProduct_compat`
      + `evalMap_overrideC_fixSet_compat_on_fillZrW`.
    * Positivity: `obsKernel_fixSet_W_marginal_eq_M1_marginal` (Rule 3) +
      `hPositivity_ae` transport the obs-side a.e. statement onto the product
      `νZ ⊗ₘ μW`, where the do-side is natively pinned (Fubini via
      `ae_compProd_of_ae_ae`).

    The theorem assembles the iso reparametrization (`valuesUnionEquiv` ↔ pair
    conditioning), the do-side `M2` mirror of `obsSide_eq_witness`, the `fillZrW`
    identification of the two witness kernels, and the product/positivity Fubini
    lift, using `cutset_factor_pointwise` and `cutset_condIndep_condDistrib` as
    the cut-set cores. -/
theorem obsCondKernel_fixSet_M1_eq_ae_product
    (M' : Causalean.SCM N Ω) (Z : Finset N)
    (hZ_obs : ∀ D ∈ Z, SWIGNode.random D ∈ M'.observed)
    (hZ_fixed : ∀ D ∈ Z, SWIGNode.fixed D ∉ M'.fixed)
    (Y W : Finset (SWIGNode N))
    (hY : Y ⊆ M'.observed) (hW : W ⊆ M'.observed)
    (hZr : Z.image SWIGNode.random ⊆ M'.observed)
    (hZrW : Z.image SWIGNode.random ∪ W ⊆ M'.observed)
    (hDisj_ZrW : Disjoint (Z.image SWIGNode.random) W)
    (hDisj_YZr : Disjoint Y (Z.image SWIGNode.random))
    (hWNonDesc : ∀ z ∈ Z, ∀ v ∈ W,
      ¬ (M'.fixSet Z hZ_obs hZ_fixed).dag.isAncestor (SWIGNode.fixed z) v)
    (hWNonDescM1 : ∀ D ∈ Z, ∀ w ∈ W,
      ¬ M'.dag.isAncestor (SWIGNode.random D) w)
    (hdSep : (M'.fixSet Z hZ_obs hZ_fixed).dag.dSep
      Y (Z.image SWIGNode.random)
      (W ∪ (M'.fixSet Z hZ_obs hZ_fixed).fixed))
    [StandardBorelSpace M'.RandomValues]
    [∀ n, StandardBorelSpace (swigΩ Ω n)] [∀ n, Nonempty (swigΩ Ω n)]
    [StandardBorelSpace (ValuesOn Y (swigΩ Ω))]
    [Nonempty (ValuesOn Y (swigΩ Ω))]
    [StandardBorelSpace
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [Nonempty
      (ValuesOn (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W)) (swigΩ Ω))]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).RandomValues]
    [StandardBorelSpace (M'.fixSet Z hZ_obs hZ_fixed).ObservedValues]
    [StandardBorelSpace (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [Nonempty (ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.jointKernel s)]
    [∀ s : M'.FixedValues, MeasureTheory.IsFiniteMeasure (M'.obsKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).jointKernel s)]
    [∀ s : (M'.fixSet Z hZ_obs hZ_fixed).FixedValues,
      MeasureTheory.IsFiniteMeasure ((M'.fixSet Z hZ_obs hZ_fixed).obsKernel s)]
    [MeasurableSpace.CountableOrCountablyGenerated
      M'.FixedValues (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated
      (M'.fixSet Z hZ_obs hZ_fixed).FixedValues
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    [MeasurableSpace.CountableOrCountablyGenerated
      (M'.fixSet Z hZ_obs hZ_fixed).FixedValues (ValuesOn W (swigΩ Ω))]
    [MeasurableSingletonClass
      (ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω))]
    (s0 : M'.FixedValues)
    (_hPositivity_ae :
      (((M'.obsKernel s0).map (valuesProjection hZr) ⊗ₘ
          ProbabilityTheory.Kernel.const _
            ((M'.obsKernel s0).map (valuesProjection hW))).map
          (fun p => valuesUnionMk p.1 p.2))
        ≪ ((M'.obsKernel s0).map (valuesProjection hZrW))) :
    ∀ᵐ p ∂((M'.obsKernel s0).map (valuesProjection hZr) ⊗ₘ
            ProbabilityTheory.Kernel.const _
              ((M'.obsKernel s0).map (valuesProjection hW))),
      (M'.fixSet Z hZ_obs hZ_fixed).obsCondKernel Y W
          ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY)
          ((fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW)
          (M'.fixSetExtend Z hZ_obs hZ_fixed s0 p.1, p.2)
        = M'.obsCondKernel Y (Z.image SWIGNode.random ∪ W) hY hZrW
            (s0, valuesUnionMk p.1 p.2) := by
  -- **Per-slice posterior-witness construction.**  `doSide_eq_witness` gives,
  -- for each treatment value `t`, the equality of LHS and RHS at the slice
  -- `s' := fixSetExtend s0 t`, a.e. in `w` under `μW = (M'.obsKernel s0).map π_W`
  -- (the M2 `W`-marginal at the slice equals `μW` literally by Rule 3,
  -- `obsKernel_fixSet_W_marginal_eq_M1_marginal`).  Both sides of that per-slice
  -- identity are pinned to the posterior witness kernel
  -- `(condDistrib C_W (π_W∘E1) M1.latentProduct w).map (h t w)` — RHS via
  -- `obsCondKernel_union_eq_witness`@M1, LHS via the M2 witness chain + cross-SCM
  -- connect. This proof does not rely on the retired rectangle identity
  -- `obsKernel_fixSet_rect_eq`. Finally `ae_compProd_of_ae_ae` lifts the iterated
  -- `∀ᵐ t, ∀ᵐ w` statement to the product `νZ ⊗ₘ const μW`.
  classical
  set M2 := M'.fixSet Z hZ_obs hZ_fixed with hM2
  set hY_M2 : Y ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hY with hhY_M2
  set hW_M2 : W ⊆ M2.observed := (fixSet_observed M' Z hZ_obs hZ_fixed).symm ▸ hW with hhW_M2
  set νZ := (M'.obsKernel s0).map (valuesProjection hZr) with hνZ
  set μW := (M'.obsKernel s0).map (valuesProjection hW) with hμW
  set lam := νZ ⊗ₘ ProbabilityTheory.Kernel.const _ μW with hlam
  -- The fill map and the cut-set factorization data, shared by both witness lemmas.
  set G : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω)
      → ValuesOn (Z.image SWIGNode.random ∪ W) (swigΩ Ω) :=
    fun p => valuesUnionMk p.1 p.2 with hG
  have hG_meas : Measurable G := measurable_valuesUnionMk
  haveI hΩne : ∀ n, Nonempty (Ω n) := fun n =>
    (inferInstance : Nonempty (swigΩ Ω (SWIGNode.random n)))
  obtain ⟨h, hh, hfac, hoverride⟩ := cutset_factor_pointwise M' Y W Z hY hZr hW hZrW s0
  -- The shared posterior witness kernel, as a function of the conditioning pair.
  set wk : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω)
      → MeasureTheory.Measure (ValuesOn Y (swigΩ Ω)) :=
    fun p =>
      ((ProbabilityTheory.condDistrib
          (valuesProjection
            (M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
          (fun ℓ : M'.LatentValues =>
            valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
          M'.latentProduct) p.2).map (h p.1 p.2) with hwk
  -- The projection facts: under `G = valuesUnionMk`, the union iso recovers `(t, w)`.
  have hproj_left : ∀ (t : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
      (w : ValuesOn W (swigΩ Ω)),
      valuesProjection (Finset.subset_union_left) (valuesUnionMk t w) = t := by
    intro t w; funext v
    exact valuesUnionMk_apply_left t w (Finset.subset_union_left v.property) v.property
  have hproj_right : ∀ (t : ValuesOn (Z.image SWIGNode.random) (swigΩ Ω))
      (w : ValuesOn W (swigΩ Ω)),
      valuesProjection (Finset.subset_union_right) (valuesUnionMk t w) = w := by
    intro t w; funext v
    have hnotleft : v.val ∉ Z.image SWIGNode.random := fun hv =>
      (Finset.disjoint_left.mp hDisj_ZrW) hv v.property
    exact valuesUnionMk_apply_right t w (Finset.subset_union_right v.property) hnotleft v.property
  haveI hM2Markov : ProbabilityTheory.IsMarkovKernel
      (M2.obsCondKernel Y W hY_M2 hW_M2) := by
    unfold SCM.obsCondKernel; infer_instance
  haveI hM1Markov : ProbabilityTheory.IsMarkovKernel
      (M'.obsCondKernel Y (Z.image SWIGNode.random ∪ W) hY hZrW) := by
    unfold SCM.obsCondKernel; infer_instance
  -- **RHS = witness** (transport `obsCondKernel_union_eq_witness`@M1 from `μ_C` onto
  -- `lam` via the product positivity `hPositivity_ae`).  This is where positivity is
  -- consumed.
  have h_rhs_witness :
      ∀ᵐ p ∂lam,
        M'.obsCondKernel Y (Z.image SWIGNode.random ∪ W) hY hZrW (s0, G p) = wk p := by
    -- Cutset d-sep at M1, derived from the do-graph d-sep `hdSep`@M2 + criterion (i)
    -- (`hWNonDescM1`) via the cross-model graph lemma.  This REPLACES the deleted
    -- false hypothesis `hdSepM1 : M'.dag.dSep Y Zr (W∪M'.fixed)`.
    have hdSepCW : M'.dag.dSep (M'.cutsetLatent Y (Z.image SWIGNode.random ∪ W))
        (Z.image SWIGNode.random) (W ∪ M'.fixed) :=
      M'.cutsetLatent_dSep_of_fixSet_dSep Z hZ_obs hZ_fixed Y W hW hWNonDescM1 hdSep
    have hunion := obsCondKernel_union_eq_witness M' Y W Z hY hZr hW hZrW
      hDisj_ZrW hdSepCW s0 h hh hfac
    -- `lam.map G ≪ μ_C` (the positivity assumption) transports the `μ_C`-a.e. identity.
    have hAC : MeasureTheory.Measure.map G lam
        ≪ (M'.obsKernel s0).map (valuesProjection hZrW) := _hPositivity_ae
    have h_mapG :
        (fun c => M'.obsCondKernel Y (Z.image SWIGNode.random ∪ W) hY hZrW (s0, c))
          =ᵐ[lam.map G]
          (fun c =>
            ((ProbabilityTheory.condDistrib
                (valuesProjection
                  (M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W)))
                (fun ℓ : M'.LatentValues =>
                  valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
                M'.latentProduct)
              (valuesProjection (Finset.subset_union_right) c)).map
              (h (valuesProjection (Finset.subset_union_left) c)
                 (valuesProjection (Finset.subset_union_right) c))) :=
      hAC.ae_eq hunion
    have h_prod := MeasureTheory.ae_of_ae_map hG_meas.aemeasurable h_mapG
    filter_upwards [h_prod] with p hp
    rw [hp, hwk]
    -- Rewrite the projections of `G p = valuesUnionMk p.1 p.2` to `p.1`, `p.2`.
    simp only [hG, hproj_left, hproj_right]
  -- **LHS = witness** (the do-side per-slice identity, lifted to `lam`).
  have h_lhs_witness :
      ∀ᵐ p ∂lam,
        M2.obsCondKernel Y W hY_M2 hW_M2
            (M'.fixSetExtend Z hZ_obs hZ_fixed s0 p.1, p.2) = wk p := by
    refine MeasureTheory.Measure.ae_compProd_of_ae_ae ?_ ?_
    · -- Measurability of the agreement set.
      have hfst : Measurable (fun p :
          ValuesOn (Z.image SWIGNode.random) (swigΩ Ω) × ValuesOn W (swigΩ Ω) =>
          M2.obsCondKernel Y W hY_M2 hW_M2
            (M'.fixSetExtend Z hZ_obs hZ_fixed s0 p.1, p.2)) := by
        refine (ProbabilityTheory.Kernel.measurable _).comp ?_
        exact ((M'.measurable_fixSetExtend Z hZ_obs hZ_fixed s0).comp
          measurable_fst).prodMk measurable_snd
      have hwk_meas : Measurable wk := by
        rw [hwk]
        exact ProbabilityTheory.Kernel.measurable
          (ProbabilityTheory.witnessKernel M'.latentProduct
            (Z := fun ℓ => valuesProjection hW (M'.randomToObserved (M'.evalMap s0 ℓ)))
            (C := valuesProjection
              (M'.cutsetLatent_subset Y (Z.image SWIGNode.random ∪ W))) hh)
      exact measurableSet_measure_eq hfst hwk_meas (fun _ => inferInstance)
    · -- The per-slice posterior witness-kernel identity at `s' := fixSetExtend s0 t`.
      refine MeasureTheory.ae_of_all _ (fun t => ?_)
      rw [ProbabilityTheory.Kernel.const_apply]
      exact SCM.doSide_eq_witness M' Z hZ_obs hZ_fixed Y W hY hW hZr hZrW
        hDisj_ZrW hDisj_YZr hWNonDesc s0 t h hh hfac hoverride
  -- Combine: LHS = witness = RHS.
  filter_upwards [h_lhs_witness, h_rhs_witness] with p hL hR
  rw [hL, ← hR]

end SCM

end Causalean
