/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

import Mathlib.Data.Finset.Pi
import Mathlib.MeasureTheory.MeasurableSpace.Constructions
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.MeasureTheory.Measure.Typeclasses.Probability

/-! # Value assignments over finite node sets

This file provides the graph- and model-agnostic value-space infrastructure shared by the
structural-causal-model and potential-outcome frameworks: typed value assignments over a finite
node set (`ValuesOn`), their measurable coordinate restrictions, and the canonical measurable
equivalence and measure transport between assignments over propositionally equal node sets.

Nothing here mentions graphs, SWIGs, or the `SCM` structure — it is pure product-space
bookkeeping over a finite index `Finset`, so it lives in the `Mathlib` staging area rather than
in `SCM/`. The restriction map coincides with Mathlib's `Finset.restrict₂`; we keep the named
`valuesProjection`/`ValuesOn` vocabulary because it reads better at the many downstream call
sites and because `simp` lemmas throughout the library are keyed on these names.
-/

namespace Causalean

open scoped MeasureTheory

/-- A value assignment over a finite node set gives one value in the appropriate space for each
node in the set. -/
abbrev ValuesOn {M : Type*} [DecidableEq M] [Fintype M]
    (I : Finset M) (Ω : M → Type*) [∀ n, MeasurableSpace (Ω n)] :=
  ∀ i : {i // i ∈ I}, Ω i.val

/-- A value assignment can be restricted from a larger finite node set to a smaller one.

    This coincides definitionally with Mathlib's `Finset.restrict₂`; we keep the explicit
    lambda body because a large number of downstream proofs `simp [valuesProjection]` and rely
    on it unfolding to `fun ξ j => ξ ⟨j.val, hJI j.property⟩`. -/
def valuesProjection {M : Type*} [DecidableEq M] [Fintype M]
    {I J : Finset M} {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)]
    (hJI : J ⊆ I) : ValuesOn I Ω → ValuesOn J Ω :=
  fun ξ j => ξ ⟨j.val, hJI j.property⟩

/-- Restricting a value assignment to fewer coordinates is a measurable map.

    Coordinate restriction `valuesProjection hJI` is measurable; since it coincides with
    `Finset.restrict₂ hJI`, measurability is exactly `Finset.measurable_restrict₂`. -/
theorem measurable_valuesProjection {M : Type*} [DecidableEq M] [Fintype M]
    {I J : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hJI : J ⊆ I) : Measurable (valuesProjection (Ω := Ω') hJI) :=
  Finset.measurable_restrict₂ hJI

/-- The sigma-algebra generated by a coordinate restriction is contained in the ambient product
sigma-algebra.

    The comap of `valuesProjection` gives a sub-σ-algebra of the ambient
    measurable space on `ValuesOn I Ω`. -/
theorem comap_valuesProjection_le {M : Type*} [DecidableEq M] [Fintype M]
    {I W : Finset M} {Ω' : M → Type*} [∀ n, MeasurableSpace (Ω' n)]
    (hW : W ⊆ I) :
    MeasurableSpace.comap (valuesProjection (Ω := Ω') hW) inferInstance ≤
      (inferInstance : MeasurableSpace (ValuesOn I Ω')) :=
  Measurable.comap_le (measurable_valuesProjection hW)

/-- Value assignments over propositionally equal finite node sets are canonically measurably
equivalent.

    `ValuesOn I Ω` and `ValuesOn J Ω` are canonically measurably-equivalent when the
    index `Finset`s agree propositionally.  Packages the `valuesProjection`
    inverse pair so call sites avoid ad-hoc `▸`/`HEq` on the `Subtype` index. -/
noncomputable def valuesEquivOfEq {M : Type*} [DecidableEq M] [Fintype M]
    {I J : Finset M} {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)]
    (h : I = J) : ValuesOn I Ω ≃ᵐ ValuesOn J Ω where
  toFun := valuesProjection (le_of_eq h.symm)
  invFun := valuesProjection (le_of_eq h)
  left_inv := fun _ => rfl
  right_inv := fun _ => rfl
  measurable_toFun := measurable_valuesProjection (le_of_eq h.symm)
  measurable_invFun := measurable_valuesProjection (le_of_eq h)

/-- Product measures are preserved by the canonical equivalence between equal finite node sets.

    `Measure.pi` transports along `valuesEquivOfEq`: the equiv is measure-preserving
    between the two `Measure.pi`'s whose per-coordinate measures agree through the
    subtype transport of the index equality. -/
lemma measurePreserving_valuesEquivOfEq {M : Type*} [DecidableEq M] [Fintype M]
    {I J : Finset M} {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)]
    (h : I = J)
    (μ : (i : {i // i ∈ I}) → MeasureTheory.Measure (Ω i.val))
    [∀ i, MeasureTheory.IsProbabilityMeasure (μ i)] :
    MeasureTheory.MeasurePreserving (valuesEquivOfEq (Ω := Ω) h)
      (MeasureTheory.Measure.pi μ)
      (MeasureTheory.Measure.pi
        (fun j : {j // j ∈ J} => μ ⟨j.val, h ▸ j.property⟩)) := by
  subst h
  refine ⟨(valuesEquivOfEq (Ω := Ω) rfl).measurable, ?_⟩
  have hid : (⇑(valuesEquivOfEq (Ω := Ω) (rfl : I = I))
      : ValuesOn I Ω → ValuesOn I Ω) = id := by
    funext ξ; rfl
  rw [show (MeasureTheory.Measure.map (valuesEquivOfEq (Ω := Ω) rfl)
        (MeasureTheory.Measure.pi μ) : MeasureTheory.Measure _)
      = MeasureTheory.Measure.map id (MeasureTheory.Measure.pi μ) from by rw [hid]]
  rw [MeasureTheory.Measure.map_id]

/-- This map combines two coordinate assignments into one assignment on their union.

The first assignment takes priority on overlapping coordinates; the second
assignment is used on the remaining coordinates. -/
noncomputable def valuesUnionMk {M : Type*} [DecidableEq M] [Fintype M]
    {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)] {A B : Finset M}
    (a : ValuesOn A Ω) (b : ValuesOn B Ω) :
    ValuesOn (A ∪ B) Ω := fun ⟨v, hv⟩ =>
  if hA : v ∈ A then a ⟨v, hA⟩
  else b ⟨v, (Finset.mem_union.mp hv).resolve_left hA⟩

/-- Projecting the union assignment to a coordinate from the first input returns the first input's value. -/
@[simp] lemma valuesUnionMk_apply_left {M : Type*} [DecidableEq M] [Fintype M]
    {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)] {A B : Finset M}
    (a : ValuesOn A Ω) (b : ValuesOn B Ω)
    {v : M} (hv : v ∈ A ∪ B) (hA : v ∈ A) :
    valuesUnionMk a b ⟨v, hv⟩ = a ⟨v, hA⟩ := by
  unfold valuesUnionMk
  exact dif_pos hA

/-- Projecting the union assignment to a coordinate outside the first input returns the second input's value. -/
@[simp] lemma valuesUnionMk_apply_right {M : Type*} [DecidableEq M] [Fintype M]
    {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)] {A B : Finset M}
    (a : ValuesOn A Ω) (b : ValuesOn B Ω)
    {v : M} (hv : v ∈ A ∪ B) (hA : v ∉ A)
    (hB : v ∈ B := (Finset.mem_union.mp hv).resolve_left hA) :
    valuesUnionMk a b ⟨v, hv⟩ = b ⟨v, hB⟩ := by
  unfold valuesUnionMk
  exact dif_neg hA

/-- Combining assignments is measurable in the second assignment when the first assignment is held fixed.

At every output coordinate the value is either constant or a coordinate
projection of the second assignment. -/
lemma measurable_valuesUnionMk_right {M : Type*} [DecidableEq M] [Fintype M]
    {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)] {A B : Finset M}
    (a : ValuesOn A Ω) :
    Measurable (fun b : ValuesOn B Ω => valuesUnionMk a b) := by
  refine measurable_pi_iff.mpr ?_
  rintro ⟨v, hv⟩
  by_cases hA : v ∈ A
  · have h_eq :
        (fun b : ValuesOn B Ω => valuesUnionMk a b ⟨v, hv⟩)
          = (fun _ => a ⟨v, hA⟩) :=
      funext fun _ => valuesUnionMk_apply_left a _ hv hA
    rw [h_eq]
    exact measurable_const
  · have hB : v ∈ B := (Finset.mem_union.mp hv).resolve_left hA
    have h_eq :
        (fun b : ValuesOn B Ω => valuesUnionMk a b ⟨v, hv⟩)
          = (fun b => b ⟨v, hB⟩) :=
      funext fun _ => valuesUnionMk_apply_right a _ hv hA
    rw [h_eq]
    exact measurable_pi_apply _

/-- Combining assignments is jointly measurable in both input assignments. -/
lemma measurable_valuesUnionMk {M : Type*} [DecidableEq M] [Fintype M]
    {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)] {A B : Finset M} :
    Measurable
      (fun p : ValuesOn A Ω × ValuesOn B Ω =>
        valuesUnionMk p.1 p.2) := by
  refine measurable_pi_iff.mpr ?_
  rintro ⟨v, hv⟩
  by_cases hA : v ∈ A
  · have h_eq :
        (fun p : ValuesOn A Ω × ValuesOn B Ω =>
            valuesUnionMk p.1 p.2 ⟨v, hv⟩)
          = (fun p => p.1 ⟨v, hA⟩) := by
      funext p
      exact valuesUnionMk_apply_left _ _ hv hA
    rw [h_eq]
    exact (measurable_pi_apply _).comp measurable_fst
  · have hB : v ∈ B := (Finset.mem_union.mp hv).resolve_left hA
    have h_eq :
        (fun p : ValuesOn A Ω × ValuesOn B Ω =>
            valuesUnionMk p.1 p.2 ⟨v, hv⟩)
          = (fun p => p.2 ⟨v, hB⟩) := by
      funext p
      exact valuesUnionMk_apply_right _ _ hv hA
    rw [h_eq]
    exact (measurable_pi_apply _).comp measurable_snd

end Causalean
