/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Backdoor ATE identification in the Potential Outcome Framework

Implements the standard backdoor adjustment identity for the average treatment
effect (ATE) under the PO framework, with continuous covariate `X`, binary
treatment `D`, and real outcome `Y`.

Core identification (σ-algebra level):
    μ[Y(d) | σ(X)]  =ᵐ  μ[Y · 1_{D=d} | σ(X)] / P[D=d | σ(X)].

Integrated corollary:
    ATE = E[μ[Y(1)|σ(X)] − μ[Y(0)|σ(X)]].
-/

import Causalean.PO.Assumptions.ConsistencyLemmas
import Causalean.PO.Assumptions.IndepCF
import Causalean.PO.Conditioning.CondExpTooling
import Causalean.Mathlib.CondIndep
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Probability.ConditionalExpectation
import Mathlib.Probability.Independence.Conditional
import Mathlib.MeasureTheory.Function.FactorsThrough
import Causalean.Mathlib.MeasureTheory.CondExpIndicatorTower

/-! # Backdoor Average Treatment Effect

This file proves backdoor identification for the average treatment effect in
the potential-outcome framework. It connects conditional independence,
consistency, and overlap assumptions to the standard adjustment formula for
binary treatment and real-valued outcomes.

The adjustment covariate has an arbitrary measurable value space, so the same
setup covers discrete, continuous, and vector-valued covariates. The proof uses
conditional expectations with respect to the sigma-algebra generated by the
covariate.

The main public results are `cate_backdoor_of_propScore_ne`, which isolates the
per-arm propensity nonvanishing condition, `cate_backdoor` and `ate_backdoor`,
which discharge it from two-sided overlap, and `regression_adjustment`, which
shows the adjusted conditional functional is the observable regression
`E[Y | D=d, X]`. -/

namespace Causalean
namespace PO

open MeasureTheory ProbabilityTheory

/-- A backdoor system consists of a binary treatment, a real outcome, and an adjustment covariate.

The covariate may be discrete, continuous, or vector-valued through its arbitrary
measurable value space. -/
structure POBackdoorSystem (P : POSystem) (γ : Type*) [MeasurableSpace γ] where
  D : P.V
  Y : P.V
  Xvar : POVar P γ
  hDbool : P.X D ≃ᵐ Bool
  hYreal : P.X Y ≃ᵐ ℝ
  hDY : D ≠ Y
  hDX : D ≠ Xvar.v
  hYX : Y ≠ Xvar.v

namespace POBackdoorSystem

variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]
variable (S : POBackdoorSystem P γ)

/-- The treatment node is packaged as a binary potential-outcome variable. -/
def dVar : POVar P Bool := ⟨S.D, S.hDbool⟩
/-- The outcome node is packaged as a real-valued potential-outcome variable. -/
def yVar : POVar P ℝ := ⟨S.Y, S.hYreal⟩
/-- The adjustment covariate is the specified potential-outcome variable. -/
def xVar : POVar P γ := S.Xvar

/-- The potential outcome under a fixed treatment arm is a real-valued function on units. -/
noncomputable def YofD (d : Bool) : P.Ω → ℝ := S.yVar.cfUnder S.dVar d
/-- The factual treatment is the observed treatment assignment for each unit. -/
noncomputable def factualD : P.Ω → Bool := S.dVar.factual
/-- The factual outcome is the observed outcome for each unit. -/
noncomputable def factualY : P.Ω → ℝ := S.yVar.factual
/-- The factual covariate is the observed adjustment covariate for each unit. -/
noncomputable def factualX : P.Ω → γ := S.xVar.factual

/-- Potential outcomes under fixed treatment arms are measurable. -/
lemma measurable_YofD (d : Bool) : Measurable (S.YofD d) :=
  S.yVar.measurable_cfUnder S.dVar d
/-- The observed treatment is measurable. -/
lemma measurable_factualD : Measurable S.factualD := S.dVar.measurable_factual
/-- The observed outcome is measurable. -/
lemma measurable_factualY : Measurable S.factualY := S.yVar.measurable_factual
/-- The observed covariate is measurable. -/
lemma measurable_factualX : Measurable S.factualX := S.xVar.measurable_factual

/-- The covariate sigma-algebra is generated by the observed covariate. -/
noncomputable def sigmaX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualX inferInstance

/-- The covariate sigma-algebra is a sub-sigma-algebra of the ambient one. -/
lemma sigmaX_le : S.sigmaX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_factualX.comap_le

/-- The regimed form of the potential outcome fixes treatment to the chosen arm. -/
def yUnderD (d : Bool) : RegimedVar P ℝ :=
  ⟨S.yVar, Regime.single S.D (S.hDbool.symm d)⟩

/-- The counterfactual bundle collects the treated and untreated potential
outcomes for unconfoundedness. -/
noncomputable def cfBundle : POCFBundle P :=
  POCFBundle.cons (S.yUnderD true) <|
  POCFBundle.cons (S.yUnderD false) <|
  POCFBundle.nil P

/-- The propensity score is the conditional probability of a treatment arm given the covariate. -/
noncomputable def propScore (d : Bool) : P.Ω → ℝ :=
  P.μ[S.dVar.indicator d | S.sigmaX]

/-- The conditional mean potential outcome is the mean of a treatment-arm
potential outcome given the covariate. -/
noncomputable def CATE (d : Bool) : P.Ω → ℝ :=
  P.μ[S.YofD d | S.sigmaX]

/-- The ATE is the population mean difference between treated and untreated potential outcomes. -/
noncomputable def ATE : ℝ := ∫ ω, S.YofD true ω - S.YofD false ω ∂P.μ

/-- The adjusted conditional functional is the observable outcome-indicator
regression divided by the propensity score. -/
noncomputable def adjustedCE (d : Bool) : P.Ω → ℝ :=
  fun ω => P.μ[fun ω' => S.factualY ω' * S.dVar.indicator d ω' | S.sigmaX] ω / S.propScore d ω

/-- The adjusted ATE integrates the difference of the two adjusted conditional
outcome functionals. -/
noncomputable def adjustedATE : ℝ :=
  ∫ ω, S.adjustedCE true ω - S.adjustedCE false ω ∂P.μ

/-- The backdoor (Rosenbaum–Rubin / Firpo) identifying assumptions for the ATE,
at the potential-outcome level: for binary treatment `D` and real outcome `Y`,
adjusting for covariates `X` identifies `E[Y(1) − Y(0)]`. Bundles the four
standard conditions below. -/
structure Assumptions (S : POBackdoorSystem P γ)
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ] : Prop where
  /-- Consistency (SUTVA): the observed outcome equals the potential outcome of
  the realized arm — on `{D = d}`, `Y = Y(d)`. Links observed data to the
  potential outcomes. -/
  consistency : P.Consistency
  /-- Unconfoundedness (conditional ignorability): treatment is independent of the
  potential outcomes given the covariates, `D ⟂ (Y(1), Y(0)) | X`. Stated as
  conditional independence of the realized `D` and the counterfactual bundle
  `(Y(1), Y(0))` given `σ(X)`. -/
  unconfoundedness :
    P.CondIndepCF (RegimedVar.ofFactual S.dVar) S.cfBundle
      (RegimedVar.ofFactual S.xVar) P.μ
  /-- Overlap (common support): every covariate stratum has a positive chance of
  EITHER arm — `0 < P[D=1 | σ(X)] < 1` a.s. Two-sided here because the ATE needs
  both arms identified at every `x`. Bare positivity (not a uniform `c ≤ e ≤ 1−c`
  strong-overlap bound, which is only needed for efficient-estimator asymptotics),
  mirroring DTR. -/
  overlap :
    ∀ᵐ ω ∂P.μ, 0 < S.propScore true ω ∧ S.propScore true ω < 1
  /-- Regularity: the treated potential outcome `Y(1)` is integrable (so `E[Y(1)]`
  is well-defined). -/
  integrable_Y1 : Integrable (S.YofD true) P.μ
  /-- Regularity: the control potential outcome `Y(0)` is integrable (so `E[Y(0)]`
  is well-defined). -/
  integrable_Y0 : Integrable (S.YofD false) P.μ

/-- Factual `Y` is integrable whenever both treatment-arm potential outcomes are
integrable and consistency links the observed outcome to the realized arm. -/
lemma integrable_factualY_of_consistency
    (hcons : P.Consistency)
    (hY1 : Integrable (S.YofD true) P.μ)
    (hY0 : Integrable (S.YofD false) P.μ) :
    Integrable S.factualY P.μ := by
  have hY1_ind :
      Integrable (fun ω => S.YofD true ω * S.dVar.indicator true ω) P.μ :=
    S.dVar.integrable_mul_indicator true hY1 (S.measurable_YofD true)
  have hY0_ind :
      Integrable (fun ω => S.YofD false ω * S.dVar.indicator false ω) P.μ :=
    S.dVar.integrable_mul_indicator false hY0 (S.measurable_YofD false)
  have hsum_int :
      Integrable
        (fun ω => S.YofD true ω * S.dVar.indicator true ω
          + S.YofD false ω * S.dVar.indicator false ω) P.μ :=
    hY1_ind.add hY0_ind
  refine hsum_int.congr ?_
  filter_upwards with ω
  have htrue := congr_fun
    (POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar true (Ne.symm S.hDY)) ω
  have hfalse := congr_fun
    (POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar false (Ne.symm S.hDY)) ω
  have htrue' : S.YofD true ω * S.dVar.indicator true ω =
      S.factualY ω * S.dVar.indicator true ω := by
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY] using htrue.symm
  have hfalse' : S.YofD false ω * S.dVar.indicator false ω =
      S.factualY ω * S.dVar.indicator false ω := by
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY] using hfalse.symm
  have hsum := S.dVar.indicator_add_indicator_not ω
  calc
    S.YofD true ω * S.dVar.indicator true ω
        + S.YofD false ω * S.dVar.indicator false ω
        = S.factualY ω * S.dVar.indicator true ω
          + S.factualY ω * S.dVar.indicator false ω := by
          rw [htrue', hfalse']
    _ = S.factualY ω *
            (S.dVar.indicator true ω + S.dVar.indicator false ω) := by
          ring
    _ = S.factualY ω := by
          rw [hsum, mul_one]

/-- The observed outcome is integrable under the backdoor assumption bundle. -/
lemma Assumptions.integrable_factualY
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ] (hA : S.Assumptions) :
    Integrable S.factualY P.μ :=
  S.integrable_factualY_of_consistency
    hA.consistency hA.integrable_Y1 hA.integrable_Y0

/-- From two-sided overlap, the per-arm propensity score `P[D=d | σ(X)]` is a.s.
nonzero: for `d = true` directly from `0 < e(X)`, for `d = false` from
`e(X) < 1` via `propScore false = 1 - e(X)`. -/
lemma propScore_ne_of_overlap [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hov : ∀ᵐ ω ∂P.μ, 0 < S.propScore true ω ∧ S.propScore true ω < 1) (d : Bool) :
    ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0 := by
  cases d
  · -- false: propScore false = 1 - propScore true, and propScore true < 1.
    have hindD_integrable : ∀ e : Bool, Integrable (S.dVar.indicator e) P.μ :=
      fun e => S.dVar.integrable_indicator e
    have hsum_ptwise :
        (fun ω => S.dVar.indicator true ω + S.dVar.indicator false ω)
          = (fun _ : P.Ω => (1 : ℝ)) := by
      funext ω
      exact S.dVar.indicator_add_indicator_not ω
    have hsum :
        P.μ[fun ω => S.dVar.indicator true ω + S.dVar.indicator false ω | S.sigmaX]
          =ᵐ[P.μ] (fun _ => (1 : ℝ)) := by
      rw [hsum_ptwise]
      exact Filter.EventuallyEq.of_eq (MeasureTheory.condExp_const S.sigmaX_le (1 : ℝ))
    have hadd :
        P.μ[fun ω => S.dVar.indicator true ω + S.dVar.indicator false ω | S.sigmaX]
          =ᵐ[P.μ]
            P.μ[S.dVar.indicator true | S.sigmaX]
              + P.μ[S.dVar.indicator false | S.sigmaX] :=
      MeasureTheory.condExp_add (hindD_integrable true) (hindD_integrable false) S.sigmaX
    filter_upwards [hsum, hadd, hov] with ω h1 h2 hT
    have heq : S.propScore true ω + S.propScore false ω = 1 := by
      have : P.μ[S.dVar.indicator true | S.sigmaX] ω
            + P.μ[S.dVar.indicator false | S.sigmaX] ω = 1 := by
        rw [← Pi.add_apply, ← h2, h1]
      unfold POBackdoorSystem.propScore
      exact this
    have hps_false : S.propScore false ω = 1 - S.propScore true ω := by linarith
    rw [hps_false]
    intro h
    linarith [hT.2]
  · filter_upwards [hov] with ω hω
    exact ne_of_gt hω.1

/-- **CATE-level backdoor identification (per-arm overlap form).** The conditional
ATE equals the adjusted-outcome functional under consistency, unconfoundedness,
arm-wise outcome integrability, and the single one-sided requirement that the
`d`-arm propensity score is a.s. nonzero (`P[D=d | σ(X)] ≠ 0`):

    μ[Y(d) | σ(X)] =ᵐ[μ] μ[Y · 1_{D=d} | σ(X)] / P[D=d | σ(X)].

This isolates the *only* place two-sided overlap is used in backdoor CATE
identification — the nonvanishing of the relevant arm's propensity score — so
ATT identification, which needs only the control arm (`e(X) < 1`), can reuse the
machinery without assuming `0 < e(X)`. The `Assumptions`-based `cate_backdoor` is
the two-sided wrapper. -/
theorem cate_backdoor_of_propScore_ne [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hcons : P.Consistency)
    (hunconf : P.CondIndepCF (RegimedVar.ofFactual S.dVar) S.cfBundle
      (RegimedVar.ofFactual S.xVar) P.μ)
    (hY1 : Integrable (S.YofD true) P.μ) (hY0 : Integrable (S.YofD false) P.μ)
    (d : Bool) (h_ne : ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0) :
    S.CATE d =ᵐ[P.μ] S.adjustedCE d := by
  -- Rewrite `adjustedCE d = condExpRatio S.xVar (factualY * indD d) (indD d) P.μ`.
  have hratio_def :
      S.adjustedCE d
        = S.xVar.condExpRatio
          (fun ω => S.factualY ω * S.dVar.indicator d ω)
          (S.dVar.indicator d) P.μ := by
    funext ω
    unfold POBackdoorSystem.adjustedCE POBackdoorSystem.propScore
      POBackdoorSystem.sigmaX POBackdoorSystem.factualX POVar.condExpRatio
      POVar.condExpGiven
    rfl
  rw [hratio_def]
  -- Apply `condExpRatio_eq_of_mul` to reduce to (hprod) and (hne).
  refine (S.xVar.condExpRatio_eq_of_mul (g := fun ω => S.factualY ω * S.dVar.indicator d ω)
      (h := S.dVar.indicator d) (target := S.CATE d) ?_ ?_).symm
  · -- (hprod): μ[Y·1_{D=d}|σX] =ᵐ μ[1_{D=d}|σX] · CATE d.
    -- Integrability prerequisites.
    have hindD_integrable : Integrable (S.dVar.indicator d) P.μ :=
      S.dVar.integrable_indicator d
    have hYofD_integrable : Integrable (S.YofD d) P.μ := by
      cases d
      · exact hY0
      · exact hY1
    have hYofD_bdd_integrable_aux :
        Integrable (fun ω => S.YofD d ω * S.dVar.indicator d ω) P.μ := by
      exact S.dVar.integrable_mul_indicator d hYofD_integrable (S.measurable_YofD d)
    have hYtimesInd_integrable :
        Integrable (fun ω => S.factualY ω * S.dVar.indicator d ω) P.μ := by
      exact S.dVar.integrable_mul_indicator d
        (S.integrable_factualY_of_consistency hcons hY1 hY0) S.measurable_factualY
    -- Step 1: μ[Y·1_{D=d}|σX] =ᵐ μ[Y(d)·1_{D=d}|σX].
    have hstep1 :
        S.xVar.condExpGiven (fun ω => S.factualY ω * S.dVar.indicator d ω) P.μ
          =ᵐ[P.μ] S.xVar.condExpGiven
            (fun ω => S.YofD d ω * S.dVar.indicator d ω) P.μ := by
      have hvw : S.yVar.v ≠ S.dVar.v := Ne.symm S.hDY
      have hfm :=
        POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
          hcons S.yVar S.dVar d hvw
      -- `S.factualY = S.yVar.factual` and `S.YofD d = S.yVar.cfUnder S.dVar d` by def.
      change S.xVar.condExpGiven
          (fun ω => S.yVar.factual ω * S.dVar.indicator d ω) P.μ
          =ᵐ[P.μ] S.xVar.condExpGiven
            (fun ω => S.yVar.cfUnder S.dVar d ω * S.dVar.indicator d ω) P.μ
      rw [hfm]
    refine hstep1.trans ?_
    -- Project unconfoundedness onto the `d`-th coordinate of the bundle.
    -- The bundle has two components: index 0 = YofD true, index 1 = YofD false.
    let ψ : (∀ i : Fin S.cfBundle.n, S.cfBundle.type i) → ℝ :=
      fun f => match d with
        | true  => f (0 : Fin 2)
        | false => f (1 : Fin 2)
    have hψ_meas : Measurable ψ := by
      cases d with
      | true  => exact measurable_pi_apply (0 : Fin 2)
      | false => exact measurable_pi_apply (1 : Fin 2)
    have hYofD_eq : S.YofD d = ψ ∘ S.cfBundle.jointValue := by
      funext ω; cases d <;> rfl
    have hCI :
        ProbabilityTheory.CondIndepFun S.sigmaX S.sigmaX_le
          S.factualD (S.YofD d) P.μ := by
      have hproj := hunconf.project (ψ := ψ) hψ_meas
      rw [hYofD_eq]; exact hproj
    -- Apply factorization with u := indD d (as a function of factualD) and v := YofD d.
    -- Use the plain pointwise product: indD d ω * YofD d ω.
    have hindMul_swap :
        (fun ω => S.YofD d ω * S.dVar.indicator d ω)
          = (fun ω => S.dVar.indicator d ω * S.YofD d ω) := by
      funext ω; exact mul_comm _ _
    rw [hindMul_swap]
    -- Apply via an auxiliary lemma that takes the (u, v) shapes matching our data.
    -- Use `condExp_mul_of_condIndep` with:
    --   f = factualD, g = YofD d, u = (fun b => if b = d then 1 else 0), v = id.
    -- `u (factualD ω) = indD d ω` and `id (YofD d ω) = YofD d ω` by rfl.
    -- Set-indicator packaging: `u b := ({d} : Set Bool).indicator 1 b`, which
    -- satisfies `u (S.factualD ω) = S.dVar.indicator d ω`.
    let u : Bool → ℝ := ({d} : Set Bool).indicator (fun _ => (1 : ℝ))
    have hu_meas : Measurable u :=
      measurable_const.indicator (MeasurableSet.singleton d)
    have hu_eq : (fun ω => u (S.factualD ω)) = S.dVar.indicator d := by
      funext ω
      unfold POVar.indicator
      by_cases h : S.factualD ω = d
      · have h1 : S.factualD ω ∈ ({d} : Set Bool) := h
        have h2 : ω ∈ S.dVar.event d := h
        rw [show u (S.factualD ω) = (1 : ℝ) from Set.indicator_of_mem h1 _,
            Set.indicator_of_mem h2]
      · have h1 : S.factualD ω ∉ ({d} : Set Bool) := h
        have h2 : ω ∉ S.dVar.event d := h
        rw [show u (S.factualD ω) = (0 : ℝ) from Set.indicator_of_notMem h1 _,
            Set.indicator_of_notMem h2]
    have huMul_int :
        MeasureTheory.Integrable
          (fun ω => u (S.factualD ω) * S.YofD d ω) P.μ := by
      have hEq : (fun ω => u (S.factualD ω) * S.YofD d ω)
          = (fun ω => S.YofD d ω * S.dVar.indicator d ω) := by
        funext ω; rw [show u (S.factualD ω) = S.dVar.indicator d ω from
          congr_fun hu_eq ω]; ring
      rw [hEq]; exact hYofD_bdd_integrable_aux
    have hfact :
        P.μ[fun ω => u (S.factualD ω) * S.YofD d ω | S.sigmaX]
          =ᵐ[P.μ]
            P.μ[fun ω => u (S.factualD ω) | S.sigmaX]
              * P.μ[fun ω => S.YofD d ω | S.sigmaX] := by
      have := condExp_mul_of_condIndep (μ := P.μ) (m := S.sigmaX) S.sigmaX_le
          (f := S.factualD) (g := S.YofD d)
          S.measurable_factualD (S.measurable_YofD d) hCI
          (u := u) (v := id) hu_meas measurable_id
          (by rw [hu_eq]; exact hindD_integrable)
          hYofD_integrable huMul_int
      exact this
    -- Goal (after hindMul_swap):
    --   S.xVar.condExpGiven (indD d * YofD d) =ᵐ S.xVar.condExpGiven (indD d) * CATE d.
    -- Unfold condExpGiven/CATE to land on μ[·|σX] with matching argument shapes.
    unfold POVar.condExpGiven POBackdoorSystem.CATE
      POBackdoorSystem.sigmaX POBackdoorSystem.factualX
    have hfact_rw : (fun ω => u (S.factualD ω)) = S.dVar.indicator d := hu_eq
    have hprod_rw : (fun ω => u (S.factualD ω) * S.YofD d ω)
        = (fun ω => S.dVar.indicator d ω * S.YofD d ω) := by
      funext ω; rw [congr_fun hu_eq ω]
    rw [hprod_rw, hfact_rw] at hfact
    exact hfact
  · -- (hne): μ[1_{D=d}|σX] ≠ 0 a.s. — supplied directly as `h_ne`.
    -- `S.xVar.condExpGiven (S.dVar.indicator d) P.μ = S.propScore d` definitionally.
    have hEq : S.xVar.condExpGiven (S.dVar.indicator d) P.μ = S.propScore d := by
      unfold POVar.condExpGiven POBackdoorSystem.propScore
        POBackdoorSystem.sigmaX POBackdoorSystem.factualX
      rfl
    rw [hEq]
    exact h_ne

/-- **CATE-level backdoor identification.**  Under consistency, unconfoundedness,
and (two-sided) overlap, the conditional ATE equals the adjusted-outcome
functional:

    μ[Y(d) | σ(X)] =ᵐ[μ] μ[Y · 1_{D=d} | σ(X)] / P[D=d | σ(X)].

Two-sided wrapper around `cate_backdoor_of_propScore_ne`: it discharges the
per-arm nonvanishing hypothesis from `Assumptions.overlap` via
`propScore_ne_of_overlap`. -/
theorem cate_backdoor [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) (d : Bool) :
    S.CATE d =ᵐ[P.μ] S.adjustedCE d :=
  S.cate_backdoor_of_propScore_ne hA.consistency hA.unconfoundedness
    hA.integrable_Y1 hA.integrable_Y0 d (S.propScore_ne_of_overlap hA.overlap d)

/-- **Integrated backdoor ATE identification.** -/
theorem ate_backdoor [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) : S.ATE = S.adjustedATE := by
  unfold POBackdoorSystem.ATE POBackdoorSystem.adjustedATE
  -- `CATE d = xVar.condExpGiven (YofD d) P.μ` definitionally.
  have hf' : S.xVar.condExpGiven (S.YofD true) P.μ =ᵐ[P.μ] S.adjustedCE true :=
    S.cate_backdoor hA true
  have hg' : S.xVar.condExpGiven (S.YofD false) P.μ =ᵐ[P.μ] S.adjustedCE false :=
    S.cate_backdoor hA false
  exact S.xVar.integral_sub_eq_integral_sub_of_condExpGiven_ae_eq
    hA.integrable_Y1 hA.integrable_Y0 hf' hg'

/-! ## Regression-adjustment identification: the adjustment functional is a regression

`cate_backdoor` identifies the *counterfactual* conditional mean `μ[Y(d)|σX]` with
the adjustment functional `adjustedCE d` (needs unconfoundedness). The results below
supply the missing, purely *observable* fact that `adjustedCE d` is the **outcome
regression of the observed `Y` on the observed `(D, X)`** — a statement about the
law of `(X, D, Y)` only — certifying that estimating `μ` is a standard regression
problem (the one `ML/CausalApplication/RegressionBridge.lean` solves). Together they give the
chain `E[Y(d)|X] =ᵐ adjustedCE d =ᵐ E[Y|D=d,X]`. -/

/-- Factual `(D, X)` pair `ω ↦ (factualD ω, factualX ω) : Ω → Bool × γ`. The
covariate–treatment cell each unit lands in. -/
noncomputable def factualDX : P.Ω → Bool × γ :=
  fun ω => (S.factualD ω, S.factualX ω)

/-- The observed treatment-covariate pair is measurable. -/
lemma measurable_factualDX : Measurable S.factualDX :=
  S.measurable_factualD.prodMk S.measurable_factualX

/-- σ-algebra generated by the factual `(D, X)`. Contains `σ(X)` (snd projection)
and is the information a regression of `Y` on `(D, X)` may use. -/
noncomputable def sigmaDX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualDX inferInstance

/-- The joint treatment-covariate sigma-algebra is a sub-sigma-algebra of the ambient one. -/
lemma sigmaDX_le : S.sigmaDX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_factualDX.comap_le

/-- `σ(X) ≤ σ(D, X)`: the covariate σ-algebra is coarser than the joint one. -/
lemma sigmaX_le_sigmaDX : S.sigmaX ≤ S.sigmaDX := by
  -- `factualX = Prod.snd ∘ factualDX`, so `comap factualX ≤ comap factualDX`.
  have hfx : S.factualX = Prod.snd ∘ S.factualDX := rfl
  rw [POBackdoorSystem.sigmaX, POBackdoorSystem.sigmaDX, hfx,
    ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono measurable_snd.comap_le

/-- **Outcome regression** `E[Y | D, X] := μ[factualY | σ(D, X)]`, the conditional
mean of the *observed* outcome given the *observed* treatment and covariate. A
functional of the observed data law, learnable by regressing `Y` on `(D, X)`. -/
noncomputable def outcomeReg : P.Ω → ℝ :=
  P.μ[S.factualY | S.sigmaDX]

/-- The observed outcome regression is strongly measurable with respect to the
joint treatment-covariate sigma-algebra. -/
lemma stronglyMeasurable_outcomeReg :
    StronglyMeasurable[S.sigmaDX] S.outcomeReg :=
  MeasureTheory.stronglyMeasurable_condExp

/-- The `σ(D, X)`-measurable `outcomeReg` factors through `(D, X)`: there is a
measurable value-space regression function `r : Bool × γ → ℝ` with
`outcomeReg = r ∘ factualDX`. This is Doob–Dynkin (`exists_eq_measurable_comp`);
`r` is the function an ML regressor of `Y` on `(D, X)` targets. -/
lemma exists_regFn :
    ∃ r : Bool × γ → ℝ, Measurable r ∧
      S.outcomeReg = fun ω => r (S.factualDX ω) := by
  -- `sigmaDX = comap factualDX`, so `outcomeReg` is `comap factualDX`-measurable;
  -- Doob–Dynkin (`exists_eq_measurable_comp`) produces the value-space factorisation.
  have hmeas : Measurable[S.sigmaDX] S.outcomeReg :=
    S.stronglyMeasurable_outcomeReg.measurable
  obtain ⟨r, hr_meas, hr_eq⟩ :=
    Measurable.exists_eq_measurable_comp (f := S.factualDX) (g := S.outcomeReg) hmeas
  exact ⟨r, hr_meas, by funext ω; exact congrFun hr_eq ω⟩

/-- Value-space outcome regression `regFn (d, x) = E[Y | D=d, X=x]`. -/
noncomputable def regFn : Bool × γ → ℝ := S.exists_regFn.choose

/-- The value-space outcome regression is measurable. -/
lemma measurable_regFn : Measurable S.regFn := S.exists_regFn.choose_spec.1

/-- The observed outcome regression equals the value-space regression evaluated
at each unit's observed treatment and covariate. -/
lemma outcomeReg_eq_regFn :
    S.outcomeReg = fun ω => S.regFn (S.factualDX ω) :=
  S.exists_regFn.choose_spec.2

/-- The `σ(X)`-measurable propensity `propScore true` factors through `factualX`:
a measurable value-space propensity `e : γ → ℝ` with `propScore true = e ∘ factualX`
(Doob–Dynkin). This is the value-space propensity an estimator learns. -/
lemma exists_propScoreLift :
    ∃ e : γ → ℝ, Measurable e ∧ S.propScore true = fun ω => e (S.factualX ω) := by
  have hmeas : Measurable[S.sigmaX] (S.propScore true) :=
    (MeasureTheory.stronglyMeasurable_condExp).measurable
  obtain ⟨e, he_meas, he_eq⟩ :=
    Measurable.exists_eq_measurable_comp (f := S.factualX) (g := S.propScore true) hmeas
  exact ⟨e, he_meas, by funext ω; exact congrFun he_eq ω⟩

/-- Value-space propensity `eLift x` (a measurable representative of `E[D | X=x]`). -/
noncomputable def eLift : γ → ℝ := S.exists_propScoreLift.choose

/-- The value-space propensity representative is measurable. -/
lemma measurable_eLift : Measurable S.eLift := S.exists_propScoreLift.choose_spec.1

/-- The treated-arm propensity score equals the value-space propensity evaluated
at each unit's observed covariate. -/
lemma propScore_true_eq_eLift :
    S.propScore true = fun ω => S.eLift (S.factualX ω) :=
  S.exists_propScoreLift.choose_spec.2

/-- **Regression-adjustment identification (observable).** The adjustment
functional equals the value-space outcome regression evaluated at the arm `d`:

    adjustedCE d  =ᵐ  fun ω => regFn (d, factualX ω)  = E[Y | D=d, X].

This is a fact about the observed law of `(X, D, Y)` alone — it needs overlap
(`P[D=d | σ(X)] ≠ 0`) but NOT unconfoundedness. Combined with `cate_backdoor` it
completes the chain `E[Y(d)|X] =ᵐ adjustedCE d =ᵐ E[Y|D=d,X]`, certifying the
back-door nuisance `μ` as a genuine regression problem. -/
theorem regression_adjustment [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (d : Bool) (hY : Integrable S.factualY P.μ)
    (h_ne : ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0) :
    S.adjustedCE d =ᵐ[P.μ] (fun ω => S.regFn (d, S.factualX ω)) := by
  have hratio_def :
      S.adjustedCE d
        = S.xVar.condExpRatio
          (fun ω => S.factualY ω * S.dVar.indicator d ω)
          (S.dVar.indicator d) P.μ := by
    funext ω
    unfold POBackdoorSystem.adjustedCE POBackdoorSystem.propScore
      POBackdoorSystem.sigmaX POBackdoorSystem.factualX POVar.condExpRatio
      POVar.condExpGiven
    rfl
  rw [hratio_def]
  refine S.xVar.condExpRatio_eq_of_mul
    (g := fun ω => S.factualY ω * S.dVar.indicator d ω)
    (h := S.dVar.indicator d)
    (target := fun ω => S.regFn (d, S.factualX ω)) ?_ ?_
  · have hYint : Integrable S.factualY P.μ := hY
    · let s : Set P.Ω := S.dVar.event d
      let target : P.Ω → ℝ := fun ω => S.regFn (d, S.factualX ω)
      have hsDX : MeasurableSet[S.sigmaDX] s := by
        change MeasurableSet[MeasurableSpace.comap S.factualDX inferInstance]
          (S.factualD ⁻¹' {d})
        exact ⟨Prod.fst ⁻¹' {d}, measurableSet_singleton d |>.preimage measurable_fst, rfl⟩
      have hs : MeasurableSet s := S.dVar.measurableSet_event d
      have hmul_indicator :
          (fun ω => S.factualY ω * S.dVar.indicator d ω) = s.indicator S.factualY := by
        funext ω
        by_cases hω : ω ∈ s
        · have hind : S.dVar.indicator d ω = 1 := S.dVar.indicator_apply_eq_one hω
          rw [hind, mul_one, Set.indicator_of_mem hω]
        · have hD : S.factualD ω ≠ d := hω
          have hind : S.dVar.indicator d ω = 0 := S.dVar.indicator_apply_eq_zero hD
          rw [hind, mul_zero, Set.indicator_of_notMem hω]
      have htarget_meas : Measurable[S.sigmaX] target := by
        have hreg_d : Measurable (fun x : γ => S.regFn (d, x)) :=
          S.measurable_regFn.comp (measurable_const.prodMk measurable_id)
        change Measurable[MeasurableSpace.comap S.factualX inferInstance]
          ((fun x : γ => S.regFn (d, x)) ∘ S.factualX)
        exact hreg_d.comp (comap_measurable S.factualX)
      have htarget_sm : StronglyMeasurable[S.sigmaX] target :=
        htarget_meas.stronglyMeasurable
      have houtcome_target :
          s.indicator S.outcomeReg = s.indicator target := by
        funext ω
        by_cases hω : ω ∈ s
        · have hD : S.factualD ω = d := hω
          rw [Set.indicator_of_mem hω, Set.indicator_of_mem hω]
          rw [congrFun S.outcomeReg_eq_regFn ω]
          simp [target, POBackdoorSystem.factualDX, hD]
        · rw [Set.indicator_of_notMem hω, Set.indicator_of_notMem hω]
      have htower :
          P.μ[s.indicator S.factualY | S.sigmaX]
            =ᵐ[P.μ] P.μ[s.indicator S.outcomeReg | S.sigmaX] := by
        simpa [s, POBackdoorSystem.outcomeReg] using
          MeasureTheory.condExp_setIndicator_condExp_of_le
            (μ := P.μ) (m := S.sigmaX) (m' := S.sigmaDX)
            S.sigmaX_le_sigmaDX S.sigmaDX_le hsDX hYint
      have hleft :
          P.μ[fun ω => S.factualY ω * S.dVar.indicator d ω | S.sigmaX]
            =ᵐ[P.μ] P.μ[s.indicator target | S.sigmaX] :=
        (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ)
          (Filter.EventuallyEq.of_eq hmul_indicator)).trans
          (htower.trans
            (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ)
              (Filter.EventuallyEq.of_eq houtcome_target)))
      have hind_int : Integrable (S.dVar.indicator d) P.μ :=
        S.dVar.integrable_indicator d
      have htarget_mul_indicator :
          target * S.dVar.indicator d = s.indicator target := by
        funext ω
        by_cases hω : ω ∈ s
        · have hind : S.dVar.indicator d ω = 1 := S.dVar.indicator_apply_eq_one hω
          rw [Pi.mul_apply, hind, mul_one, Set.indicator_of_mem hω]
        · have hD : S.factualD ω ≠ d := hω
          have hind : S.dVar.indicator d ω = 0 := S.dVar.indicator_apply_eq_zero hD
          rw [Pi.mul_apply, hind, mul_zero, Set.indicator_of_notMem hω]
      have htarget_mul_int : Integrable (target * S.dVar.indicator d) P.μ := by
        rw [htarget_mul_indicator]
        have houtcome_target' :
            s.indicator (P.μ[S.factualY | S.sigmaDX]) = s.indicator target := by
          simpa [POBackdoorSystem.outcomeReg] using houtcome_target
        exact MeasureTheory.Integrable.indicator
          (MeasureTheory.integrable_condExp (μ := P.μ) (m := S.sigmaDX) (f := S.factualY)) hs
            |>.congr (Filter.EventuallyEq.of_eq houtcome_target')
      have hpull :
          P.μ[target * S.dVar.indicator d | S.sigmaX]
            =ᵐ[P.μ] target * P.μ[S.dVar.indicator d | S.sigmaX] :=
        MeasureTheory.condExp_mul_of_stronglyMeasurable_left
          (m := S.sigmaX) (μ := P.μ) htarget_sm htarget_mul_int hind_int
      change P.μ[fun ω => S.factualY ω * S.dVar.indicator d ω | S.sigmaX]
          =ᵐ[P.μ] P.μ[S.dVar.indicator d | S.sigmaX] * target
      refine hleft.trans ?_
      refine (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ)
        (Filter.EventuallyEq.of_eq htarget_mul_indicator.symm)).trans ?_
      exact hpull.trans (Filter.EventuallyEq.of_eq (by
        funext ω
        exact mul_comm _ _))
  · have hEq : S.xVar.condExpGiven (S.dVar.indicator d) P.μ = S.propScore d := by
      unfold POVar.condExpGiven POBackdoorSystem.propScore
        POBackdoorSystem.sigmaX POBackdoorSystem.factualX
      rfl
    rw [hEq]
    exact h_ne

/-- **Regression-adjustment, packaged for identified systems.** The same observable
identity `adjustedCE d =ᵐ E[Y|D=d,X]`, with the two regularity hypotheses of
`regression_adjustment` discharged from the back-door `Assumptions`: integrability of
the observed outcome from `Assumptions.integrable_factualY`, and overlap from
`propScore_ne_of_overlap`. Lets callers in an identified context apply it with just
`hA`. -/
theorem regression_adjustment_of_assumptions [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) (d : Bool) :
    S.adjustedCE d =ᵐ[P.μ] (fun ω => S.regFn (d, S.factualX ω)) :=
  S.regression_adjustment d hA.integrable_factualY (S.propScore_ne_of_overlap hA.overlap d)

end POBackdoorSystem

end PO
end Causalean
